### PR TITLE
Fix: solana stakes <pubkey> clean handling

### LINKED ISSUE #8441: `solana stakes <vote pubkey>` should cleanly handle a non-vote pubkey
`solana stakes <identity pubkey>` or `solana stakes <does not exist pubkey>` all silently return nothing. 

Lets:
* If possible make `solana stakes <identity pubkey>` report the stakes from the corresponding vote account
* `solana stakes <does not exist pubkey>` report that the account was not found
* `solana stakes <some other account pubkey>` report that the account is invalid

### PR DESCRIPTION
**Pull request by kubanemil**
#### Problem
- Returns no message if invalid pubkey(s) are provided.
- Does not search for identity pubkeys.

#### Summary of Changes

- Retrieval of matching vote account from identity/vote pubkey. If invalid pubkey(s) are provided, it will throw an error without continuing with valid ones.
- Added separate progress bars for fetching vote accounts and for fetching stake accounts
- returns a message if no stake accounts are found for the vote account.

I decided not to continue with pubkeys if some of them are invalid, because the message might go unnoticed by the user when a lot of stake accounts are displayed.

@mvines  @CriesofCarrots  Waiting for your reviews and your thoughts about my suggestion below. 
(fyi, I've tested CLI with my changes - everything works as expected)

#### Suggestion
Should I change an argument name of `<VOTE_ACCOUNT_PUBKEYS>` to `<VALIDATOR_ACCOUNT_PUBKEY>` in the help description if `$ solana stakes <>` now supports both identity and vote pubkeys?
Also, I think if `$ solana stakes` is run without any pubkey, it shouldn't return all stake accounts. What about putting some limit (like a max of 50/100 displayed stake accounts) on?

Closes https://github.com/solana-labs/solana/issues/8441

### CODE REVIEW

File: cli/src/cluster_query.rs [hunk 1]
```diff
@@ -1791,53 +1823,74 @@ pub fn process_show_stakes(
...
+            if let Some(withdraw_authority_filter) = &withdraw_authority_filter {
+                program_accounts_config.filters.as_mut().unwrap().push(
+                    withdraw_authority_filter.clone()
+                );
+            }
+            all_stake_accounts.append(
+                &mut rpc_client.get_program_accounts_with_config(
+                    &stake::program::id(), 
+                    program_accounts_config.clone()
+                )?
```
Comment (CriesofCarrots) [inline cli/src/cluster_query.rs]: Unfortunately, `get_program_accounts` calls are very expensive; it is not feasible to call this multiple times with different server-side filters. This needs to be called only once and filtered client-side.

**Review by CriesofCarrots — DISMISSED** [review]
Please make sure to run `cargo fmt` and `cargo clippy` on the next iteration

File: cli/src/cluster_query.rs (hunk 1 above)
Comment (kubanemil) [reply cli/src/cluster_query.rs:1871]: got it, but how can I get all stake accounts with their delegate specified? As far as I can see, `rpc_client.get_program_accounts_with_config()` contains only the owner of the stake account.

Comment (kubanemil) [reply cli/src/cluster_query.rs]: Fixed, now uses only one call. Also, made sure to use `fmt `and `clippy`

File: cli/src/cluster_query.rs [hunk 2]
```diff
@@ -1780,8 +1776,39 @@ pub fn process_show_stakes(
...
+                })
+                .map(|vote_acc| vote_acc.vote_pubkey.to_string())
+                .collect();
+
+            if vote_account_pubkeys.len() != pubkeys.len() {
+                return Err(CliError::RpcRequestError(
+                    "Failed to retrieve matching vote account for pubkey(s).".to_string(),
+                )
+                .into());
+            }
```
Comment (CriesofCarrots) [inline cli/src/cluster_query.rs]: It would be nice to print exactly which pubkeys could not be found. Could you collect them during the iteration `filter` step above?

File: cli/src/cluster_query.rs [hunk 3]
```diff
@@ -1780,8 +1776,39 @@ pub fn process_show_stakes(
 ) -> ProcessResult {
     use crate::stake::build_stake_state;
 
-    let progress_bar = new_spinner_progress_bar();
-    progress_bar.set_message("Fetching stake accounts...");
+    let vote_account_progress_bar = new_spinner_progress_bar();
+    vote_account_progress_bar.set_message("Searching for matching vote accounts...");
```
Comment (CriesofCarrots) [inline cli/src/cluster_query.rs]: Let's move this inside the `Some` case, as it will be confusing when a user hasn't provided any keys.

File: cli/src/cluster_query.rs [hunk 4]
```diff
@@ -1876,9 +1902,13 @@ pub fn process_show_stakes(
             }
         }
     }
-    Ok(config
-        .output_format
-        .formatted_string(&CliStakeVec::new(stake_accounts)))
+    if stake_accounts.is_empty() {
+        Ok("No stake account found for provided vote account(s).".into())
```
Comment (CriesofCarrots) [inline cli/src/cluster_query.rs]: What if the user hasn't provided any vote accounts? (eg being filtered on a withdraw_authority that cannot be found)

**Review by CriesofCarrots — COMMENTED** [review]
Thanks, this approach looks much better! A few comments below; plus it looks like this needs a rebase on master (please rebase and force-push instead of pushing merge commits).

File: cli/src/cluster_query.rs (hunk 2 above)
Comment (kubanemil) [reply cli/src/cluster_query.rs]: Now error outputs invalid pubkeys

File: cli/src/cluster_query.rs (hunk 4 above)
Comment (kubanemil) [reply cli/src/cluster_query.rs]: Alright, changed the message

File: cli/src/cluster_query.rs (hunk 3 above)
Comment (kubanemil) [reply cli/src/cluster_query.rs]: Done

File: cli/src/cluster_query.rs [hunk 5]
```diff
@@ -1747,8 +1744,58 @@ pub fn process_show_stakes(
...
+                ))
+                .into());
+            }
+            vote_account_progress_bar.finish_and_clear();
+
+            let filtered_vote_pubkeys = filtered_vote_accounts
+                .iter()
+                .map(|vote_acc| vote_acc.vote_pubkey.to_string())
+                .collect();
+            filtered_vote_pubkeys
```
Comment (CriesofCarrots) [inline cli/src/cluster_query.rs]:
```suggestion
            let mut pubkeys: HashSet<String> =
                pubkeys.iter().map(|pubkey| pubkey.to_string()).collect();

            let vote_account_pubkeys: HashSet<String> = vote_accounts
                .current
                .into_iter()
                .chain(vote_accounts.delinquent)
                .filter_map(|vote_acc| {
                    (pubkeys.remove(&vote_acc.node_pubkey) || pubkeys.remove(&vote_acc.vote_pubkey))
                        .then(|| vote_acc.vote_pubkey)
                })
                .collect();

            if !pubkeys.is_empty() {
                return Err(CliError::RpcRequestError(format!(
                    "Failed to retrieve matching vote account for {:?}.",
                    pubkeys
                ))
                .into());
            }
            vote_account_progress_bar.finish_and_clear();
            vote_account_pubkeys
```
Would be nicer to iterate only once. Also, given all the Pubkey-String conversions, I prefer `clone()` to `to_string()` when needed to reallocate a String to make it more obvious what's occurring. The rest of this suggestion is to make the expression more concise.

File: cli/src/cluster_query.rs [hunk 6]
```diff
@@ -1843,9 +1889,13 @@ pub fn process_show_stakes(
             }
         }
     }
-    Ok(config
-        .output_format
-        .formatted_string(&CliStakeVec::new(stake_accounts)))
+    if stake_accounts.is_empty() {
+        Ok("No stake account found".into())
```
Comment (CriesofCarrots) [inline cli/src/cluster_query.rs]:
```suggestion
        Ok("No stake accounts found".into())
```

File: cli/src/cluster_query.rs [hunk 7]
```diff
@@ -26,6 +26,7 @@ use {
         },
         *,
     },
+    solana_client::rpc_response::RpcVoteAccountInfo,
```
Comment (CriesofCarrots) [inline cli/src/cluster_query.rs]: This will need removing, with my suggested change below.

**Review by CriesofCarrots — COMMENTED** [review]
Thanks for your patience, I think this is close.

File: cli/src/cluster_query.rs (hunk 5 above)
Comment (kubanemil) [reply cli/src/cluster_query.rs]: Nice suggestion! Very sorry I did not write it that way from the start, thanks.

File: cli/src/cluster_query.rs [hunk 8]
```diff
@@ -1817,8 +1813,40 @@ pub fn process_show_stakes(
...
+            let vote_account_pubkeys: HashSet<String> = vote_accounts
+                .current
+                .iter()
+                .chain(vote_accounts.delinquent.iter())
+                .filter(|vote_acc| {
+                    pubkeys.remove(&vote_acc.node_pubkey) || pubkeys.remove(&vote_acc.vote_pubkey)
+                })
+                .map(|vote_acc| &vote_acc.vote_pubkey)
+                .cloned()
+                .collect();
```
Comment (CriesofCarrots) [inline cli/src/cluster_query.rs]: You changed a few parts of my suggestion here. Why?
`iter().cloned()` is less performant.

Comment (kubanemil) [reply cli/src/cluster_query.rs]: sorry, I only saw your .remove() code, didn't pay attention to the rest of it. Updated it, thanks for your patience

File: cli/src/cluster_query.rs [hunk 9]
```diff
@@ -1817,8 +1813,39 @@ pub fn process_show_stakes(
 ) -> ProcessResult {
     use crate::stake::build_stake_state;
 
-    let progress_bar = new_spinner_progress_bar();
-    progress_bar.set_message("Fetching stake accounts...");
+    // fetching corresponding vote pubkey from identity pubkey
```
Comment (CriesofCarrots) [inline cli/src/cluster_query.rs]:
```suggestion
    // Both vote and identity pubkeys are supported to identify validator stakes.
    // For identity pubkeys, fetch corresponding vote pubkey.
```

**Review by CriesofCarrots — COMMENTED** [review]
Thanks, this logic looks good to me now.
Can you please update the value and help text of the cli arg so that it's clear that identity pubkeys are supported? https://github.com/anza-xyz/agave/blob/aa2f078836434965e1a5a03af7f95c6640fe6e1e/cli/src/cluster_query.rs#L369-L375
Then this should be good to merge!

File: cli/src/cluster_query.rs (hunk 9 above)
Comment (kubanemil) [reply cli/src/cluster_query.rs]: done.

**Review by CriesofCarrots — APPROVED** [review]

**Comment by kubanemil** [comment]
@CriesofCarrots thanks a lot for your patience!
