### PR TITLE
Patches race in secondary index w.r.t. insert and remove

### LINKED ISSUE #10832: Secondary index consistency panic during shrink (V3.1)
#### Problem

On a v3.1-based custom branch on mainnet RPC, we’re seeing a panic in accounts-db/src/accounts_index/secondary.rs:186:
```
  assert!(inner_key_map.value().remove_inner_key(removed_inner_key));
```
  
This indicates reverse_index[inner_key] contains outer_key, but index[outer_key] does not contain inner_key. This can happen under concurrent insert and remove_by_inner_key (e.g., shrink running in background while tx processing updates secondary indexes).

Backtrace includes:
```
  - SecondaryIndex::remove_by_inner_key
  - AccountsIndex::handle_dead_keys
  - AccountsDb::remove_zero_lamport_single_ref_accounts_after_shrink
  - AccountsDb::shrink_storage
```

Likely a race condition

-   SecondaryIndex::insert writes forward map first, then reverse index.
-   SecondaryIndex::remove_by_inner_key removes reverse index first, then forward map.
-   This permits the following interleaving:
 

1. T2 insert(outer_key, inner_key) updates forward map.
2. T1 remove_by_inner_key(inner_key) removes reverse entry + forward entry.
3. T2 resumes and inserts into reverse index.

Result: reverse index points to outer key not present in forward map.

Also  shrink runs in the background Rayon pool and multiple remove_by_inner_key can race on the delete too.

This should only affect when secondary index is enabled.

### PR DESCRIPTION
**Pull request by brooksprumo**
#### Problem

Refer to https://github.com/anza-xyz/agave/issues/10832.

#### Summary of Changes

Modifies `insert`/`remove` to ensure they grab the locks in the same order.

Fixes #10832

Note: Planning to backport all the way to v3.1, since that's the version used in the initial bug report.

### CODE REVIEW

File: accounts-db/src/accounts_index/secondary.rs [hunk 1]
```diff
@@ -129,101 +129,106 @@ impl<SecondaryIndexEntryType: SecondaryIndexEntry + Default + Sync + Send>
...
-                let mut w_outer_keys = outer_keys.write().unwrap();
-                if !w_outer_keys.contains(key) {
-                    w_outer_keys.push(*key);
-                }
-            }
+        if !outer_keys.contains(key) {
+            outer_keys.push(*key);
         }
 
+        // explicityly drop the locks so we don't hold them while reporting metrics
```
Comment (roryharr) [inline accounts-db/src/accounts_index/secondary.rs]: Spelling (explicityly)

File: accounts-db/src/accounts_index/secondary.rs [hunk 2]
```diff
@@ -129,101 +129,106 @@ impl<SecondaryIndexEntryType: SecondaryIndexEntry + Default + Sync + Send>
         }
     }
 
+    /// Inserts `inner_key` into `key`'s map.
```
Comment (roryharr) [inline accounts-db/src/accounts_index/secondary.rs:132]: This also inserts key into inner_keys vec. 

This is needed because we never explicitly remove old_key from inner_key unless we free the pubkey? why? 

I see this is mostly used for ownership, why tracking old owners for a key?

File: accounts-db/src/accounts_index/secondary.rs [hunk 3]
```diff
@@ -129,101 +129,106 @@ impl<SecondaryIndexEntryType: SecondaryIndexEntry + Default + Sync + Send>
...
+            // If the outer_key map was empty, we'll check again and remove it if still empty.
+            // If it is no longer empty, that is fine, it was re-added, and nothing to do here.
+            self.index
+                .remove_if(outer_key, |_, inner_keys| inner_keys.is_empty());
         }
+        was_removed
     }
 
+    /// Removes `inner_key` from the secondary index.
     pub fn remove_by_inner_key(&self, inner_key: &Pubkey) {
```
Comment (roryharr) [inline accounts-db/src/accounts_index/secondary.rs:209]: Maybe i'm missing something, but why not just hold a write lock on the inner key in the reverse index for the entire duration of both insert and remove? 

Seems like the code would be much easier to follow, and less bug prone. 

It may effect perf a bit, but it seems like the expectation is that the inner key list is quite short.

File: accounts-db/src/accounts_index/secondary.rs [hunk 4]
```diff
@@ -249,3 +254,125 @@ impl<SecondaryIndexEntryType: SecondaryIndexEntry + Default + Sync + Send>
...
+
+#[cfg(all(test, feature = "shuttle-test"))]
+mod shuttle_tests {
+    use {
+        super::*,
+        shuttle::thread,
+        std::{iter, sync::Arc},
+    };
+
+    fn do_test_concurrent_insert_remove() {
```
Comment (roryharr) [inline accounts-db/src/accounts_index/secondary.rs]: Did you manage to reproduce the issue with this test?

Comment (brooksprumo) [reply accounts-db/src/accounts_index/secondary.rs]: Lol. So in the patch I posted here, there's a non-shuttle test that *does* reproduce the issue: https://github.com/anza-xyz/agave/issues/10832#issuecomment-3985941728

I had also added a shuttle test. And for this PR, I removed the "normal" unit test. However the shuttle test doesn't reproduce the issue. Maybe not enough iterations, or me not configuring shuttle properly? I noticed run time of the shuttle test got really long really fast as the number of iterations increased. And maybe it also needed to use the shuttle RwLock types too?

Anyway, I've converted back to a normal unit test, which reproduces reliably, in https://github.com/anza-xyz/agave/pull/10908/commits/806f3b246fa8056603c0ea6aae89db89af21cfea.

File: accounts-db/src/accounts_index/secondary.rs (hunk 1 above)
Comment (brooksprumo) [reply accounts-db/src/accounts_index/secondary.rs]: Thanks! Fixed in https://github.com/anza-xyz/agave/pull/10908/commits/aebb02808cd9ab5d9dae511e7c140fc00fde692a.

File: accounts-db/src/accounts_index/secondary.rs (hunk 2 above)
Comment (brooksprumo) [reply accounts-db/src/accounts_index/secondary.rs:132]: > This also inserts key into inner_keys vec.

Yes, we do add inner_key into the reverse-index. I didn't think that was important for the caller to know about though. Wdyt?

> This is needed because we never explicitly remove old_key from inner_key unless we free the pubkey? why?
> I see this is mostly used for ownership, why tracking old owners for a key?

I wouldn't expect this to happen often (ever?). The usage of the secondary index is to track program accounts. Once an account is created for a program, I don't know of a reason why someone would switch it be used for another program. I'm not even sure if that's possible (iow, does the user even have the keypair for the account?). I think it may be possible *if* the user does have the keypair to set the account with one program as the owner, then close the account, then recreate it for another program -- all within a single tx likely so that we don't call a `remove` here. Ultimately I'm not intending to change that behavior here though. Maybe there's a gap here? I'm not too worried about it though, since the `get()` fn is for a specific outer key (e.g. a program), and there's always a possibility an inner key is removed _after_ `get()` returns and _before_ the results are used. So RPC clients need to handle this possibility anyway.

So the reverse-index for each inner key should be just a single entry.

File: accounts-db/src/accounts_index/secondary.rs (hunk 3 above)
Comment (brooksprumo) [reply accounts-db/src/accounts_index/secondary.rs:209]: I'm not sure I follow. This PR does now take a write lock on the inner key in the reverse index for the duration of `insert()` and `remove()`.

Can you help me understand by maybe pointing to specific code lines?

Comment (roryharr) [reply accounts-db/src/accounts_index/secondary.rs:209]: I'm wondering why https://github.com/anza-xyz/agave/pull/10908/changes#diff-d609bcf3370fd463bed96d9229d59cca4a56aebf9638a5fe0c07ce29ca84caf1R224 would be needed if the lock is held the entire time.

I guess holding that the entire time would require holding a write lock on that shard of the dashmap... Might still be ok?

File: accounts-db/src/accounts_index/secondary.rs (hunk 2 above)
Comment (roryharr) [reply accounts-db/src/accounts_index/secondary.rs:132]: Leave it for future improvements if we end up keeping the secondary index. Seems like it would save a bit of memory if that could be simplified.

File: accounts-db/src/accounts_index/secondary.rs (hunk 3 above)
Comment (brooksprumo) [reply accounts-db/src/accounts_index/secondary.rs:209]: Ah, I see. The `self.reverse_index.remove_if()` line write locks the `reverse_index` (well, that shard). Whereas the code earlier in the fn only has a read lock on `reverse_index`.

Here's that earlier code:
```rust
if let Some(reverse_index_entry) = self.reverse_index.get(inner_key) {
            let mut outer_keys = reverse_index_entry.write().unwrap();
```

The `reverse_index.get()` is the read lock on the whole reverse_index.
And the `reverse_index_entry.write()` is the write lock on just the `inner_key`'s vec of reverse mappings.

So yes, we could write lock the whole reverse_index the entire duration of the fn, but I think that could be bad for performance, as it would prevent other inserts/removals to non-conflicting keys.

File: accounts-db/src/accounts_index/secondary.rs (hunk 2 above)
Comment (brooksprumo) [reply accounts-db/src/accounts_index/secondary.rs:132]: I don't expect the reverse-index to have more than a single entry per inner key, so I doubt we'd save much/any memory.

More importantly, I agree let's leave it for later. Ideally we remove secondary indexes entirely.

File: accounts-db/src/accounts_index/secondary.rs (hunk 3 above)
Comment (roryharr) [reply accounts-db/src/accounts_index/secondary.rs:209]: It would just be a shard lock right? (it's a dashmap isn't it?) How many shards? 

Could also increase the number of shards at the same time to reduce the collision chances.

File: accounts-db/src/accounts_index/secondary.rs (hunk 2 above)
Comment (roryharr) [reply accounts-db/src/accounts_index/secondary.rs:132]: yup!

By save memory, i mean a vec wouldn't be needed anymore. it would just be a pubkey. Saving ~24 bytes per entry I think?

File: accounts-db/src/accounts_index/secondary.rs (hunk 3 above)
Comment (brooksprumo) [reply accounts-db/src/accounts_index/secondary.rs:209]: Yes, it's a DashMap so the locks on it are per shard. Default number of shards. Yes, could increase the number of shards, but I don't see why we would want to change a read lock to a write lock though.

Comment (roryharr) [reply accounts-db/src/accounts_index/secondary.rs:209]: It's not really changing a read lock to a write lock is it? It's changing a read lock + a write lock to a write lock. Just a longer write lock. 

Disadvantage - Slower (holding the write lock for longer) 
Advantage - makes some buggy code that isn't well tested less bug prone. 

Expanding the number of shards would reduce the downside of the disadvantage.

Comment (brooksprumo) [reply accounts-db/src/accounts_index/secondary.rs:209]: Ok, I've changed to using a write lock in https://github.com/anza-xyz/agave/pull/10908/commits/63dccff61b458f4ce2fec63bc9b85756ca69f491.

**Review by roryharr — APPROVED** [review]
