### PR TITLE
Fix UDP client binding to localhost breaking vote propagation

### LINKED ISSUE #8339: Vote latency degradation on v3.0.x compared to v2.3.x
#### Problem

Vote latency drops significantly when upgrading to 3.0.x from 2.3.x. It is currently unclear what is causing this issue.

### PR DESCRIPTION
**Pull request by onnie81**
Fixes #8339

Commit e1d78e1d04 changed UDP client socket binding from UNSPECIFIED (0.0.0.0) to LOCALHOST (127.0.0.1) to fix test port conflicts in #7490. This broke production validators by preventing vote packets from being sent on actual network interfaces.

**Impact:** Vote latency regressed from ~1 slot to ~2 slots between v2.3.11 and v3.0.4.

**Root cause:** Bisected the entire codebase from v2.3.11 to v3.0.4 and identified commit e1d78e1d04 as the regression point.

**Fix:** Use conditional compilation to bind to LOCALHOST only in tests while restoring UNSPECIFIED binding for production builds.

**Testing:** Tested fix on mainnet validator - vote latency restored to mostly 1s.

### CODE REVIEW

File: udp-client/src/lib.rs [hunk 1]
```diff
@@ -63,10 +63,17 @@ pub struct UdpConfig {
 
 impl NewConnectionConfig for UdpConfig {
     fn new() -> Result<Self, ClientError> {
+        // Use UNSPECIFIED for production validators to bind to all interfaces
+        // Use LOCALHOST only in tests to avoid port conflicts in CI
+        #[cfg(not(test))]
+        let bind_ip = std::net::IpAddr::V4(std::net::Ipv4Addr::UNSPECIFIED);
+        #[cfg(test)]
+        let bind_ip = std::net::IpAddr::V4(std::net::Ipv4Addr::LOCALHOST);
```
Comment (t-nelson) [inline udp-client/src/lib.rs]: i was going to nix this construction as brittle, but this abstraction is so hilariously broken that i think this is actually the least wrong path to backportable fix

Comment (onnie81) [reply udp-client/src/lib.rs]: I wrote this sleep deprived and with a toddler climbing on my face. I couldn't think of any other way to fix this without taking a massive tech debt dump

Comment (t-nelson) [reply udp-client/src/lib.rs]: your assessment was correct, nevertheless

Comment (lijunwangs) [reply udp-client/src/lib.rs]: Good catch. We missed it in https://github.com/anza-xyz/agave/pull/7490. But I think the fix would not work for tests running not in this crate. As the #[cfg(test)] is not persistent across crates. The right way I think to fix this is through #[cfg(feature = "dev-context-only-utils")].

**Review by lijunwangs — CHANGES_REQUESTED** [review]

File: udp-client/src/lib.rs (hunk 1 above)
Comment (lijunwangs) [reply udp-client/src/lib.rs]: We may simply revert the change of #7490 on this file. i.e. turning back to std::net::IpAddr::V4(std::net::Ipv4Addr::UNSPECIFIED)
so that we can quickly back port 
While addressing the flaky test problem.

Comment (onnie81) [reply udp-client/src/lib.rs]: Proposing a revert was a bridge too far for me, I focused on trying to keep the logic while solving the perf regression.


if we just revert that file wouldn’t we bringing back potential port conflicts during testing?

should I go ahead and use  #[cfg(feature = "dev-context-only-utils")] ?

Comment (lijunwangs) [reply udp-client/src/lib.rs]: I am not proposing reverting the whole PR. Only the change in this file only.  Having "#[cfg(test)]" is useless and confusing. So instead of having that non-working/misleading config code littered, cleaner to just revert that change. We can fix the test using dev-context-only-utils way in a subsequent PR to unblock this more critical fix.

Comment (lijunwangs) [reply udp-client/src/lib.rs]: You may refer to https://github.com/anza-xyz/agave/pull/7815 as a recent example on how to use #[cfg(feature = "dev-context-only-utils")]. We need to code it like you are doing with #[cfg(test)] in the code and then ensure using the feature in the dev-dependencies where we use udp-client when creating the UDP based connection cache abstraction. Adding some debug logs to ensure the test path is really exercised when running the unit test.

Comment (t-nelson) [reply udp-client/src/lib.rs]: could use `cfg(feature = "dev-context-only-utils")` instead of `cfg(test)`

generally if you want to "revert" something, it should be at commit-level resolution, not some confusing partial thing

Comment (onnie81) [reply udp-client/src/lib.rs]: ok, uploaded new version with dev-context-only-utils

File: udp-client/src/lib.rs [hunk 2]
```diff
@@ -63,10 +63,17 @@ pub struct UdpConfig {
 
 impl NewConnectionConfig for UdpConfig {
     fn new() -> Result<Self, ClientError> {
+        // Use UNSPECIFIED for production validators to bind to all interfaces
+        // Use LOCALHOST only in dev/test context to avoid port conflicts in CI
+        #[cfg(not(feature = "dev-context-only-utils"))]
+        let bind_ip = std::net::IpAddr::V4(std::net::Ipv4Addr::UNSPECIFIED);
+        #[cfg(feature = "dev-context-only-utils")]
```
Comment (lijunwangs) [inline udp-client/src/lib.rs:70]: This is necessary but not sufficient to fix the flaky port collision issue with unit tests as it must be enabled by the test to use the feature in its dev-dependencies.  But I think we can get this in first as and address the test part in a separate PR as there are quite a few crates need that change.

Comment (alexpyattaev) [reply udp-client/src/lib.rs:70]: CI should work mostly fine even if it binds to all interfaces here. Patching in the DCOU hooks can be done in a separate PR.

**Review by alexpyattaev — APPROVED** [review]
Thank you very much for your contribution!

**Review by alexpyattaev — APPROVED** [review]
Thank you for your contribution and for spotting this one!

**Review by lijunwangs — APPROVED** [review]

File: udp-client/src/lib.rs [hunk 3]
```diff
@@ -63,10 +63,17 @@ pub struct UdpConfig {
...
+        let bind_ip = std::net::IpAddr::V4(std::net::Ipv4Addr::LOCALHOST);
```
Comment (brooksprumo) [inline udp-client/src/lib.rs:71]: As an FYI for anyone that hits this later, if you build with `cargo build --release`, then agave-validator will have DCOU *enabled*, and the bind_ip will incorrectly be `Ipv4Addr::LOCALHOST`.

Comment (steviez) [reply udp-client/src/lib.rs:71]: Agreed, using `#[cfg(feature = "dev-context-only-utils")]` isn't a bulletproof solution. This function itself is not DCOU so it is possible for a test function to be using this function while DCOU is disabled.

I know we made this change with backportability in mind, but we should revisit alternates to remove footguns for master

Comment (t-nelson) [reply udp-client/src/lib.rs:71]: > As an FYI for anyone that hits this later, if you build with `cargo build --release`, then agave-validator will have DCOU _enabled_, and the bind_ip will incorrectly be `Ipv4Addr::LOCALHOST`.

lmao that is its own bug that we need to fix

Comment (steviez) [reply udp-client/src/lib.rs:71]: >  if you build with cargo build --release, then agave-validator will have DCOU enabled, and the bind_ip will incorrectly be Ipv4Addr::LOCALHOST.
>
> lmao that is its own bug that we need to fix

Searching the repo, the reason for that seems to be explained here: https://github.com/anza-xyz/agave/issues/6354#issuecomment-2957405438.

This is pretty foot-gunny, Ryo's latest comment implies that we don't have much recourse except for waiting for a cargo feature which isn't ideal either

Comment (onnie81) [reply udp-client/src/lib.rs:71]: uh-oh... did I mess it up? Originally i just used the "test" condition.

@brooksprumo will the usual method of $ scripts/cargo_install_all.sh --validator-only also enable DCOU? Because #6354 is ambiguous about it, and if it is then then fix is moot

Comment (t-nelson) [reply udp-client/src/lib.rs:71]: no i think you did the best we can do. we're just choosing best from a lot of bad options

Comment (t-nelson) [reply udp-client/src/lib.rs:71]: > > if you build with cargo build --release, then agave-validator will have DCOU enabled, and the bind_ip will incorrectly be Ipv4Addr::LOCALHOST.
> > lmao that is its own bug that we need to fix
> 
> Searching the repo, the reason for that seems to be explained here: [#6354 (comment)](https://github.com/anza-xyz/agave/issues/6354#issuecomment-2957405438).
> 
> This is pretty foot-gunny, Ryo's latest comment implies that we don't have much recourse except for waiting for a cargo feature which isn't ideal either

i can take a look. just got a little more familiar with debugging/tracking crate feature enablement. we should move the discussion off this thread tho

Comment (alexpyattaev) [reply udp-client/src/lib.rs:71]: When I was testing this PR I built with cargo build --release --bin agave-validator , and the binding was chosen correctly . If DCOU can be enabled in release builds somehow, we have a lot of other problems as well, not just this one...

Comment (brooksprumo) [reply udp-client/src/lib.rs:71]: > I built with cargo build --release --bin agave-validator

Yeah, with just the validator bin you're fine. It's when you build multiple/all bins and the dcou feature gets enabled for everything.

Comment (t-nelson) [reply udp-client/src/lib.rs:71]: > > I built with cargo build --release --bin agave-validator
> 
> Yeah, with just the validator bin you're fine. It's when you build multiple/all bins and the dcou feature gets enabled for everything.

correct. if any of the packages specified [here](https://github.com/anza-xyz/agave/pull/8403/files#diff-36f9209af96f164ef3532a28b913ed64e51e28bb5c12b7f16a4d5795eba8f08cR2-R8) are selected, you will get dcou on everything

Comment (alexpyattaev) [reply udp-client/src/lib.rs:71]: Well we need to accelerate the removal of connection cache then to get rid of these hacks.
