### PR TITLE
Check poh_recorder.start_slot() hasn't been dumped previously before checking it in ProgressMap.

### LINKED ISSUE #2671: Fix panic in ProgressMap when the underlying block may have been dumped and repaired
#### Problem
During today's testnet accident, we saw validators panicking in ProgressMap when underlying blocks have been purged:

[2024-08-20T07:07:42.166017158Z WARN  solana_core::replay_stage] purging slot 288668257
[2024-08-20T07:07:43.020116943Z WARN  solana_core::replay_stage] purging duplicate descendant: 288668259
thread 'solReplayStage' panicked at core/src/consensus/progress_map.rs:294:32:
slot=288668259 must exist in ProgressMap
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: solana_core::consensus::progress_map::ProgressMap::get_propagated_stats_must_exist
   3: solana_core::consensus::progress_map::ProgressMap::get_leader_propagation_slot_must_exist
   4: solana_core::replay_stage::ReplayStage::retransmit_latest_unpropagated_leader_slot

#### Proposed Solution
Audit all _must_exist function and fix.

### PR DESCRIPTION
**Pull request by wen-coding**
#### Problem
It's possible that poh_recorder.start_slot() has been dumped because of duplicate proof, in that case we would currently panic inside ProgressMap::get_propagated_stats_must_exist()

#### Summary of Changes
Check that start_slot still exists in ProgressMap before proceeding.

### CODE REVIEW

**Comment by AshwinSekar** [comment]
Should check the rest of them as well:
```
1966:            progress_map.get_latest_leader_slot_must_exist(parent_slot)
1980:            .get_leader_propagation_slot_must_exist(parent_slot)
2086:                let latest_unconfirmed_leader_slot = progress_map.get_latest_leader_slot_must_exist(parent_slot)
3591:        if progress.get_leader_propagation_slot_must_exist(slot).0 {
3907:                    .get_leader_propagation_slot_must_exist(candidate_vote_bank.slot())
3982:        let mut current_leader_slot = progress.get_latest_leader_slot_must_exist(fork_tip);
4409:                        progress.get_latest_leader_slot_must_exist(*slot)
```

It looks like some of them might be safe, but good to double check.

Additionally it looks like we can get screwed here:
https://github.com/anza-xyz/agave/blob/951bb04d8639c7a92be79e10c5eea6210d73ce81/core/src/replay_stage.rs#L2037-L2041
`parent_slot` is also the `poh_recorder.start_slot()` so it could have been dumped.

**Comment by wen-coding** [comment]
> Should check the rest of them as well:
> 
> ```
> 1966:            progress_map.get_latest_leader_slot_must_exist(parent_slot)
> 1980:            .get_leader_propagation_slot_must_exist(parent_slot)
> 2086:                let latest_unconfirmed_leader_slot = progress_map.get_latest_leader_slot_must_exist(parent_slot)
> 3591:        if progress.get_leader_propagation_slot_must_exist(slot).0 {
> 3907:                    .get_leader_propagation_slot_must_exist(candidate_vote_bank.slot())
> 3982:        let mut current_leader_slot = progress.get_latest_leader_slot_must_exist(fork_tip);
> 4409:                        progress.get_latest_leader_slot_must_exist(*slot)
> ```
> 
> It looks like some of them might be safe, but good to double check.
> 
> Additionally it looks like we can get screwed here:
> 
> https://github.com/anza-xyz/agave/blob/951bb04d8639c7a92be79e10c5eea6210d73ce81/core/src/replay_stage.rs#L2037-L2041
> 
> 
> `parent_slot` is also the `poh_recorder.start_slot()` so it could have been dumped.

I wanted to put each check in a different PR, is it better to put all of them in the same PR?

**Comment by AshwinSekar** [comment]
> I wanted to put each check in a different PR, is it better to put all of them in the same PR?

one PR is probably fine, i imagine it'll be a hassle managing and backporting multiple with possible merge conflicts

**Comment by wen-coding** [comment]
> > I wanted to put each check in a different PR, is it better to put all of them in the same PR?
> 
> one PR is probably fine, i imagine it'll be a hassle managing and backporting multiple with possible merge conflicts

That's fair, let me take a look at the other instances.

**Comment by wen-coding** [comment]
> > > I wanted to put each check in a different PR, is it better to put all of them in the same PR?
> > 
> > 
> > one PR is probably fine, i imagine it'll be a hassle managing and backporting multiple with possible merge conflicts
> 
> That's fair, let me take a look at the other instances.

I checked all _must_exist in replay, and I think these are the only two places we would be in trouble, added comments in other places.

File: core/src/replay_stage.rs [hunk 1]
```diff
@@ -1306,6 +1307,13 @@ impl ReplayStage {
     ) {
         let start_slot = poh_recorder.read().unwrap().start_slot();
 
+        // It is possible that bank corresponding to `start_slot` has been
+        // dumped, so we need to double check it exists before proceeding
+        if !progress.contains(&start_slot) {
+            debug!("Slot may have been dumped: start_slot={}", start_slot);
```
Comment (AshwinSekar) [inline core/src/replay_stage.rs]: Prefer warn here, can also use string formatting:
```suggestion
            warn!("Poh start slot {start_slot}, is missing from progress map. This indicates that we are in the middle of a dump and repair. Skipping retransmission of unpropagated leader slots");
```

File: core/src/replay_stage.rs [hunk 2]
```diff
@@ -2034,11 +2045,17 @@ impl ReplayStage {
 
         trace!("{} reached_leader_slot", my_pubkey);
 
-        let parent = bank_forks
-            .read()
-            .unwrap()
-            .get(parent_slot)
-            .expect("parent_slot doesn't exist in bank forks");
+        let parent = bank_forks.read().unwrap().get(parent_slot);
```
Comment (AshwinSekar) [inline core/src/replay_stage.rs]: We can let else:
```rust
let Some(parent) = bank_forks.read().unwrap().get(parent_slot) else {
    warn!("Poh recorder parent slot {parent_slot} is missing from bank_forks. This indicates that we are in the middle of a dump and repair. Unable to start leader");
    return false;
}
```

File: core/src/replay_stage.rs [hunk 3]
```diff
@@ -2083,6 +2100,7 @@ impl ReplayStage {
             );
 
             if !Self::check_propagation_for_start_leader(poh_slot, parent_slot, progress_map) {
+                // We checked that parent_slot hasn't been dumped, so we should get it in the progress map.
```
Comment (AshwinSekar) [inline core/src/replay_stage.rs]: I think it's fine to not add this comment since the `expect` below explains the situation.

Comment (wen-coding) [reply core/src/replay_stage.rs]: Done.

File: core/src/replay_stage.rs (hunk 2 above)
Comment (wen-coding) [reply core/src/replay_stage.rs]: Done.

Comment (AshwinSekar) [reply core/src/replay_stage.rs]: can you  update the warn! message to match what I wrote above?

**Comment by AshwinSekar** [comment]
overall looks good, added some more reviewers to get a second opinion

**Review by bw-solana — APPROVED** [review]
LGTM

File: core/src/replay_stage.rs (hunk 2 above)
Comment (wen-coding) [reply core/src/replay_stage.rs]: Done.

File: core/src/replay_stage.rs [hunk 4]
```diff
@@ -1306,6 +1307,13 @@ impl ReplayStage {
     ) {
         let start_slot = poh_recorder.read().unwrap().start_slot();
 
+        // It is possible that bank corresponding to `start_slot` has been
+        // dumped, so we need to double check it exists before proceeding
+        if !progress.contains(&start_slot) {
+            warn!("Poh start slot {start_slot}, is missing from progress map. This indicates that we are in the middle of a dump and repair. Skipping retransmission of unpropagated leader slots");
+            return;
+        }
+
```
Comment (carllin) [inline core/src/replay_stage.rs:1316]: hmm if we're about to dump the slot, shouldn't we be resetting PoH to an ancestor of that slot? @AshwinSekar 

Seems like `select_vote_and_reset_forks` should be handling the reset to account for latest duplicate we reset to before we get here

Comment (wen-coding) [reply core/src/replay_stage.rs:1316]:
```
[2024-08-20T07:07:42.150220136Z WARN  solana_core::repair::cluster_slot_state_verifier] Cluster duplicate confirmed slot 288668257 with hash 2kQ6z6XvYiFc3hnw5PqhwREa9yDChBDqneVrjYvcabeu, but our version has hash AytETM4WSS9AheCCDLdiBwXVWkkmQY59EEZzdUKzDuBo
[2024-08-20T07:07:42.150226519Z INFO  solana_core::consensus::heaviest_subtree_fork_choice] marking fork starting at: (288668257, AytETM4WSS9AheCCDLdiBwXVWkkmQY59EEZzdUKzDuBo) invalid candidate
[2024-08-20T07:07:42.150244693Z INFO  solana_core::consensus::heaviest_subtree_fork_choice] Fork choice for (288668259, D4281472KYmdbJg8YFUHuJc59oGMTzJhNFeEUUtaAKuH) setting latest invalid ancestor from None to 288668257
[2024-08-20T07:07:42.150252709Z INFO  solana_core::consensus::heaviest_subtree_fork_choice] Fork choice for (288668258, Eq2j5UoAQFsJftEp7X5gtvF7MiykGznFySLT3mku3zwy) setting latest invalid ancestor from None to 288668257
[2024-08-20T07:07:42.150259652Z INFO  solana_core::consensus::heaviest_subtree_fork_choice] Fork choice for (288668257, AytETM4WSS9AheCCDLdiBwXVWkkmQY59EEZzdUKzDuBo) setting latest invalid ancestor from None to 288668257
[2024-08-20T07:07:42.162790246Z INFO  solana_core::replay_stage] 4mJV1MwoVG1Qztpwagnw396QGALvWQxbGXw5cChWKaJJ slot_weight: 288668260 0.0% 288668254
[2024-08-20T07:07:42.162816507Z INFO  solana_core::replay_stage] validator fork confirmed 288668225 21957ms
[2024-08-20T07:07:42.162821536Z INFO  solana_core::replay_stage] validator fork confirmed 288668219 25771ms
[2024-08-20T07:07:42.162825554Z INFO  solana_core::replay_stage] validator fork confirmed 288668238 13693ms
[2024-08-20T07:07:42.165829839Z INFO  solana_core::replay_stage] Waiting to switch vote to 288668260,
                    resetting to slot Some(288668259) for now,
                    switch proof stake: 0,
                    threshold stake: 106674872336469650,
                    total stake: 280723348253867482
```
It looks like in this case we shouldn't reset to 288668259 which links to an invalid ancestor?

Comment (AshwinSekar) [reply core/src/replay_stage.rs:1316]: `dump_then_repair` happens in between the reset and `maybe_start_leader`.
It does have a check to ensure that it doesn't dump a slot that is an ancestor of a `working_bank` we currently have, however that doesn't help if `maybe_start_leader` is just about to tick to our leader slot. 

> Seems like select_vote_and_reset_forks should be handling the reset to account for latest duplicate we reset to before we get here

We do reset to the duplicate fork deepest descended from our last vote in case of switching such as the example wen posted above. To achieve what you're hinting at we should modify `dump_then_repair` to reset to the heaviest block descended from the last vote that is not dumped (or in case of lockout, from the switch slot) OR have select forks talk to the state machine in order to exclude blocks that could be potentially dumped.

I have little confidence in making a fork choice modification that we can backport to 2.0 at this time. I would prefer to hold off on starting leader until dump and repair has succeeded or we have reset to another bank. In the meantime we can make make the fork choice change on master.

Comment (carllin) [reply core/src/replay_stage.rs:1316]: hmm so the current order of events is:

1. Ingest new duplicate and update state machine and thus fork choice in `process_duplicate_slots()`
2. `select_vote_and_reset_forks` runs and picks the reset bank, which currently does not account for the new duplicates from 1?
3. Reset PoH happens to a block that will get dumped 
4. dump and repair dumps block from progress map
5. Panic happens in `retransmit_latest_unpropagated_leader_slot`

So the issue  even though we've updated fork choice in 1, the reset bank is still picking an invalid fork to reset to in 2 right?

Comment (carllin) [reply core/src/replay_stage.rs:1316]: I thought select vote and reset in 2. already accounted for slots marked duplicate by 1 that should be marked as invalid in fork choice

Comment (wen-coding) [reply core/src/replay_stage.rs:1316]: As far I see, yes. We currently use `heaviest_bank_on_same_voted_fork ` for reset bank if switch threshold fails, and we don't seem to set heaviest_bank_on_same_voted_fork to a valid block, instead we change to deepest slot:
[https://github.com/anza-xyz/agave/blob/master/core/src/consensus/heaviest_subtree_fork_choice.rs#L1138](https://github.com/anza-xyz/agave/blob/master/core/src/consensus/heaviest_subtree_fork_choice.rs#L1138)

Did I read that correctly?
