### PR TITLE
fix: re-enable test_scheduler_drop_idle by resolving race condition

### LINKED ISSUE #8279: Re-enable test_scheduler_drop_idle
#### Problem
`test_scheduler_drop_idle` disabled as part of #8278 . Leaves a gap in test coverage

#### Proposed Solution
Race condition should be understood, fixed, and test re-enabled

### PR DESCRIPTION
**Pull request by AvhiMaz**
## Problem
  The test `test_scheduler_drop_idle` was disabled in PR #8278 due to a race condition that caused intermittent CI failures. This left a gap in test coverage for the scheduler pool's idle scheduler cleanup logic.

  ## Summary of Changes
  - Removed `#[ignore]` attribute to re-enable the test
  - Fixed the race condition by using an explicit 300ms idle threshold (instead of 100ms)
  - Increased sleep duration to 350ms to provide a safe timing margin
  - Improved comments explaining the timing guarantees
  
  This eliminates the race condition by providing a 50ms+ safety margin between the idle threshold and actual scheduler ages.

  Fixes #8279

### CODE REVIEW

**Review by steviez — COMMENTED** [review]
I didn't really dig into the test fully previously, but I'm a little dubious that tweaking sleep durations will not leave this open to still being flaky. Gonna tag @bw-solana in for this one tho

**Comment by AvhiMaz** [comment]
> I didn't really dig into the test fully previously, but I'm a little dubious that tweaking sleep durations will not leave this open to still being flaky. Gonna tag @bw-solana in for this one tho

what i thought is that the sleep here isn’t really for syncing with the cleaner. that part still happens deterministically through `sleepless_testing` checkpoints (`BeforeIdleSchedulerCleaned` / `AfterIdleSchedulerCleaned`). The 350 ms wait just creates a clear age gap between the old and new schedulers (300 ms idle threshold vs 350 ms sleep), so the cleaner reliably treats only the old one as idle. should hold up fine under CI, but happy to make adjustments if there’s a cleaner approach.

File: unified-scheduler-pool/src/lib.rs [hunk 1]
```diff
@@ -2872,7 +2872,6 @@ mod tests {
     const SHORTENED_MAX_POOLING_DURATION: Duration = Duration::from_millis(100);
```
Comment (bw-solana) [inline unified-scheduler-pool/src/lib.rs]: let's move this down closer to the only test where it is used now

File: unified-scheduler-pool/src/lib.rs [hunk 2]
```diff
@@ -2884,14 +2883,17 @@ mod tests {
         ]);
 
         let ignored_prioritization_fee_cache = Arc::new(PrioritizationFeeCache::new(0u64));
+        // Use a longer pooling duration for this test to avoid race conditions.
+        // old_scheduler and new_scheduler need to have a clear age difference.
+        let test_max_pooling_duration = Duration::from_millis(300);
```
Comment (bw-solana) [inline unified-scheduler-pool/src/lib.rs]: it would be better to follow the convention of the testing in this file and declare a const explaining the selected value

File: unified-scheduler-pool/src/lib.rs [hunk 3]
```diff
@@ -2905,8 +2907,10 @@ mod tests {
         let new_scheduler_id = new_scheduler.id();
         Box::new(old_scheduler.into_inner().1).return_to_pool();
 
-        // sleepless_testing can't be used; wait a bit here to see real progress of wall time...
-        sleep(SHORTENED_MAX_POOLING_DURATION * 10);
+        // Wait for old_scheduler to be considered idle by the cleaner (> 300ms old).
+        // This ensures when the cleaner runs, old_scheduler will definitely be idle.
+        sleep(Duration::from_millis(350));
```
Comment (bw-solana) [inline unified-scheduler-pool/src/lib.rs]: It would be better to explicitly tie this selection to the `test_max_pooling_duration` value

Comment (bw-solana) [reply unified-scheduler-pool/src/lib.rs]: I know 50ms seems like an eternity, but we've seen these types of thresholds still be flaky in CI testing, especially for non-serial testing..

File: unified-scheduler-pool/src/lib.rs [hunk 4]
```diff
@@ -2884,14 +2883,17 @@ mod tests {
         ]);
 
         let ignored_prioritization_fee_cache = Arc::new(PrioritizationFeeCache::new(0u64));
+        // Use a longer pooling duration for this test to avoid race conditions.
+        // old_scheduler and new_scheduler need to have a clear age difference.
```
Comment (bw-solana) [inline unified-scheduler-pool/src/lib.rs]: I think we could make it more clear why 300ms was selected here.

Essentially we are balancing these two concerns:

1. Make it as small as possible to reduce testing time
2. Create as large of a window as possible to avoid race conditions due to the second scheduler accidentally getting freed before we check the assert condition (i.e. we somehow took long enough between unblocking and checking the inner schedulers length that we freed both schedulers)

File: unified-scheduler-pool/src/lib.rs [hunk 5]
```diff
@@ -2916,12 +2920,9 @@ mod tests {
...
         sleepless_testing::at(&TestCheckPoint::AfterIdleSchedulerCleaned);
 
-        // The following assertion is racy.
-        //
-        // We need to make sure new_scheduler isn't treated as idle up to now since being returned
-        // to the pool after sleep(SHORTENED_MAX_POOLING_DURATION * 10).
-        // Removing only old_scheduler is the expected behavior. So, make
-        // SHORTENED_MAX_POOLING_DURATION rather long...
+        // After the cleaner finishes, only the new_scheduler should remain.
+        // The old_scheduler is idle (pooled > 100ms ago) so it gets removed.
```
Comment (bw-solana) [inline unified-scheduler-pool/src/lib.rs]: only guaranteed to have been pooled >50ms ago, right?

**Comment by bw-solana** [comment]
> what i thought is that the sleep here isn’t really for syncing with the cleaner. that part still happens deterministically through `sleepless_testing` checkpoints (`BeforeIdleSchedulerCleaned` / `AfterIdleSchedulerCleaned`). The 350 ms wait just creates a clear age gap between the old and new schedulers (300 ms idle threshold vs 350 ms sleep), so the cleaner reliably treats only the old one as idle. should hold up fine under CI, but happy to make adjustments if there’s a cleaner approach.

To be clear, the key is how much time can pass between the following LOC relative to the pooling duration: https://github.com/anza-xyz/agave/blob/master/unified-scheduler-pool/src/lib.rs#L2910-L2925

The previous code only allows for up to 100ms while the new code allows for up to 300ms

File: unified-scheduler-pool/src/lib.rs (hunk 5 above)
Comment (AvhiMaz) [reply unified-scheduler-pool/src/lib.rs]: yaa, updated the comment to be explicit about the timing:
- old_scheduler is ~500ms old (exceeds 300ms idle threshold), 
- new_scheduler is ~50ms old (below threshold).

File: unified-scheduler-pool/src/lib.rs [hunk 6]
```diff
@@ -2883,6 +2881,14 @@ mod tests {
...
         ]);
 
+        // Use 300ms pooling duration as a balance between:
+        // - Keeping the test fast (as small as possible)
+        // - Providing a large enough window to avoid the race condition where the second
+        //   scheduler could also be freed before we can assert only one remains
+        const TEST_MAX_POOLING_DURATION: Duration = Duration::from_millis(300);
+        // Add a generous safety margin to avoid flakiness in CI. We need old_scheduler to be
+        // reliably older than TEST_MAX_POOLING_DURATION when the cleaner runs.
+        const TEST_WAIT_FOR_IDLE: Duration = Duration::from_millis(500);
```
Comment (bw-solana) [inline unified-scheduler-pool/src/lib.rs]: might be nice to tie these together explicitly. Something like:
```rust
const TEST_MAX_POOLING_DURATION_MS: u64 = 300;
const TEST_MAX_POOLING_DURATION: Duration = Duration::from_millis(TEST_MAX_POOLING_DURATION_MS);
const TEST_WAIT_FOR_IDLE_MS: u64 = TEST_MAX_POOLING_DURATION_MS + 200;
const TEST_WAIT_FOR_IDLE: Duration = Duration::from_millis(TEST_WAIT_FOR_IDLE_MS);
```

File: unified-scheduler-pool/src/lib.rs [hunk 7]
```diff
@@ -2916,12 +2923,8 @@ mod tests {
...
         sleepless_testing::at(&TestCheckPoint::AfterIdleSchedulerCleaned);
 
-        // The following assertion is racy.
-        //
-        // We need to make sure new_scheduler isn't treated as idle up to now since being returned
-        // to the pool after sleep(SHORTENED_MAX_POOLING_DURATION * 10).
-        // Removing only old_scheduler is the expected behavior. So, make
-        // SHORTENED_MAX_POOLING_DURATION rather long...
+        // Only new_scheduler should remain. old_scheduler (~500ms old) exceeds the
+        // 300ms idle threshold, while new_scheduler (~50ms old) does not.
```
Comment (bw-solana) [inline unified-scheduler-pool/src/lib.rs]: I like the idea of the comments, but putting the actual values here seems like a potential code maintenance problem keeping in sync with the actual constant values. Maybe reference the constants?

Also, I don't think we actually know how old the new scheduler is here, right? Why would it be 50ms old?

Comment (AvhiMaz) [reply unified-scheduler-pool/src/lib.rs]: the ~50ms was just a rough guess. I've updated the comments to reference the constants instead of hardcoding the values. so this should removes those timing assumptions and keeps it maintainable.

**Review by bw-solana — DISMISSED** [review]
LGTM

**Comment by AvhiMaz** [comment]
> LGTM

🫡

**Comment by AvhiMaz** [comment]
@bw-solana there was a formatting issue, fixed it.

**Review by bw-solana — APPROVED** [review]
