### PR TITLE
Cli: fix inflation rewards effective slot, block time

### LINKED ISSUE #3984: Cli: inflation rewards Reward Slot no longer accurate for multiple accounts
#### Problem
Now that the Partitioned Epoch Rewards feature is active, stake accounts receive their rewards across a range of slots, instead of all in the same slot. The RPC `getInflationReward` accepts multiple stake-account addresses and returns the correct effective slot for each account/reward. But the solana-cli assumes the effective slot for the first reward applies to all accounts queried (`CliEpochRewardsMetadata::effective_slot`). When `--output json` is passed, the return includes the correct `effectiveSlot` within each reward struct, but also includes an incorrect `effectiveSlot` at the top level.

#### Proposed Solution
Deprecate `CliEpochRewardsMetadata::effective_slot`
In human-readable mode, display Reward Slot in each reward line

### PR DESCRIPTION
**Pull request by CriesofCarrots**
#### Problem
As of partitioned epoch rewards activation, the effective slots and block times returned from `solana inflation reward` that are incorrect, since the cli assumes that all rewards have been delivered in the same slot.

#### Summary of Changes
- Remove general effective slot and block time from human-readable output
- Deprecate these fields in `CliEpochRewardsMetadata` and populate with 0 for json output
- Add verbose display that includes effective slot and blocktime for every reward
- Query for correct block time for all reward slots

Fixes #3984

### CODE REVIEW

File: cli/src/inflation.rs [hunk 1]
```diff
@@ -118,19 +118,21 @@ fn process_rewards(
...
                 reward: cli_reward,
             });
         }
-        let block_time = rpc_client.get_block_time(first_reward.effective_slot)?;
         Some(CliEpochRewardsMetadata {
             epoch: first_reward.epoch,
-            effective_slot: first_reward.effective_slot,
-            block_time,
+            effective_slot: 0, // Deprecated
+            block_time: 0,     // Deprecated
```
Comment (CriesofCarrots) [inline cli/src/inflation.rs]: Open to suggestions for other/better ways to do this.

File: cli-output/src/cli_output.rs [hunk 2]
```diff
@@ -1025,7 +1025,9 @@ pub struct CliKeyedEpochReward {
 #[serde(rename_all = "camelCase")]
 pub struct CliEpochRewardsMetadata {
     pub epoch: Epoch,
+    // Deprecated
     pub effective_slot: Slot,
+    // Deprecated
     pub block_time: UnixTimestamp,
```
Comment (joncinque) [inline cli-output/src/cli_output.rs]: Are these not formally marked as `#[deprecated(...)]` because of the backwards compatibility policy on CLI output?

File: cli/src/inflation.rs (hunk 1 above)
Comment (joncinque) [reply cli/src/inflation.rs]: It might be clearer to mark the fields as deprecated, but then add a `Default` implementation which sets them to 0, so you can do:

```
Some(CliEpochRewardsMetadata {
    epoch: first_reward.epoch,
    ..Default::default()
})
```

**Review by joncinque — COMMENTED** [review]
Looks great! Just the bit about the deprecated fields

File: cli-output/src/cli_output.rs (hunk 2 above)
Comment (CriesofCarrots) [reply cli-output/src/cli_output.rs]: Amazingly, deprecated fields have never come up in `solana-cli-output` before. (Or at least, never been marked.) But yes, thanks, that does seem like a better approach, in case something other than `solana-cli` is using the struct.

**Review by joncinque — APPROVED** [review]
Looks great!
