### PR TITLE
rpc: Return accurate last valid block height

### LINKED ISSUE #24526: RPC API calculates the last valid block height incorrectly
#### Problem
`Bank::get_blockhash_last_valid_block_height` uses the max age of the blockhash queue to return whether a transaction blockhash is valid but that max age is **double** the max age for transaction processing. RPC API's related to transaction / blockhash expiration use this bank method and give clients an incorrect response. 

#### Proposed Solution
Double the max age of transaction processing (draft PR: https://github.com/solana-labs/solana/pull/24425)

Doubling the max age of transaction processing should increase the chances that user transactions are confirmed even during cluster instability. Validators are already tracking the necessary state for double the current processing age so the implementation requires minimal changes.

tag @t-nelson @mvines @CriesofCarrots

### PR DESCRIPTION
**Pull request by joncinque**
#### Problem

The last valid block height reported by RPC uses the size of the blockhash queue instead of the max processing age, doubling the age. Clients that retry until that block height has passed are waiting twice as long as they should before resending.

#### Summary of Changes

This aims to keep it pretty simple by deprecating `is_hash_valid` and `get_max_age`, which are based on the size of the queue, in favor of using `is_hash_valid_for_age` and `MAX_PROCESSING_AGE`. These functions were not used outside of the bank, so the fix is really at the bank level.

The functions on the bank that change, `is_blockhash_valid` and `get_blockhash_last_valid_block_height`, are only used by clients.

Fixes https://github.com/solana-labs/solana/issues/24526

### CODE REVIEW

File: runtime/src/bank.rs [hunk 1]
```diff
@@ -3075,7 +3075,7 @@ impl Bank {
 
     pub fn is_blockhash_valid(&self, hash: &Hash) -> bool {
         let blockhash_queue = self.blockhash_queue.read().unwrap();
-        blockhash_queue.is_hash_valid(hash)
+        blockhash_queue.is_hash_valid_for_age(hash, MAX_PROCESSING_AGE)
```
Comment (CriesofCarrots) [inline runtime/src/bank.rs:3078]: Wow! :so-beautiful:

**Review by jstarry — APPROVED** [review]
