### PR TITLE
cli: add --authority and --payer flags to `solana program extend`

### LINKED ISSUE #10509: solana program extend doesn't work with payer key different from upgrade authority of the program
#### Problem
I'm trying to extend program buffer account using a payer that is different from the program upgrade authority.
BPF program allows this, but CLI does not.
```sh
solana program extend <...> 1000

Error: Upgrade authority <...> does not match <...>
```
https://github.com/anza-xyz/agave/blob/4887e4e04138bc580ac8d795a9a467b67279e862/cli/src/program.rs#L2514-L2521

#### Proposed Solution
There should be config flag to skip this check.

### PR DESCRIPTION
**Pull request by Not-Sarthak**
## Problem

The `solana program extend` CLI command fails when the payer (fee payer / default signer) is different from the program's upgrade authority. The BPF loader's `ExtendProgramChecked` instruction allows this -- it only requires the authority to sign, and the payer can be a separate account. But the CLI had no `--authority` or `--payer` flags on the `extend` subcommand, so both always defaulted to the fee payer.

Fixes #10509

## Summary of Changes

- Add `--authority` argument to the `extend` subcommand for specifying the upgrade authority signer
- Add `--payer` argument to the `extend` subcommand for specifying a separate rent payer
- Add parse test coverage for `--authority`, `--payer`, and both combined in `test_cli_parse_extend_program`
- Add integration test that extends a program using a separate fee payer, authority, and rent payer

### CODE REVIEW

File: cli/tests/program.rs [hunk 1]
```diff
@@ -1593,6 +1593,30 @@ async fn test_cli_program_extend_program() {
...
     });
     process_command(&config).await.unwrap();
+
+    wait_n_slots(&rpc_client, 1).await;
+
+    let different_payer = Keypair::new();
+    config.signers = vec![&different_payer];
+    config.command = CliCommand::Airdrop {
+        pubkey: None,
+        lamports: 100 * minimum_balance_for_programdata,
```
Comment (buffalojoec) [inline cli/tests/program.rs]: nit: the new payer here doesn't need that many funds. This is enough for 100 programdata accounts!

Instead, you could just airdrop enough for the transaction fee. See my other comment about the two different payers involved here, too.

**Review by buffalojoec — COMMENTED** [review]
Lgtm! Seems like the arg was just missing.

https://github.com/anza-xyz/agave/blob/6bc93cb06fb55ca20bda1a5017109ec7f825fcc3/cli/src/program.rs#L1015-L1020

We are actually missing two arguments: the `authority` *and* the optional `payer` who is responsible for topping up the extended programdata account's rent:

https://github.com/anza-xyz/solana-sdk/blob/54449336c03ae8a99bc37745ac97ab90a77eb24b/loader-v3-interface/src/instruction.rs#L195-L196

Mind adding the `payer` here as well?

File: cli/tests/program.rs (hunk 1 above)
Comment (Not-Sarthak) [reply cli/tests/program.rs]: yes sure, thanks for flagging!

added `--payer` flag as well for a separate rent payer, and reduced the airdrop in the test.

let me know if anything else is to be done

File: cli/tests/program.rs [hunk 2]
```diff
@@ -1593,6 +1595,32 @@ async fn test_cli_program_extend_program() {
...
     process_command(&config).await.unwrap();
+
+    wait_n_slots(&rpc_client, 1).await;
+
+    // Extend with separate fee payer, authority, and rent payer
+    let rent_payer = Keypair::new();
+    config.signers = vec![&rent_payer];
+    config.command = CliCommand::Airdrop {
+        pubkey: None,
+        lamports: minimum_balance_for_programdata,
```
Comment (buffalojoec) [inline cli/tests/program.rs]: You can just use Rent::min_balance(1024).

File: cli/tests/program.rs
Comment (buffalojoec) [inline cli/tests/program.rs:1]: Can you also add some coverage to `test_cli_parse_extend_program` (line 4604 in this file) so we can make sure parsing of the explicit `--authority` and `--payer` args is covered? You can see `test_cli_parse_close` does a nice job of this.

**Review by buffalojoec — COMMENTED** [review]
Looking great, thanks for adding both args.

Do you mind changing the PR title and description? Just add the test coverage I mentioned and we can ship this.

File: cli/tests/program.rs (hunk 2 above)
Comment (Not-Sarthak) [reply cli/tests/program.rs]: just to confirm the method here is `minimum_balance` right?

correct me if i am wrong here. pushed the below mentioned changes as well

**Review by buffalojoec — APPROVED** [review]
Looks great! Thanks for the fix!
