### PR TITLE
[streamer] Fix musl build

### LINKED ISSUE #3971: error: cannot construct `msghdr` with struct literal syntax due to private fields
```
Step 3/13 : RUN cargo --version
 ---> Running in 7543266d511d
cargo 1.82.0 (8f40fc59f 2024-08-2
```

Docker image: rust:alpine

```
   Compiling solana-streamer v2.1.4
error: cannot construct `msghdr` with struct literal syntax due to private fields
   --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/solana-streamer-2.1.4/src/recvmmsg.rs:112:22
    |
112 |             msg_hdr: msghdr {
    |                      ^^^^^^
    |
    = note: ...and other private fields `__pad1` and `__pad2` that were not provided

error: cannot construct `msghdr` with struct literal syntax due to private fields
   --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/solana-streamer-2.1.4/src/sendmmsg.rs:100:18
    |
100 |         msg_hdr: msghdr {
    |                  ^^^^^^
    |
    = note: ...and other private fields `__pad1` and `__pad2` that were not provided

error: could not compile `solana-streamer` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...

```

### PR DESCRIPTION
**Pull request by jalaziz**
#### Problem

msghdr cannot be directly instantiated on musl due to private padding fields (see rust-lang/libc#2344). The recommended solution is to use `mem::zeroed` to initialize the struct then set the fields as needed.

While we could use the same solution for both glibc and musl, we use a conditional compilation directive to avoid using unsafe code when it's not required.

#### Summary of Changes

* Use `mem::zeroed` to initalize the `msghdr` struct on musl to avoid issues with private padding fields.

### CODE REVIEW

File: streamer/src/recvmmsg.rs [hunk 1]
```diff
@@ -107,17 +107,35 @@ pub fn recv_mmsg(sock: &UdpSocket, packets: &mut [Packet]) -> io::Result</*num p
             iov_len: buffer.len(),
         });
 
-        hdr.write(mmsghdr {
-            msg_len: 0,
-            msg_hdr: msghdr {
+        let mut msg_hdr: msghdr;
```
Comment (joncinque) [inline streamer/src/recvmmsg.rs]: This triggers a warning in non-musl builds because it doesn't need to be mutable. Let's just add an `#[allow(unused_mut)]` on top with a comment.

Our other options are to replicate all of the code under each block (have `hdr.write(...)` under the `cfg`), or to have a function to return the `msghdr`, but I think those will be easier to break in the future. What do you think?

```suggestion
        // Mutable for musl builds, see https://github.com/rust-lang/libc/issues/2344 for more info
        #[allow(unused_mut)]
        let mut msg_hdr: msghdr;
```

File: streamer/src/sendmmsg.rs [hunk 2]
```diff
@@ -95,17 +95,35 @@ fn mmsghdr_for_packet(
         }
     };
 
-    hdr.write(mmsghdr {
-        msg_len: 0,
-        msg_hdr: msghdr {
+    let mut msg_hdr: msghdr;
```
Comment (joncinque) [inline streamer/src/sendmmsg.rs]: Same here, we can do whatever we decide on the other comment

**Review by joncinque — COMMENTED** [review]
Thanks for the contribution! I confirm that this works on a musl build

File: streamer/src/recvmmsg.rs (hunk 1 above)
Comment (jalaziz) [reply streamer/src/recvmmsg.rs]: Yeah, I think the allow directive makes the most sense here. It limits the amount of duplication.

Having a function could also work, not sure it would be any more fragile. Will give it a shot and push an update.

Comment (jalaziz) [reply streamer/src/recvmmsg.rs]: Just pushed a change which I think fixes the lint warning without necessarily making things too complicated.

**Review by joncinque — APPROVED** [review]
Looks great, thanks for fixing it up!

**Comment by Ma233** [comment]
Hello, I found that this pull request is not included in the latest version v2.1.10. Is there any consideration for this? We are trying to use the musl target compilation, and this pull request is very necessary for us.

**Comment by steviez** [comment]
> Hello, I found that this pull request is not included in the latest version v2.1.10.

Hi @Ma233, that is correct. This PR landed after the v2.1 branch had already been created. Our general flow involves several branches, and gives time for changes to run before being recommended for mass adoption. You can see some more details [here](https://github.com/anza-xyz/agave/blob/master/RELEASE.md) if you're interested.

If all goes well, we should be pushing mainnet beta to v2.1 in a couple weeks, which would coincide with us creating a v2.2 branch and tags. Is that timeline workable for you or are you specifically looking to build against v2.1 crates (ie you're running a validator against specific cluster) ?

**Comment by joncinque** [comment]
Note that in the meantime, you can apply this patch on the v2.1 branch and build everything yourself. I just did a test and it works perfectly.

**Comment by Ma233** [comment]
@steviez Hi, I encountered this issue while building a Rust project that invokes solana program, and I aim to release the package with the musl target.

@joncinque Thanks for your advice. I tried to specific my dependencies in git commit format.
```diff
diff --git a/crates/balance-payment-sdk/Cargo.toml b/crates/balance-payment-sdk/Cargo.toml
index 548eaa6..810bfbe 100644
--- a/crates/balance-payment-sdk/Cargo.toml
+++ b/crates/balance-payment-sdk/Cargo.toml
@@ -18,9 +18,9 @@ serde = { version = "1.0.217", optional = true }
 serde_json = "1.0.137"
 serde_with = { version = "3.12.0", optional = true }
 sha2 = "0.10"
-solana-client = "2.1.10"
-solana-program = "2.1.10"
-solana-sdk = "2.1.10"
-solana-zk-token-sdk = "2.1.10"
+solana-client = { version = "2.1.11", git = "https://github.com/dephy-io/agave.git", rev = "134be7c14066ea00c9791187d6bbc4795dd92f0e" }
+solana-program = { version = "2.1.11", git = "https://github.com/dephy-io/agave.git", rev = "134be7c14066ea00c9791187d6bbc4795dd92f0e" }
+solana-sdk = { version = "2.1.11", git = "https://github.com/dephy-io/agave.git", rev = "134be7c14066ea00c9791187d6bbc4795dd92f0e" }
+solana-zk-token-sdk = { version = "2.1.11", git = "https://github.com/dephy-io/agave.git", rev = "134be7c14066ea00c9791187d6bbc4795dd92f0e" }
 thiserror = "2.0.11"
 tracing = "0.1.41"
```

But got errors like this.

<details>

<summary>check fails</summary>

```
    Checking solana-account-decoder v2.1.11 (https://github.com/dephy-io/agave.git?rev=134be7c14066ea00c9791187d6bbc4795dd92f0e#134be7c1)
error[E0277]: the trait bound `S: spl_token_2022::solana_program::solana_program_pack::Pack` is not satisfied
   --> /Users/magine/.cargo/git/checkouts/agave-562dd7396af6df1e/134be7c/account-decoder/src/parse_token_extension.rs:23:15
    |
23  |     account: &StateWithExtensions<S>,
    |               ^^^^^^^^^^^^^^^^^^^^^^ the trait `spl_token_2022::solana_program::solana_program_pack::Pack` is not implemented for `S`
    |
note: required by a bound in `StateWithExtensions`
   --> /Users/magine/.cargo/registry/src/index.crates.io-6f17d22bba15001f/spl-token-2022-4.0.0/src/extension/mod.rs:505:54
    |
505 | pub struct StateWithExtensions<'data, S: BaseState + Pack> {
    |                                                      ^^^^ required by this bound in `StateWithExtensions`
help: consider further restricting this bound
    |
21  | pub fn parse_extension<S: BaseState + Pack + spl_token_2022::solana_program::solana_program_pack::Pack>(
    |                                            +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

error[E0308]: mismatched types
    --> /Users/magine/.cargo/git/checkouts/agave-562dd7396af6df1e/134be7c/account-decoder/src/parse_account_data.rs:39:18
     |
29   |         m.insert(
     |         - ... which causes `m` to have type `HashMap<solana_sdk::pubkey::Pubkey, ParsableAccount>`
30   |             *ADDRESS_LOOKUP_PROGRAM_ID,
     |             -------------------------- this argument has type `solana_sdk::pubkey::Pubkey`...
...
39   |         m.insert(spl_token::id(), ParsableAccount::SplToken);
     |           ------ ^^^^^^^^^^^^^^^ expected `solana_sdk::pubkey::Pubkey`, found `Pubkey`
     |           |
     |           arguments to this method are incorrect
     |
     = note: `Pubkey` and `solana_sdk::pubkey::Pubkey` have similar names, but are actually distinct types
note: `Pubkey` is defined in crate `solana_pubkey`
    --> /Users/magine/.cargo/registry/src/index.crates.io-6f17d22bba15001f/solana-pubkey-2.1.11/src/lib.rs:163:1
     |
163  | pub struct Pubkey(pub(crate) [u8; 32]);
     | ^^^^^^^^^^^^^^^^^
note: `solana_sdk::pubkey::Pubkey` is defined in crate `solana_pubkey`
    --> /Users/magine/.cargo/git/checkouts/agave-562dd7396af6df1e/134be7c/sdk/pubkey/src/lib.rs:163:1
     |
163  | pub struct Pubkey(pub(crate) [u8; 32]);
     | ^^^^^^^^^^^^^^^^^
     = note: perhaps two different versions of crate `solana_pubkey` are being used?
note: method defined here
    --> /Users/magine/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/collections/hash/map.rs:1136:12
     |
1136 |     pub fn insert(&mut self, k: K, v: V) -> Option<V> {
     |            ^^^^^^

error[E0308]: mismatched types
    --> /Users/magine/.cargo/git/checkouts/agave-562dd7396af6df1e/134be7c/account-decoder/src/parse_account_data.rs:40:18
     |
29   |         m.insert(
     |         - ... which causes `m` to have type `HashMap<solana_sdk::pubkey::Pubkey, ParsableAccount>`
30   |             *ADDRESS_LOOKUP_PROGRAM_ID,
     |             -------------------------- this argument has type `solana_sdk::pubkey::Pubkey`...
...
40   |         m.insert(spl_token_2022::id(), ParsableAccount::SplToken2022);
     |           ------ ^^^^^^^^^^^^^^^^^^^^ expected `solana_sdk::pubkey::Pubkey`, found `Pubkey`
     |           |
     |           arguments to this method are incorrect
     |
     = note: `Pubkey` and `solana_sdk::pubkey::Pubkey` have similar names, but are actually distinct types
note: `Pubkey` is defined in crate `solana_pubkey`
    --> /Users/magine/.cargo/registry/src/index.crates.io-6f17d22bba15001f/solana-pubkey-2.1.11/src/lib.rs:163:1
     |
163  | pub struct Pubkey(pub(crate) [u8; 32]);
     | ^^^^^^^^^^^^^^^^^
note: `solana_sdk::pubkey::Pubkey` is defined in crate `solana_pubkey`
    --> /Users/magine/.cargo/git/checkouts/agave-562dd7396af6df1e/134be7c/sdk/pubkey/src/lib.rs:163:1
     |
163  | pub struct Pubkey(pub(crate) [u8; 32]);
     | ^^^^^^^^^^^^^^^^^
     = note: perhaps two different versions of crate `solana_pubkey` are being used?
note: method defined here
    --> /Users/magine/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/collections/hash/map.rs:1136:12
     |
1136 |     pub fn insert(&mut self, k: K, v: V) -> Option<V> {
     |            ^^^^^^

error[E0308]: mismatched types
   --> /Users/magine/.cargo/git/checkouts/agave-562dd7396af6df1e/134be7c/account-decoder/src/parse_token.rs:24:10
    |
24  |     vec![spl_token::id(), spl_token_2022::id()]
    |          ^^^^^^^^^^^^^^^ expected `solana_sdk::pubkey::Pubkey`, found `Pubkey`
    |
    = note: `Pubkey` and `solana_sdk::pubkey::Pubkey` have similar names, but are actually distinct types
note: `Pubkey` is defined in crate `solana_pubkey`
   --> /Users/magine/.cargo/registry/src/index.crates.io-6f17d22bba15001f/solana-pubkey-2.1.11/src/lib.rs:163:1
    |
163 | pub struct Pubkey(pub(crate) [u8; 32]);
    | ^^^^^^^^^^^^^^^^^
note: `solana_sdk::pubkey::Pubkey` is defined in crate `solana_pubkey`
   --> /Users/magine/.cargo/git/checkouts/agave-562dd7396af6df1e/134be7c/sdk/pubkey/src/lib.rs:163:1
    |
163 | pub struct Pubkey(pub(crate) [u8; 32]);
    | ^^^^^^^^^^^^^^^^^
    = note: perhaps two different versions of crate `solana_pubkey` are being used?

error[E0308]: mismatched types
   --> /Users/magine/.cargo/git/checkouts/agave-562dd7396af6df1e/134be7c/account-decoder/src/parse_token.rs:29:20
    |
29  |     *program_id == spl_token::id() || *program_id == spl_token_2022::id()
    |     -----------    ^^^^^^^^^^^^^^^ expected `solana_sdk::pubkey::Pubkey`, found `Pubkey`
    |     |
    |     expected because this is `solana_sdk::pubkey::Pubkey`
    |
    = note: `Pubkey` and `solana_sdk::pubkey::Pubkey` have similar names, but are actually distinct types
note: `Pubkey` is defined in crate `solana_pubkey`
   --> /Users/magine/.cargo/registry/src/index.crates.io-6f17d22bba15001f/solana-pubkey-2.1.11/src/lib.rs:163:1
    |
163 | pub struct Pubkey(pub(crate) [u8; 32]);
    | ^^^^^^^^^^^^^^^^^
note: `solana_sdk::pubkey::Pubkey` is defined in crate `solana_pubkey`
   --> /Users/magine/.cargo/git/checkouts/agave-562dd7396af6df1e/134be7c/sdk/pubkey/src/lib.rs:163:1
    |
163 | pub struct Pubkey(pub(crate) [u8; 32]);
    | ^^^^^^^^^^^^^^^^^
    = note: perhaps two different versions of crate `solana_pubkey` are being used?

error[E0308]: mismatched types
   --> /Users/magine/.cargo/git/checkouts/agave-562dd7396af6df1e/134be7c/account-decoder/src/parse_token.rs:29:54
    |
29  |     *program_id == spl_token::id() || *program_id == spl_token_2022::id()
    |                                       -----------    ^^^^^^^^^^^^^^^^^^^^ expected `solana_sdk::pubkey::Pubkey`, found `Pubkey`
    |                                       |
    |                                       expected because this is `solana_sdk::pubkey::Pubkey`
    |
    = note: `Pubkey` and `solana_sdk::pubkey::Pubkey` have similar names, but are actually distinct types
note: `Pubkey` is defined in crate `solana_pubkey`
   --> /Users/magine/.cargo/registry/src/index.crates.io-6f17d22bba15001f/solana-pubkey-2.1.11/src/lib.rs:163:1
    |
163 | pub struct Pubkey(pub(crate) [u8; 32]);
    | ^^^^^^^^^^^^^^^^^
note: `solana_sdk::pubkey::Pubkey` is defined in crate `solana_pubkey`
   --> /Users/magine/.cargo/git/checkouts/agave-562dd7396af6df1e/134be7c/sdk/pubkey/src/lib.rs:163:1
    |
163 | pub struct Pubkey(pub(crate) [u8; 32]);
    | ^^^^^^^^^^^^^^^^^
    = note: perhaps two different versions of crate `solana_pubkey` are being used?

error[E0277]: the trait bound `spl_token_2022::state::Account: solana_sdk::solana_program_pack::Pack` is not satisfied
  --> /Users/magine/.cargo/git/checkouts/agave-562dd7396af6df1e/134be7c/account-decoder/src/parse_token.rs:54:53
   |
54 |             .map(|extension_type| parse_extension::<Account>(extension_type, &account))
   |                                                     ^^^^^^^ the trait `solana_sdk::solana_program_pack::Pack` is not implemented for `spl_token_2022::state::Account`
   |
note: required by a bound in `parse_extension`
  --> /Users/magine/.cargo/git/checkouts/agave-562dd7396af6df1e/134be7c/account-decoder/src/parse_token_extension.rs:21:39
   |
21 | pub fn parse_extension<S: BaseState + Pack>(
   |                                       ^^^^ required by this bound in `parse_extension`

error[E0277]: the trait bound `spl_token_2022::state::Mint: solana_sdk::solana_program_pack::Pack` is not satisfied
  --> /Users/magine/.cargo/git/checkouts/agave-562dd7396af6df1e/134be7c/account-decoder/src/parse_token.rs:91:53
   |
91 |             .map(|extension_type| parse_extension::<Mint>(extension_type, &mint))
   |                                                     ^^^^ the trait `solana_sdk::solana_program_pack::Pack` is not implemented for `spl_token_2022::state::Mint`
   |
note: required by a bound in `parse_extension`
  --> /Users/magine/.cargo/git/checkouts/agave-562dd7396af6df1e/134be7c/account-decoder/src/parse_token_extension.rs:21:39
   |
21 | pub fn parse_extension<S: BaseState + Pack>(
   |                                       ^^^^ required by this bound in `parse_extension`

error[E0599]: the method `get_extension` exists for reference `&StateWithExtensions<'_, S>`, but its trait bounds were not satisfied
   --> /Users/magine/.cargo/git/checkouts/agave-562dd7396af6df1e/134be7c/account-decoder/src/parse_token_extension.rs:28:14
    |
27  |           ExtensionType::TransferFeeConfig => account
    |  _____________________________________________-
28  | |             .get_extension::<extension::transfer_fee::TransferFeeConfig>()
    | |             -^^^^^^^^^^^^^ method cannot be called on `&StateWithExtensions<'_, S>` due to unsatisfied trait bounds
    | |_____________|
    |
    |
   ::: /Users/magine/.cargo/registry/src/index.crates.io-6f17d22bba15001f/spl-token-2022-4.0.0/src/extension/mod.rs:505:1
    |
505 |   pub struct StateWithExtensions<'data, S: BaseState + Pack> {
    |   ---------------------------------------------------------- doesn't satisfy `_: BaseStateWithExtensions<S>`
    |
    = note: the following trait bounds were not satisfied:
            `S: spl_token_2022::solana_program::solana_program_pack::Pack`
            which is required by `StateWithExtensions<'_, S>: BaseStateWithExtensions<S>`
help: consider restricting the type parameter to satisfy the trait bound
    |
24  | ) -> UiExtension where S: spl_token_2022::solana_program::solana_program_pack::Pack {
    |                  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

error[E0599]: the method `get_extension` exists for reference `&StateWithExtensions<'_, S>`, but its trait bounds were not satisfied
   --> /Users/magine/.cargo/git/checkouts/agave-562dd7396af6df1e/134be7c/account-decoder/src/parse_token_extension.rs:34:14
    |
33  |           ExtensionType::TransferFeeAmount => account
    |  _____________________________________________-
34  | |             .get_extension::<extension::transfer_fee::TransferFeeAmount>()
    | |             -^^^^^^^^^^^^^ method cannot be called on `&StateWithExtensions<'_, S>` due to unsatisfied trait bounds
    | |_____________|
    |
    |
   ::: /Users/magine/.cargo/registry/src/index.crates.io-6f17d22bba15001f/spl-token-2022-4.0.0/src/extension/mod.rs:505:1
    |
505 |   pub struct StateWithExtensions<'data, S: BaseState + Pack> {
    |   ---------------------------------------------------------- doesn't satisfy `_: BaseStateWithExtensions<S>`
    |
    = note: the following trait bounds were not satisfied:
            `S: spl_token_2022::solana_program::solana_program_pack::Pack`
            which is required by `StateWithExtensions<'_, S>: BaseStateWithExtensions<S>`
help: consider restricting the type parameter to satisfy the trait bound
    |
24  | ) -> UiExtension where S: spl_token_2022::solana_program::solana_program_pack::Pack {
    |                  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

error[E0599]: the method `get_extension` exists for reference `&StateWithExtensions<'_, S>`, but its trait bounds were not satisfied
   --> /Users/magine/.cargo/git/checkouts/agave-562dd7396af6df1e/134be7c/account-decoder/src/parse_token_extension.rs:40:14
    |
39  |           ExtensionType::MintCloseAuthority => account
    |  ______________________________________________-
40  | |             .get_extension::<extension::mint_close_authority::MintCloseAuthority>()
    | |             -^^^^^^^^^^^^^ method cannot be called on `&StateWithExtensions<'_, S>` due to unsatisfied trait bounds
    | |_____________|
    |
    |
   ::: /Users/magine/.cargo/registry/src/index.crates.io-6f17d22bba15001f/spl-token-2022-4.0.0/src/extension/mod.rs:505:1
    |
505 |   pub struct StateWithExtensions<'data, S: BaseState + Pack> {
    |   ---------------------------------------------------------- doesn't satisfy `_: BaseStateWithExtensions<S>`
    |
    = note: the following trait bounds were not satisfied:
            `S: spl_token_2022::solana_program::solana_program_pack::Pack`
            which is required by `StateWithExtensions<'_, S>: BaseStateWithExtensions<S>`
help: consider restricting the type parameter to satisfy the trait bound
    |
24  | ) -> UiExtension where S: spl_token_2022::solana_program::solana_program_pack::Pack {
    |                  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

error[E0599]: the method `get_extension` exists for reference `&StateWithExtensions<'_, S>`, but its trait bounds were not satisfied
   --> /Users/magine/.cargo/git/checkouts/agave-562dd7396af6df1e/134be7c/account-decoder/src/parse_token_extension.rs:46:14
    |
45  |           ExtensionType::ConfidentialTransferMint => account
    |  ____________________________________________________-
46  | |             .get_extension::<extension::confidential_transfer::ConfidentialTransferMint>()
    | |             -^^^^^^^^^^^^^ method cannot be called on `&StateWithExtensions<'_, S>` due to unsatisfied trait bounds
    | |_____________|
    |
    |
   ::: /Users/magine/.cargo/registry/src/index.crates.io-6f17d22bba15001f/spl-token-2022-4.0.0/src/extension/mod.rs:505:1
    |
505 |   pub struct StateWithExtensions<'data, S: BaseState + Pack> {
    |   ---------------------------------------------------------- doesn't satisfy `_: BaseStateWithExtensions<S>`
    |
    = note: the following trait bounds were not satisfied:
            `S: spl_token_2022::solana_program::solana_program_pack::Pack`
            which is required by `StateWithExtensions<'_, S>: BaseStateWithExtensions<S>`
help: consider restricting the type parameter to satisfy the trait bound
    |
24  | ) -> UiExtension where S: spl_token_2022::solana_program::solana_program_pack::Pack {
    |                  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

error[E0599]: the method `get_extension` exists for reference `&StateWithExtensions<'_, S>`, but its trait bounds were not satisfied
   --> /Users/magine/.cargo/git/checkouts/agave-562dd7396af6df1e/134be7c/account-decoder/src/parse_token_extension.rs:52:14
    |
51  |           ExtensionType::ConfidentialTransferFeeConfig => account
    |  _________________________________________________________-
52  | |             .get_extension::<extension::confidential_transfer_fee::ConfidentialTransferFeeConfig>()
    | |             -^^^^^^^^^^^^^ method cannot be called on `&StateWithExtensions<'_, S>` due to unsatisfied trait bounds
    | |_____________|
    |
    |
   ::: /Users/magine/.cargo/registry/src/index.crates.io-6f17d22bba15001f/spl-token-2022-4.0.0/src/extension/mod.rs:505:1
    |
505 |   pub struct StateWithExtensions<'data, S: BaseState + Pack> {
    |   ---------------------------------------------------------- doesn't satisfy `_: BaseStateWithExtensions<S>`
    |
    = note: the following trait bounds were not satisfied:
            `S: spl_token_2022::solana_program::solana_program_pack::Pack`
            which is required by `StateWithExtensions<'_, S>: BaseStateWithExtensions<S>`
help: consider restricting the type parameter to satisfy the trait bound
    |
24  | ) -> UiExtension where S: spl_token_2022::solana_program::solana_program_pack::Pack {
    |                  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

error[E0599]: the method `get_extension` exists for reference `&StateWithExtensions<'_, S>`, but its trait bounds were not satisfied
   --> /Users/magine/.cargo/git/checkouts/agave-562dd7396af6df1e/134be7c/account-decoder/src/parse_token_extension.rs:60:14
    |
59  |           ExtensionType::ConfidentialTransferAccount => account
    |  _______________________________________________________-
60  | |             .get_extension::<extension::confidential_transfer::ConfidentialTransferAccount>()
    | |             -^^^^^^^^^^^^^ method cannot be called on `&StateWithExtensions<'_, S>` due to unsatisfied trait bounds
    | |_____________|
    |
    |
   ::: /Users/magine/.cargo/registry/src/index.crates.io-6f17d22bba15001f/spl-token-2022-4.0.0/src/extension/mod.rs:505:1
    |
505 |   pub struct StateWithExtensions<'data, S: BaseState + Pack> {
    |   ---------------------------------------------------------- doesn't satisfy `_: BaseStateWithExtensions<S>`
    |
    = note: the following trait bounds were not satisfied:
            `S: spl_token_2022::solana_program::solana_program_pack::Pack`
            which is required by `StateWithExtensions<'_, S>: BaseStateWithExtensions<S>`
help: consider restricting the type parameter to satisfy the trait bound
    |
24  | ) -> UiExtension where S: spl_token_2022::solana_program::solana_program_pack::Pack {
    |                  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

error[E0599]: the method `get_extension` exists for reference `&StateWithExtensions<'_, S>`, but its trait bounds were not satisfied
   --> /Users/magine/.cargo/git/checkouts/agave-562dd7396af6df1e/134be7c/account-decoder/src/parse_token_extension.rs:68:14
    |
67  |           ExtensionType::ConfidentialTransferFeeAmount => account
    |  _________________________________________________________-
68  | |             .get_extension::<extension::confidential_transfer_fee::ConfidentialTransferFeeAmount>()
    | |             -^^^^^^^^^^^^^ method cannot be called on `&StateWithExtensions<'_, S>` due to unsatisfied trait bounds
    | |_____________|
    |
    |
   ::: /Users/magine/.cargo/registry/src/index.crates.io-6f17d22bba15001f/spl-token-2022-4.0.0/src/extension/mod.rs:505:1
    |
505 |   pub struct StateWithExtensions<'data, S: BaseState + Pack> {
    |   ---------------------------------------------------------- doesn't satisfy `_: BaseStateWithExtensions<S>`
    |
    = note: the following trait bounds were not satisfied:
            `S: spl_token_2022::solana_program::solana_program_pack::Pack`
            which is required by `StateWithExtensions<'_, S>: BaseStateWithExtensions<S>`
help: consider restricting the type parameter to satisfy the trait bound
    |
24  | ) -> UiExtension where S: spl_token_2022::solana_program::solana_program_pack::Pack {
    |                  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

error[E0599]: the method `get_extension` exists for reference `&StateWithExtensions<'_, S>`, but its trait bounds were not satisfied
   --> /Users/magine/.cargo/git/checkouts/agave-562dd7396af6df1e/134be7c/account-decoder/src/parse_token_extension.rs:76:14
    |
75  |           ExtensionType::DefaultAccountState => account
    |  _______________________________________________-
76  | |             .get_extension::<extension::default_account_state::DefaultAccountState>()
    | |             -^^^^^^^^^^^^^ method cannot be called on `&StateWithExtensions<'_, S>` due to unsatisfied trait bounds
    | |_____________|
    |
    |
   ::: /Users/magine/.cargo/registry/src/index.crates.io-6f17d22bba15001f/spl-token-2022-4.0.0/src/extension/mod.rs:505:1
    |
505 |   pub struct StateWithExtensions<'data, S: BaseState + Pack> {
    |   ---------------------------------------------------------- doesn't satisfy `_: BaseStateWithExtensions<S>`
    |
    = note: the following trait bounds were not satisfied:
            `S: spl_token_2022::solana_program::solana_program_pack::Pack`
            which is required by `StateWithExtensions<'_, S>: BaseStateWithExtensions<S>`
help: consider restricting the type parameter to satisfy the trait bound
    |
24  | ) -> UiExtension where S: spl_token_2022::solana_program::solana_program_pack::Pack {
    |                  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

error[E0599]: the method `get_extension` exists for reference `&StateWithExtensions<'_, S>`, but its trait bounds were not satisfied
   --> /Users/magine/.cargo/git/checkouts/agave-562dd7396af6df1e/134be7c/account-decoder/src/parse_token_extension.rs:83:14
    |
82  |           ExtensionType::MemoTransfer => account
    |  ________________________________________-
83  | |             .get_extension::<extension::memo_transfer::MemoTransfer>()
    | |             -^^^^^^^^^^^^^ method cannot be called on `&StateWithExtensions<'_, S>` due to unsatisfied trait bounds
    | |_____________|
    |
    |
   ::: /Users/magine/.cargo/registry/src/index.crates.io-6f17d22bba15001f/spl-token-2022-4.0.0/src/extension/mod.rs:505:1
    |
505 |   pub struct StateWithExtensions<'data, S: BaseState + Pack> {
    |   ---------------------------------------------------------- doesn't satisfy `_: BaseStateWithExtensions<S>`
    |
    = note: the following trait bounds were not satisfied:
            `S: spl_token_2022::solana_program::solana_program_pack::Pack`
            which is required by `StateWithExtensions<'_, S>: BaseStateWithExtensions<S>`
help: consider restricting the type parameter to satisfy the trait bound
    |
24  | ) -> UiExtension where S: spl_token_2022::solana_program::solana_program_pack::Pack {
    |                  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

error[E0599]: the method `get_extension` exists for reference `&StateWithExtensions<'_, S>`, but its trait bounds were not satisfied
   --> /Users/magine/.cargo/git/checkouts/agave-562dd7396af6df1e/134be7c/account-decoder/src/parse_token_extension.rs:88:14
    |
87  |           ExtensionType::InterestBearingConfig => account
    |  _________________________________________________-
88  | |             .get_extension::<extension::interest_bearing_mint::InterestBearingConfig>()
    | |             -^^^^^^^^^^^^^ method cannot be called on `&StateWithExtensions<'_, S>` due to unsatisfied trait bounds
    | |_____________|
    |
    |
   ::: /Users/magine/.cargo/registry/src/index.crates.io-6f17d22bba15001f/spl-token-2022-4.0.0/src/extension/mod.rs:505:1
    |
505 |   pub struct StateWithExtensions<'data, S: BaseState + Pack> {
    |   ---------------------------------------------------------- doesn't satisfy `_: BaseStateWithExtensions<S>`
    |
    = note: the following trait bounds were not satisfied:
            `S: spl_token_2022::solana_program::solana_program_pack::Pack`
            which is required by `StateWithExtensions<'_, S>: BaseStateWithExtensions<S>`
help: consider restricting the type parameter to satisfy the trait bound
    |
24  | ) -> UiExtension where S: spl_token_2022::solana_program::solana_program_pack::Pack {
    |                  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

error[E0599]: the method `get_extension` exists for reference `&StateWithExtensions<'_, S>`, but its trait bounds were not satisfied
   --> /Users/magine/.cargo/git/checkouts/agave-562dd7396af6df1e/134be7c/account-decoder/src/parse_token_extension.rs:94:14
    |
93  |           ExtensionType::CpiGuard => account
    |  ____________________________________-
94  | |             .get_extension::<extension::cpi_guard::CpiGuard>()
    | |             -^^^^^^^^^^^^^ method cannot be called on `&StateWithExtensions<'_, S>` due to unsatisfied trait bounds
    | |_____________|
    |
    |
   ::: /Users/magine/.cargo/registry/src/index.crates.io-6f17d22bba15001f/spl-token-2022-4.0.0/src/extension/mod.rs:505:1
    |
505 |   pub struct StateWithExtensions<'data, S: BaseState + Pack> {
    |   ---------------------------------------------------------- doesn't satisfy `_: BaseStateWithExtensions<S>`
    |
    = note: the following trait bounds were not satisfied:
            `S: spl_token_2022::solana_program::solana_program_pack::Pack`
            which is required by `StateWithExtensions<'_, S>: BaseStateWithExtensions<S>`
help: consider restricting the type parameter to satisfy the trait bound
    |
24  | ) -> UiExtension where S: spl_token_2022::solana_program::solana_program_pack::Pack {
    |                  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

error[E0599]: the method `get_extension` exists for reference `&StateWithExtensions<'_, S>`, but its trait bounds were not satisfied
   --> /Users/magine/.cargo/git/checkouts/agave-562dd7396af6df1e/134be7c/account-decoder/src/parse_token_extension.rs:98:14
    |
97  |           ExtensionType::PermanentDelegate => account
    |  _____________________________________________-
98  | |             .get_extension::<extension::permanent_delegate::PermanentDelegate>()
    | |             -^^^^^^^^^^^^^ method cannot be called on `&StateWithExtensions<'_, S>` due to unsatisfied trait bounds
    | |_____________|
    |
    |
   ::: /Users/magine/.cargo/registry/src/index.crates.io-6f17d22bba15001f/spl-token-2022-4.0.0/src/extension/mod.rs:505:1
    |
505 |   pub struct StateWithExtensions<'data, S: BaseState + Pack> {
    |   ---------------------------------------------------------- doesn't satisfy `_: BaseStateWithExtensions<S>`
    |
    = note: the following trait bounds were not satisfied:
            `S: spl_token_2022::solana_program::solana_program_pack::Pack`
            which is required by `StateWithExtensions<'_, S>: BaseStateWithExtensions<S>`
help: consider restricting the type parameter to satisfy the trait bound
    |
24  | ) -> UiExtension where S: spl_token_2022::solana_program::solana_program_pack::Pack {
    |                  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

error[E0599]: the method `get_extension` exists for reference `&StateWithExtensions<'_, S>`, but its trait bounds were not satisfied
   --> /Users/magine/.cargo/git/checkouts/agave-562dd7396af6df1e/134be7c/account-decoder/src/parse_token_extension.rs:103:14
    |
102 |           ExtensionType::MetadataPointer => account
    |  ___________________________________________-
103 | |             .get_extension::<extension::metadata_pointer::MetadataPointer>()
    | |             -^^^^^^^^^^^^^ method cannot be called on `&StateWithExtensions<'_, S>` due to unsatisfied trait bounds
    | |_____________|
    |
    |
   ::: /Users/magine/.cargo/registry/src/index.crates.io-6f17d22bba15001f/spl-token-2022-4.0.0/src/extension/mod.rs:505:1
    |
505 |   pub struct StateWithExtensions<'data, S: BaseState + Pack> {
    |   ---------------------------------------------------------- doesn't satisfy `_: BaseStateWithExtensions<S>`
    |
    = note: the following trait bounds were not satisfied:
            `S: spl_token_2022::solana_program::solana_program_pack::Pack`
            which is required by `StateWithExtensions<'_, S>: BaseStateWithExtensions<S>`
help: consider restricting the type parameter to satisfy the trait bound
    |
24  | ) -> UiExtension where S: spl_token_2022::solana_program::solana_program_pack::Pack {
    |                  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

error[E0599]: the method `get_variable_len_extension` exists for reference `&StateWithExtensions<'_, S>`, but its trait bounds were not satisfied
   --> /Users/magine/.cargo/git/checkouts/agave-562dd7396af6df1e/134be7c/account-decoder/src/parse_token_extension.rs:107:14
    |
106 |           ExtensionType::TokenMetadata => account
    |  _________________________________________-
107 | |             .get_variable_len_extension::<TokenMetadata>()
    | |             -^^^^^^^^^^^^^^^^^^^^^^^^^^ method cannot be called on `&StateWithExtensions<'_, S>` due to unsatisfied trait bounds
    | |_____________|
    |
    |
   ::: /Users/magine/.cargo/registry/src/index.crates.io-6f17d22bba15001f/spl-token-2022-4.0.0/src/extension/mod.rs:505:1
    |
505 |   pub struct StateWithExtensions<'data, S: BaseState + Pack> {
    |   ---------------------------------------------------------- doesn't satisfy `_: BaseStateWithExtensions<S>`
    |
    = note: the following trait bounds were not satisfied:
            `S: spl_token_2022::solana_program::solana_program_pack::Pack`
            which is required by `StateWithExtensions<'_, S>: BaseStateWithExtensions<S>`
help: consider restricting the type parameter to satisfy the trait bound
    |
24  | ) -> UiExtension where S: spl_token_2022::solana_program::solana_program_pack::Pack {
    |                  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

error[E0599]: the method `get_extension` exists for reference `&StateWithExtensions<'_, S>`, but its trait bounds were not satisfied
   --> /Users/magine/.cargo/git/checkouts/agave-562dd7396af6df1e/134be7c/account-decoder/src/parse_token_extension.rs:111:14
    |
110 |           ExtensionType::TransferHook => account
    |  ________________________________________-
111 | |             .get_extension::<extension::transfer_hook::TransferHook>()
    | |             -^^^^^^^^^^^^^ method cannot be called on `&StateWithExtensions<'_, S>` due to unsatisfied trait bounds
    | |_____________|
    |
    |
   ::: /Users/magine/.cargo/registry/src/index.crates.io-6f17d22bba15001f/spl-token-2022-4.0.0/src/extension/mod.rs:505:1
    |
505 |   pub struct StateWithExtensions<'data, S: BaseState + Pack> {
    |   ---------------------------------------------------------- doesn't satisfy `_: BaseStateWithExtensions<S>`
    |
    = note: the following trait bounds were not satisfied:
            `S: spl_token_2022::solana_program::solana_program_pack::Pack`
            which is required by `StateWithExtensions<'_, S>: BaseStateWithExtensions<S>`
help: consider restricting the type parameter to satisfy the trait bound
    |
24  | ) -> UiExtension where S: spl_token_2022::solana_program::solana_program_pack::Pack {
    |                  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

error[E0599]: the method `get_extension` exists for reference `&StateWithExtensions<'_, S>`, but its trait bounds were not satisfied
   --> /Users/magine/.cargo/git/checkouts/agave-562dd7396af6df1e/134be7c/account-decoder/src/parse_token_extension.rs:115:14
    |
114 |           ExtensionType::TransferHookAccount => account
    |  _______________________________________________-
115 | |             .get_extension::<extension::transfer_hook::TransferHookAccount>()
    | |             -^^^^^^^^^^^^^ method cannot be called on `&StateWithExtensions<'_, S>` due to unsatisfied trait bounds
    | |_____________|
    |
    |
   ::: /Users/magine/.cargo/registry/src/index.crates.io-6f17d22bba15001f/spl-token-2022-4.0.0/src/extension/mod.rs:505:1
    |
505 |   pub struct StateWithExtensions<'data, S: BaseState + Pack> {
    |   ---------------------------------------------------------- doesn't satisfy `_: BaseStateWithExtensions<S>`
    |
    = note: the following trait bounds were not satisfied:
            `S: spl_token_2022::solana_program::solana_program_pack::Pack`
            which is required by `StateWithExtensions<'_, S>: BaseStateWithExtensions<S>`
help: consider restricting the type parameter to satisfy the trait bound
    |
24  | ) -> UiExtension where S: spl_token_2022::solana_program::solana_program_pack::Pack {
    |                  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

error[E0599]: the method `get_extension` exists for reference `&StateWithExtensions<'_, S>`, but its trait bounds were not satisfied
   --> /Users/magine/.cargo/git/checkouts/agave-562dd7396af6df1e/134be7c/account-decoder/src/parse_token_extension.rs:121:14
    |
120 |           ExtensionType::GroupPointer => account
    |  ________________________________________-
121 | |             .get_extension::<extension::group_pointer::GroupPointer>()
    | |             -^^^^^^^^^^^^^ method cannot be called on `&StateWithExtensions<'_, S>` due to unsatisfied trait bounds
    | |_____________|
    |
    |
   ::: /Users/magine/.cargo/registry/src/index.crates.io-6f17d22bba15001f/spl-token-2022-4.0.0/src/extension/mod.rs:505:1
    |
505 |   pub struct StateWithExtensions<'data, S: BaseState + Pack> {
    |   ---------------------------------------------------------- doesn't satisfy `_: BaseStateWithExtensions<S>`
    |
    = note: the following trait bounds were not satisfied:
            `S: spl_token_2022::solana_program::solana_program_pack::Pack`
            which is required by `StateWithExtensions<'_, S>: BaseStateWithExtensions<S>`
help: consider restricting the type parameter to satisfy the trait bound
    |
24  | ) -> UiExtension where S: spl_token_2022::solana_program::solana_program_pack::Pack {
    |                  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

error[E0599]: the method `get_extension` exists for reference `&StateWithExtensions<'_, S>`, but its trait bounds were not satisfied
   --> /Users/magine/.cargo/git/checkouts/agave-562dd7396af6df1e/134be7c/account-decoder/src/parse_token_extension.rs:125:14
    |
124 |           ExtensionType::GroupMemberPointer => account
    |  ______________________________________________-
125 | |             .get_extension::<extension::group_member_pointer::GroupMemberPointer>()
    | |             -^^^^^^^^^^^^^ method cannot be called on `&StateWithExtensions<'_, S>` due to unsatisfied trait bounds
    | |_____________|
    |
    |
   ::: /Users/magine/.cargo/registry/src/index.crates.io-6f17d22bba15001f/spl-token-2022-4.0.0/src/extension/mod.rs:505:1
    |
505 |   pub struct StateWithExtensions<'data, S: BaseState + Pack> {
    |   ---------------------------------------------------------- doesn't satisfy `_: BaseStateWithExtensions<S>`
    |
    = note: the following trait bounds were not satisfied:
            `S: spl_token_2022::solana_program::solana_program_pack::Pack`
            which is required by `StateWithExtensions<'_, S>: BaseStateWithExtensions<S>`
help: consider restricting the type parameter to satisfy the trait bound
    |
24  | ) -> UiExtension where S: spl_token_2022::solana_program::solana_program_pack::Pack {
    |                  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

error[E0599]: the method `get_extension` exists for reference `&StateWithExtensions<'_, S>`, but its trait bounds were not satisfied
   --> /Users/magine/.cargo/git/checkouts/agave-562dd7396af6df1e/134be7c/account-decoder/src/parse_token_extension.rs:131:14
    |
130 |           ExtensionType::TokenGroup => account
    |  ______________________________________-
131 | |             .get_extension::<TokenGroup>()
    | |             -^^^^^^^^^^^^^ method cannot be called on `&StateWithExtensions<'_, S>` due to unsatisfied trait bounds
    | |_____________|
    |
    |
   ::: /Users/magine/.cargo/registry/src/index.crates.io-6f17d22bba15001f/spl-token-2022-4.0.0/src/extension/mod.rs:505:1
    |
505 |   pub struct StateWithExtensions<'data, S: BaseState + Pack> {
    |   ---------------------------------------------------------- doesn't satisfy `_: BaseStateWithExtensions<S>`
    |
    = note: the following trait bounds were not satisfied:
            `S: spl_token_2022::solana_program::solana_program_pack::Pack`
            which is required by `StateWithExtensions<'_, S>: BaseStateWithExtensions<S>`
help: consider restricting the type parameter to satisfy the trait bound
    |
24  | ) -> UiExtension where S: spl_token_2022::solana_program::solana_program_pack::Pack {
    |                  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

error[E0599]: the method `get_extension` exists for reference `&StateWithExtensions<'_, S>`, but its trait bounds were not satisfied
   --> /Users/magine/.cargo/git/checkouts/agave-562dd7396af6df1e/134be7c/account-decoder/src/parse_token_extension.rs:135:14
    |
134 |           ExtensionType::TokenGroupMember => account
    |  ____________________________________________-
135 | |             .get_extension::<TokenGroupMember>()
    | |             -^^^^^^^^^^^^^ method cannot be called on `&StateWithExtensions<'_, S>` due to unsatisfied trait bounds
    | |_____________|
    |
    |
   ::: /Users/magine/.cargo/registry/src/index.crates.io-6f17d22bba15001f/spl-token-2022-4.0.0/src/extension/mod.rs:505:1
    |
505 |   pub struct StateWithExtensions<'data, S: BaseState + Pack> {
    |   ---------------------------------------------------------- doesn't satisfy `_: BaseStateWithExtensions<S>`
    |
    = note: the following trait bounds were not satisfied:
            `S: spl_token_2022::solana_program::solana_program_pack::Pack`
            which is required by `StateWithExtensions<'_, S>: BaseStateWithExtensions<S>`
help: consider restricting the type parameter to satisfy the trait bound
    |
24  | ) -> UiExtension where S: spl_token_2022::solana_program::solana_program_pack::Pack {
    |                  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Some errors have detailed explanations: E0277, E0308, E0599.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `solana-account-decoder` (lib) due to 28 previous errors
```
</details>

This is strange. I haven't put this PR in yet -- the rev `134be7c14066ea00c9791187d6bbc4795dd92f0e` I was trying to use was the same as tag v2.1.11. But these errors just appeared unexpectedly.

**Comment by joncinque** [comment]
> Thanks for your advice. I tried to specific my dependencies in git commit format.

@Ma233 if you want to use git dependencies, then you also need to patch the sdk crates. Try copying what the agave monorepo does: https://github.com/anza-xyz/agave/blob/947c7c06c1e5d3c4e2d2e7639cf65a8212abe0d3/Cargo.toml#L736-L751

**Comment by t-nelson** [comment]
why was this done with so much replicode?

**Comment by joncinque** [comment]
It's kind of tough to reduce replicode when you have two different ways of creating a struct -- what do you recommend as a better alternative?

**Comment by jalaziz** [comment]
> It's kind of tough to reduce replicode when you have two different ways of creating a struct -- what do you recommend as a better alternative?

We could reduce the duplication by using the unsafe + mutable initialization for both platforms, but I intentionally chose not to do that in favor of safety on platforms where we can use safer code as called out in the PR description:

> While we could use the same solution for both glibc and musl, we use a conditional compilation directive to avoid using unsafe code when it's not required.

**Comment by t-nelson** [comment]
> > It's kind of tough to reduce replicode when you have two different ways of creating a struct -- what do you recommend as a better alternative?
> 
> We could reduce the duplication by using the unsafe + mutable initialization for both platforms, but I intentionally chose not to do that in favor of safety on platforms where we can use safer code as called out in the PR description:

this and a helper method

> > While we could use the same solution for both glibc and musl, we use a conditional compilation directive to avoid using unsafe code when it's not required.

`unsafe` is nothing to be avoided. certainly not at the cost of platform differences
