### PR TITLE
Rpc: deprecate `getStakeActivation` and make inactive_stake consistent

### LINKED ISSUE #35111: getStakeActivation rpc method incorrect inactive balance
#### Problem

When funds are sent to an active stake account (by mistake or by e.g. JITO pools), the result of `getStakeActivation` remains unchanged. While `active` stake balance remains correct, I'd expect the `inactive` stake balance to not be 0, but be equal to the sent amount. Example:

before:
```
    "result": {
        "active": 100000000,
        "inactive": 0,
        "state": "active"
    },
```
-- send 0.1 SOL to the stake account
after:
```
    "result": {
        "active": 100000000,
        "inactive": 0,
        "state": "active"
    },
```
However, this state would be expected:
```
    "result": {
        "active": 100000000,
        "inactive": 100000000,
        "state": "active"
    },
```

#### Proposed Solution
Do not hardcode "0" inactiveBalance if the stake account is in an 'active' state, but calculate the inactiveBalance correctly (e.g. `balance - activeStake - rentAmount`)

### PR DESCRIPTION
**Pull request by CriesofCarrots**
#### Problem
The RPC endpoint getStakeActivation only looks at the total stake balance for the deactivating and inactive cases. This means that if an active stake account receives a transfer, the amount is not reflected in the "inactive" stake, which is confusing.

Originally here: https://github.com/solana-labs/solana/pull/35116

#### Summary of Changes
Deprecate this confusing RPC method
Evaluate inactive_stake to the total lamports balance minus effective stake and rent-exempt reserve for all activation cases.

Fixes https://github.com/solana-labs/solana/issues/35111

### CODE REVIEW

**Review by t-nelson — APPROVED** [review]
nice.

File: rpc/src/rpc.rs [hunk 1]
```diff
@@ -4091,7 +4063,43 @@ fn rpc_perf_sample_from_perf_sample(slot: u64, sample: PerfSample) -> RpcPerfSam
     }
 }
 
-// RPC methods deprecated in v1.8
+pub mod rpc_deprecated_v1_18 {
```
Comment (CriesofCarrots) [inline rpc/src/rpc.rs:4066]: I forgot I wrote this code before v1.18 was branched. Rather than edit all these 18s, I'm going to propose backporting to v1.18 -- this is very low risk and small in scope, and backporting will allow us to remove this method altogether in v2.

Comment (steveluscher) [reply rpc/src/rpc.rs:4066]: Should this also have been removed in #1886?

Comment (CriesofCarrots) [reply rpc/src/rpc.rs:4066]: @steveluscher I [included that at first](https://github.com/anza-xyz/agave/pull/1809#issue-2365198445), but realized we didn't deprecate the client methods in this PR. Still considering/hoping to remove in v2.0, but need to figure the best way to handle.
