### PR TITLE
bench: update vote bench ixs currently being deprecated

### LINKED ISSUE #4737: bench_process_vote and bench_process_vote_state_update fail on top of the tree.
#### Problem
Steps to repro

```
$ cargo +nightly bench --bench process_vote

failures:

---- bench_process_vote stdout ----

thread 'main' panicked at /home/sol/src/agave/program-runtime/src/invoke_context.rs:841:5:
assertion `left == right` failed
  left: Err(InvalidInstructionData)
 right: Ok(())
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- bench_process_vote_state_update stdout ----

thread 'main' panicked at /home/sol/src/agave/program-runtime/src/invoke_context.rs:841:5:
assertion `left == right` failed
  left: Err(InvalidInstructionData)
 right: Ok(())


failures:
    bench_process_vote
    bench_process_vote_state_update

```

### PR DESCRIPTION
**Pull request by AshwinSekar**
#### Problem
Legacy vote instructions are currently in the process of being rejected in the vote program.  https://github.com/anza-xyz/agave/issues/2597
Bench runs with all features enabled so legacy vote benches will fail. We should not break these benches until legacy votes are considered invalid on all clusters.

#### Summary of Changes
Deactivate the feature before running legacy vote benches.

Fixes #4737

### CODE REVIEW

**Review by ksolana — APPROVED** [review]

File: programs/vote/benches/process_vote.rs [hunk 1]
```diff
@@ -93,6 +95,31 @@ fn create_accounts() -> (Slot, SlotHashes, Vec<TransactionAccount>, Vec<AccountM
...
+                let mut deprecated_feature_set = FeatureSet::all_enabled();
+                deprecated_feature_set.deactivate(&deprecate_legacy_vote_ixs::id());
+                invoke_context.mock_set_feature_set(Arc::new(deprecated_feature_set));
+            },
+            |_invoke_context| {},
+        );
+    });
+}
+
 fn bench_process_vote_instruction(
```
Comment (tao-stones) [inline programs/vote/benches/process_vote.rs:123]: dumb question: do we still need this?
