### PR TITLE
fix: improve publish-crate.sh logging and rate limit handling

### LINKED ISSUE #11085: ci: solana-secondary publish-crates step does not respect rate limits
#### Problem
solana-secondary's publish-crates step [does not respect](https://buildkite.com/anza/agave-secondary/builds/3548#019cc490-39a2-43db-81d8-0d3e4a662edc/L603) crates-io's [rate-limits](https://crates.io/docs/rate-limits)

#### Proposed Solution
* resolve and honor published limits
* parse and respect back-off messages on failure
* add alerting so we can minimize future abuse

### LINKED ISSUE #11087: ci: solana-secondary publish-crates step logs difficult to follow
#### Problem
the solana-secondary publish-crates step's logs look like this
Image

1. the collapsed lines have all unique context truncated, leaving them apparently identical
1. this log actually moves so fast that if you try to expand the collapsed section, the ui updated almost immediately and closes it again. it's basically impossible to follow while running

#### Proposed Solution
i'm not really sure what the options are here
1. assuming we can `basename` the path off the docker script, but it might make more sense to emit a different message entirely
1. if we have sufficient control over the section collapse/expand only expanding the active section would be nice. we should at the very least bubble up error message to the root of the log

### PR DESCRIPTION
**Pull request by mircea-c**
#### Problem

Two issues with the `publish-crates` step on solana-secondary:

1. Buildkite section headers show the full `Cargo.toml` path rather than the crate name, making collapsed sections appear identical when truncated (#11087)
2. `set -x` floods the log with trace output, making it impossible to follow while running (#11087)
3. Retries use a flat 3s sleep with no awareness of crates.io rate limits. crates.io allows a burst of 30 new versions then 1 per minute; Agave publishes hundreds of crates per release so the burst is always exhausted (#11085)

#### Summary of Changes

- Use crate name instead of `Cargo.toml` path in Buildkite section headers
- Drop `set -x` from the publish subshell to reduce log noise
- Add a 60s inter-crate sleep to stay within the sustained rate limit
- Detect HTTP 429 responses via cargo's `Caused by: ... status 429` output and back off exponentially on retries instead of using a flat 3s delay
- Add `pipefail` so the `cargo publish | tee` pipeline correctly propagates failures

Fixes #11085
Fixes #11087

### CODE REVIEW

File: ci/publish-crate.sh [hunk 1]
```diff
@@ -62,7 +61,7 @@ for Cargo_toml in $Cargo_tomls; do
   fi
 
   (
-    set -x
+    set -eo pipefail
```
Comment (levsha) [inline ci/publish-crate.sh]:
```suggestion
    set -euo pipefail
```

Comment (levsha) [reply ci/publish-crate.sh]: This should just stay at the very beginning of the script.

Comment (mircea-c) [reply ci/publish-crate.sh]: OK, I moved it to the top. d8034c9

File: ci/publish-crate.sh [hunk 2]
```diff
@@ -72,18 +69,32 @@ for Cargo_toml in $Cargo_tomls; do
       echo "Attempt ${i} of ${numRetries}"
       # The rocksdb package does not build with the stock rust docker image so use
       # the solana rust docker image
-      if ci/docker-run-default-image.sh bash -exc "cd $crate; $cargoCommand"; then
+      output=$(mktemp)
```
Comment (t-nelson) [inline ci/publish-crate.sh]:
```suggestion
      output="$(ci/docker-run-default-image.sh bash -exc "cd $crate; $cargoCommand" 2>&1 | tee /dev/fd/2)"
```

i think we can avoid the temp file with something like this

File: ci/publish-crate.sh [hunk 3]
```diff
@@ -72,18 +69,32 @@ for Cargo_toml in $Cargo_tomls; do
...
 
       if [ "$i" -lt "$numRetries" ]; then
-        sleep 3
+        if grep -qiE "status 429|429 Too Many Requests" "$output"; then
+          backoff=$((60 * i))
+          echo "Rate limited by crates.io, backing off for ${backoff}s"
+          sleep "$backoff"
+        else
+          sleep 3
+        fi
```
Comment (t-nelson) [inline ci/publish-crate.sh]:
```suggestion
        until="$(until=$(sed -e 's/.*429.*Please try again after \(.*\) and see.*/\1/' <<<"$output")"
        if [[ -n "$until" ]]; then
          until="$(date +%s --date-"$until")"
          now="$(date +%s)"
          backoff=$((until - now))
          if [[ $backoff -gt 0 ]]; then
            sleep "$backoff"
          fi
        else
          sleep 3
        fi
```

this will sleep the exact backoff time from the error message

File: ci/publish-crate.sh [hunk 4]
```diff
@@ -38,7 +38,8 @@ done
 Cargo_tomls=$(ci/order-crates-for-publishing.py)
 
 for Cargo_toml in $Cargo_tomls; do
-  echo "--- $Cargo_toml"
+  crate_name=$(grep -m 1 '^name = ' "$Cargo_toml" | cut -f 3 -d ' ' | tr -d \")
```
Comment (t-nelson) [inline ci/publish-crate.sh:41]: is it time to put `cargo install toml-cli` in the ci images? then this becomes...
```sh
toml get -r "$Cargo_toml" package.name
```

Comment (t-nelson) [reply ci/publish-crate.sh:41]: tho i think the worst offender is the path to the docker runner. assuming there's something stupid in there like `echo "--- $0"`

Comment (t-nelson) [reply ci/publish-crate.sh:41]: fuckin' nailed it
https://github.com/anza-xyz/agave/blob/92d55b2c9cc70311ef61fba2ae4837eeb700f1f1/ci/docker-run.sh#L52-L54

Comment (mircea-c) [reply ci/publish-crate.sh:41]: docker-run.sh emits echo "--- $0" and causing the duplicate collapsed sections. Should we start there by removing that?

File: ci/publish-crate.sh (hunk 2 above)
Comment (mircea-c) [reply ci/publish-crate.sh]: OK, done in 079f714

File: ci/publish-crate.sh (hunk 3 above)
Comment (mircea-c) [reply ci/publish-crate.sh]: Sounds good. Made a couple of changes. `until` is a bash keyword so replaced that and put in more one liners to keep the bash mystique intact. See 079f714

File: ci/publish-crate.sh (hunk 4 above)
Comment (mircea-c) [reply ci/publish-crate.sh:41]: Right, I commented before refresh and didn't see your find. I don't want to make the change in this PR, but I can open a new one for that.

**Comment by t-nelson** [comment]
did you test the changes with a dry run?

**Comment by mircea-c** [comment]
> did you test the changes with a dry run?

I have not, cuz it's a ton of work. I did sort of unit tests of the logic changes

File: ci/publish-crate.sh [hunk 5]
```diff
@@ -72,18 +69,28 @@ for Cargo_toml in $Cargo_tomls; do
...
       else
         echo "couldn't publish '$crate_name'"
         exit 1
       fi
     done
   )
+
+  # crates.io allows a burst of 30 new versions, then 1 per minute.
+  # Sleep between each crate to stay within the sustained rate limit.
+  sleep 60
```
Comment (yihau) [inline ci/publish-crate.sh]: do we really need this? the manual sleep feels a bit too strict to me.

https://crates.io/docs/rate-limits

> ... omit ...
> 
> Concretely, the rate limits for crates.io are:
> 
> For brand new crate publishes, allow a burst of 5 new crates published at once by a single user account, with a rate limit of 1 crate every 10 minutes allowed after that burst
> For new versions of existing crates, allow a burst of 30 new versions published at once by a single user account, with a rate limit of 1 crate per minute allowed after that burst
> 
> ... omit ...

we already have a retry mechanism and each crates take ~1m to build.  this should naturally respect the rate limit. also we have ~133 crates to publish, with this change, this will likely add at least 2h to the total job time.

Comment (mircea-c) [reply ci/publish-crate.sh]: @t-nelson :point_up: 

I haven't actually checked if the existing retry works. Trusting the issue creator on this one :grin:

Comment (t-nelson) [reply ci/publish-crate.sh]: if we want to do a manual sleep i think we should time the publish and sleep `60-publish_time`. also count successful publications and fully consume the burst capacity

Comment (t-nelson) [reply ci/publish-crate.sh]: > this will likely add at least 2h to the total job time

i think it's already 2hrs 'cause we get bounced off the rate limiter for 100 of them :joy:

Comment (yihau) [reply ci/publish-crate.sh]: oh, I mean I guess it will add an extra 2hrs. spent some time to analyze the logs and got some concrete numbers (https://buildkite.com/anza/agave-secondary/builds/3584#019cd6ba-eed5-41c8-88bf-422b15b5b686)

tl;dr:

1. it looks like the rate limit is accurate. we start getting 429 from our 30th crate.
2. with this sleep, the total job time would increase ~ 1h. ( from ~5840s (97 min) to ~9593s (159 min) )


<details>

<summary>the table (click me)</summary>

| Time range | Crate | Total time | Compile time | 429 hits | Elapsed time | Publish order | Sleep simulate |
| --- | --- | --- | --- | ---: | --- | --- | --- |
| 07:59:21.563Z ~ 07:59:48.018Z | account-decoder-client-types | 26.455s | 17.38s | 0 | 26.455s | 1 | 0s + 17.38s + 60s |
| 07:59:48.018Z ~ 08:00:13.300Z | logger | 25.282s | 17.31s | 0 | 51.737s | 2 | 77.38s + 17.31s + 60s |
| 08:00:13.300Z ~ 08:00:44.971Z | remote-wallet | 31.671s | 24.54s | 0 | 83.408s | 3 | 154.69s + 24.54s + 60s |
| 08:00:44.972Z ~ 08:01:02.293Z | measure | 17.321s | 10.18s | 0 | 100.729s | 4 | 239.23s + 10.18s + 60s |
| 08:01:02.293Z ~ 08:01:34.293Z | metrics | 32.000s | 25.37s | 0 | 132.729s | 5 | 309.41s + 25.37s + 60s |
| 08:01:34.293Z ~ 08:01:57.549Z | svm-type-overrides | 23.256s | 16.59s | 0 | 155.985s | 6 | 394.78s + 16.59s + 60s |
| 08:01:57.549Z ~ 08:02:26.401Z | transaction-context | 28.852s | 20.61s | 0 | 184.837s | 7 | 471.37s + 20.61s + 60s |
| 08:02:26.401Z ~ 08:02:43.387Z | svm-feature-set | 16.986s | 10.30s | 0 | 201.823s | 8 | 551.98s + 10.30s + 60s |
| 08:02:43.387Z ~ 08:03:06.691Z | svm-transaction | 23.304s | 16.40s | 0 | 225.127s | 9 | 622.28s + 16.40s + 60s |
| 08:03:06.691Z ~ 08:03:29.562Z | svm-callback | 22.871s | 15.36s | 0 | 247.998s | 10 | 698.68s + 15.36s + 60s |
| 08:03:29.563Z ~ 08:03:53.636Z | svm-log-collector | 24.073s | 16.31s | 0 | 272.071s | 11 | 774.04s + 16.31s + 60s |
| 08:03:53.637Z ~ 08:04:10.543Z | svm-measure | 16.906s | 9.91s | 0 | 288.977s | 12 | 850.35s + 9.91s + 60s |
| 08:04:10.543Z ~ 08:04:34.389Z | svm-timings | 23.846s | 18.08s | 0 | 312.823s | 13 | 920.26s + 18.08s + 60s |
| 08:04:34.390Z ~ 08:04:57.908Z | random | 23.518s | 15.69s | 0 | 336.341s | 14 | 998.34s + 15.69s + 60s |
| 08:04:57.909Z ~ 08:05:26.698Z | tls-utils | 28.789s | 21.36s | 0 | 365.130s | 15 | 1074.03s + 21.36s + 60s |
| 08:05:26.699Z ~ 08:05:54.002Z | bloom | 27.303s | 19.23s | 0 | 392.433s | 16 | 1155.39s + 19.23s + 60s |
| 08:05:54.002Z ~ 08:06:18.216Z | merkle-tree | 24.214s | 16.00s | 0 | 416.647s | 17 | 1234.62s + 16.00s + 60s |
| 08:06:18.216Z ~ 08:06:41.907Z | bls12-381 | 23.691s | 18.07s | 0 | 440.338s | 18 | 1310.62s + 18.07s + 60s |
| 08:06:41.908Z ~ 08:07:05.276Z | io-uring | 23.368s | 15.73s | 0 | 463.706s | 19 | 1388.69s + 15.73s + 60s |
| 08:07:05.277Z ~ 08:07:29.579Z | lattice-hash | 24.302s | 16.65s | 0 | 488.008s | 20 | 1464.42s + 16.65s + 60s |
| 08:07:29.580Z ~ 08:07:53.111Z | rayon-threadlimit | 23.531s | 15.59s | 0 | 511.539s | 21 | 1541.07s + 15.59s + 60s |
| 08:07:53.112Z ~ 08:08:18.149Z | program-binaries | 25.037s | 18.16s | 0 | 536.576s | 22 | 1616.66s + 18.16s + 60s |
| 08:08:18.149Z ~ 08:08:34.742Z | scheduler-bindings | 16.593s | 9.85s | 0 | 553.169s | 23 | 1694.82s + 9.85s + 60s |
| 08:08:34.742Z ~ 08:09:02.106Z | xdp-ebpf | 27.364s | 21.65s | 0 | 580.533s | 24 | 1764.67s + 21.65s + 60s |
| 08:09:02.107Z ~ 08:09:26.163Z | notifier | 24.056s | 16.62s | 0 | 604.589s | 25 | 1846.32s + 16.62s + 60s |
| 08:09:26.163Z ~ 08:09:26.172Z | platform-tools-sdk-gen-headers | 0.009s | - | 0 | 604.598s | publish = false |  |
| 08:09:26.172Z ~ 08:09:26.179Z | rbpf-cli | 0.007s | - | 0 | 604.605s | publish = false |  |
| 08:09:26.179Z ~ 08:09:26.185Z | storage-bigtable-build-proto | 0.006s | - | 0 | 604.611s | publish = false |  |
| 08:09:26.185Z ~ 08:09:26.190Z | syscalls-gen-syscall-list | 0.005s | - | 0 | 604.616s | publish = false |  |
| 08:09:26.190Z ~ 08:09:57.947Z | account-decoder | 31.757s | 23.64s | 0 | 636.373s | 26 | 1922.94s + 23.64s + 60s |
| 08:09:57.947Z ~ 08:10:31.085Z | clap-utils | 33.138s | 26.14s | 0 | 669.511s | 27 | 2006.58s + 26.14s + 60s |
| 08:10:31.085Z ~ 08:10:58.889Z | net-utils | 27.804s | 21.12s | 0 | 697.315s | 28 | 2092.72s + 21.12s + 60s |
| 08:10:58.890Z ~ 08:11:22.631Z | transaction-status-client-types | 23.741s | 17.76s | 0 | 721.056s | 29 | 2173.84s + 17.76s + 60s |
| 08:11:22.631Z ~ 08:11:46.944Z | feature-set | 24.313s | 17.11s | 0 | 745.369s | 30 | 2251.60s + 17.11s + 60s |
| 08:11:46.944Z ~ 08:13:04.038Z | vote | 77.094s | 21.51s + 16.57s + 17.53s | 2 | 822.463s | 31 | 2328.71s + 21.51s + 60s |
| 08:13:04.038Z ~ 08:13:57.032Z | program-runtime | 52.994s | 19.87s + 17.08s | 1 | 875.457s | 32 | 2410.22s + 19.87s + 60s |
| 08:13:57.033Z ~ 08:14:44.619Z | transaction-view | 47.586s | 16.68s + 16.99s | 1 | 923.043s | 33 | 2490.09s + 16.68s + 60s |
| 08:14:44.619Z ~ 08:15:56.830Z | fs | 72.211s | 15.82s + 17.24s + 16.51s | 2 | 995.254s | 34 | 2566.77s + 15.82s + 60s |
| 08:15:56.830Z ~ 08:16:46.542Z | bucket_map | 49.712s | 17.54s + 17.50s | 1 | 1044.966s | 35 | 2642.59s + 17.54s + 60s |
| 08:16:46.542Z ~ 08:17:57.841Z | xdp | 71.299s | 18.56s + 16.13s + 16.80s | 2 | 1116.265s | 36 | 2720.13s + 18.56s + 60s |
| 08:17:57.841Z ~ 08:18:50.585Z | banks-interface | 52.744s | 20.36s + 17.51s | 1 | 1169.009s | 37 | 2798.69s + 20.36s + 60s |
| 08:18:50.585Z ~ 08:19:41.850Z | clap-v3-utils | 51.265s | 18.95s + 16.66s | 1 | 1220.274s | 38 | 2879.05s + 18.95s + 60s |
| 08:19:41.851Z ~ 08:20:53.712Z | cli-config | 71.861s | 19.43s + 15.97s + 14.84s | 2 | 1292.135s | 39 | 2958.00s + 19.43s + 60s |
| 08:20:53.713Z ~ 08:21:42.795Z | connection-cache | 49.082s | 21.84s + 15.07s | 1 | 1341.217s | 40 | 3037.43s + 21.84s + 60s |
| 08:21:42.795Z ~ 08:22:46.575Z | version | 63.780s | 15.72s + 14.73s + 14.67s | 2 | 1404.997s | 41 | 3119.27s + 15.72s + 60s |
| 08:22:46.575Z ~ 08:23:51.455Z | compute-budget | 64.880s | 15.67s + 14.74s + 14.71s | 2 | 1469.877s | 42 | 3194.99s + 15.67s + 60s |
| 08:23:51.456Z ~ 08:25:02.166Z | votor-messages | 70.710s | 20.74s + 14.97s + 14.84s | 2 | 1540.587s | 43 | 3270.66s + 20.74s + 60s |
| 08:25:02.166Z ~ 08:25:54.426Z | syscalls | 52.260s | 25.02s + 14.73s | 1 | 1592.847s | 44 | 3351.40s + 25.02s + 60s |
| 08:25:54.427Z ~ 08:26:58.830Z | programs-compute-budget | 64.403s | 14.09s + 14.71s + 14.58s | 2 | 1657.250s | 45 | 3436.42s + 14.09s + 60s |
| 08:26:58.830Z ~ 08:27:41.788Z | reserved-account-keys | 42.958s | 14.94s + 14.73s | 1 | 1700.208s | 46 | 3510.51s + 14.94s + 60s |
| 08:27:41.789Z ~ 08:28:46.192Z | leader-schedule | 64.403s | 15.30s + 14.71s + 14.80s | 2 | 1764.611s | 47 | 3585.45s + 15.30s + 60s |
| 08:28:46.192Z ~ 08:29:48.120Z | precompiles | 61.928s | 32.03s + 18.10s | 1 | 1826.539s | 48 | 3660.75s + 32.03s + 60s |
| 08:29:48.120Z ~ 08:30:55.461Z | programs-zk-elgamal-proof | 67.341s | 17.42s + 14.57s + 14.77s | 2 | 1893.880s | 49 | 3752.78s + 17.42s + 60s |
| 08:30:55.462Z ~ 08:31:59.891Z | programs-zk-token-proof | 64.429s | 14.22s + 14.59s + 14.77s | 2 | 1958.309s | 50 | 3830.20s + 14.22s + 60s |
| 08:31:59.891Z ~ 08:32:42.770Z | fee | 42.879s | 15.60s + 14.80s | 1 | 2001.188s | 51 | 3904.42s + 15.60s + 60s |
| 08:32:42.771Z ~ 08:33:47.297Z | scheduling-utils | 64.526s | 15.12s + 14.67s + 14.74s | 2 | 2065.714s | 52 | 3980.02s + 15.12s + 60s |
| 08:33:47.297Z ~ 08:33:47.305Z | svm-test-harness-fixture | 0.008s | - | 0 | 2065.722s | publish = false |  |
| 08:33:47.305Z ~ 08:34:54.974Z | rpc-client-types | 67.669s | 18.21s + 15.09s + 15.12s | 2 | 2133.391s | 53 | 4055.14s + 18.21s + 60s |
| 08:34:54.974Z ~ 08:35:59.591Z | programs-system | 64.617s | 16.29s + 14.40s + 14.58s | 2 | 2198.008s | 54 | 4133.35s + 16.29s + 60s |
| 08:35:59.591Z ~ 08:36:42.805Z | programs-bpf_loader | 43.214s | 15.30s + 14.90s | 1 | 2241.222s | 55 | 4209.64s + 15.30s + 60s |
| 08:36:42.805Z ~ 08:37:47.013Z | bls-cert-verify | 64.208s | 15.13s + 14.71s + 14.63s | 2 | 2305.430s | 56 | 4284.94s + 15.13s + 60s |
| 08:37:47.013Z ~ 08:38:55.002Z | transaction-status | 67.989s | 19.19s + 14.94s + 14.74s | 2 | 2373.419s | 57 | 4360.07s + 19.19s + 60s |
| 08:38:55.003Z ~ 08:38:55.010Z | accounts-db-store-histogram | 0.007s | - | 0 | 2373.426s | publish = false |  |
| 08:38:55.010Z ~ 08:40:02.619Z | keygen | 67.609s | 18.91s + 15.37s + 15.53s | 2 | 2441.035s | 58 | 4439.26s + 18.91s + 60s |
| 08:40:02.620Z ~ 08:40:48.602Z | pubsub-client | 45.982s | 18.57s + 15.04s | 1 | 2487.017s | 59 | 4518.17s + 18.57s + 60s |
| 08:40:48.603Z ~ 08:41:59.333Z | rpc-client-api | 70.730s | 19.96s + 15.31s + 14.93s | 2 | 2557.747s | 60 | 4596.74s + 19.96s + 60s |
| 08:41:59.333Z ~ 08:42:45.105Z | programs-vote | 45.772s | 17.16s + 14.75s | 1 | 2603.519s | 61 | 4676.70s + 17.16s + 60s |
| 08:42:45.105Z ~ 08:43:49.703Z | programs-loader-v4 | 64.598s | 15.13s + 14.74s + 14.82s | 2 | 2668.117s | 62 | 4753.86s + 15.13s + 60s |
| 08:43:49.703Z ~ 08:44:54.414Z | storage-proto | 64.711s | 35.51s + 15.47s | 1 | 2732.828s | 63 | 4828.99s + 35.51s + 60s |
| 08:44:54.414Z ~ 08:46:01.728Z | geyser-plugin-interface | 67.314s | 18.07s + 14.82s + 14.84s | 2 | 2800.142s | 64 | 4924.50s + 18.07s + 60s |
| 08:46:01.728Z ~ 08:46:51.236Z | perf | 49.508s | 21.63s + 15.28s | 1 | 2849.650s | 65 | 5002.57s + 21.63s + 60s |
| 08:46:51.236Z ~ 08:47:46.360Z | rpc-client | 55.124s | 28.42s + 16.22s | 1 | 2904.774s | 66 | 5084.20s + 28.42s + 60s |
| 08:47:46.361Z ~ 08:48:56.922Z | builtins-default-costs | 70.561s | 21.30s + 14.97s + 14.91s | 2 | 2975.335s | 67 | 5172.62s + 21.30s + 60s |
| 08:48:56.922Z ~ 08:49:43.148Z | svm | 46.226s | 19.32s + 14.60s | 1 | 3021.561s | 68 | 5253.92s + 19.32s + 60s |
| 08:49:43.149Z ~ 08:50:54.303Z | cli-output | 71.154s | 21.49s + 15.23s + 14.92s | 2 | 3092.715s | 69 | 5333.24s + 21.49s + 60s |
| 08:50:54.304Z ~ 08:52:02.108Z | storage-bigtable | 67.804s | 37.37s + 16.10s | 1 | 3160.519s | 70 | 5414.73s + 37.37s + 60s |
| 08:52:02.109Z ~ 08:52:53.439Z | builtins | 51.330s | 23.82s + 14.98s | 1 | 3211.849s | 71 | 5512.10s + 23.82s + 60s |
| 08:53:58.118Z ~ 08:54:47.524Z | rpc-client-nonce-utils | 49.406s | 19.85s + 14.98s | 1 | 3261.255s | 72 | 5595.92s + 19.85s + 60s |
| 08:54:47.525Z ~ 08:55:42.546Z | tpu-client | 55.021s | 27.75s + 15.52s | 1 | 3316.276s | 73 | 5675.77s + 27.75s + 60s |
| 08:55:42.546Z ~ 08:56:56.042Z | compute-budget-instruction | 73.496s | 25.47s + 15.02s + 14.91s | 2 | 3389.772s | 74 | 5763.52s + 25.47s + 60s |
| 08:56:56.043Z ~ 08:57:45.810Z | accounts-db | 49.767s | 21.03s + 14.89s | 1 | 3439.539s | 75 | 5848.99s + 21.03s + 60s |
| 08:57:45.810Z ~ 08:59:05.833Z | faucet | 80.023s | 22.49s + 15.14s + 18.44s | 2 | 3519.562s | 76 | 5930.02s + 22.49s + 60s |
| 08:59:05.833Z ~ 08:59:55.216Z | banking-stage-ingress-types | 49.383s | 15.46s + 18.58s | 1 | 3568.945s | 77 | 6012.51s + 15.46s + 60s |
| 08:59:55.216Z ~ 09:01:00.492Z | install | 65.276s | 32.23s + 19.29s | 1 | 3634.221s | 78 | 6087.97s + 32.23s + 60s |
| 09:01:00.492Z ~ 09:01:00.502Z | svm-test-harness-instr | 0.010s | - | 0 | 3634.231s | publish = false |  |
| 09:01:00.502Z ~ 09:02:02.768Z | watchtower | 62.266s | 28.97s + 19.21s | 1 | 3696.497s | 79 | 6180.20s + 28.97s + 60s |
| 09:02:02.769Z ~ 09:03:00.824Z | streamer | 58.055s | 25.38s + 18.24s | 1 | 3754.552s | 80 | 6269.17s + 25.38s + 60s |
| 09:03:00.824Z ~ 09:03:52.987Z | runtime-transaction | 52.163s | 20.27s + 17.62s | 1 | 3806.715s | 81 | 6354.55s + 20.27s + 60s |
| 09:03:52.988Z ~ 09:04:50.649Z | snapshots | 57.661s | 25.90s + 18.15s | 1 | 3864.376s | 82 | 6434.82s + 25.90s + 60s |
| 09:04:50.650Z ~ 09:05:47.292Z | faucet-cli | 56.642s | 25.51s + 19.32s | 1 | 3921.018s | 83 | 6520.72s + 25.51s + 60s |
| 09:05:47.292Z ~ 09:05:47.300Z | programs-compute-budget-bench | 0.008s | - | 0 | 3921.026s | publish = false |  |
| 09:05:47.300Z ~ 09:05:47.305Z | svm-test-harness | 0.005s | - | 0 | 3921.031s | publish = false |  |
| 09:05:47.305Z ~ 09:06:42.645Z | quic-client | 55.340s | 25.33s + 17.81s | 1 | 3976.371s | 84 | 6606.23s + 25.33s + 60s |
| 09:06:42.645Z ~ 09:07:59.220Z | udp-client | 76.575s | 19.11s + 17.28s + 17.87s | 2 | 4052.946s | 85 | 6691.56s + 19.11s + 60s |
| 09:07:59.221Z ~ 09:09:00.645Z | entry | 61.424s | 28.83s + 18.06s | 1 | 4114.370s | 86 | 6770.67s + 28.83s + 60s |
| 09:09:00.645Z ~ 09:09:57.594Z | cost-model | 56.949s | 24.37s + 18.22s | 1 | 4171.319s | 87 | 6859.50s + 24.37s + 60s |
| 09:09:57.595Z ~ 09:10:56.821Z | tpu-client-next | 59.226s | 26.82s + 18.64s | 1 | 4230.545s | 88 | 6943.87s + 26.82s + 60s |
| 09:10:56.822Z ~ 09:11:45.269Z | unified-scheduler-logic | 48.447s | 16.21s + 16.96s | 1 | 4278.992s | 89 | 7030.69s + 16.21s + 60s |
| 09:11:45.269Z ~ 09:11:45.278Z | bench-streamer | 0.009s | - | 0 | 4279.001s | publish = false |  |
| 09:11:45.278Z ~ 09:12:43.765Z | client | 58.487s | 24.87s + 20.09s | 1 | 4337.488s | 90 | 7106.90s + 24.87s + 60s |
| 09:12:43.766Z ~ 09:13:52.641Z | runtime | 68.875s | 35.40s + 18.92s | 1 | 4406.363s | 91 | 7191.77s + 35.40s + 60s |
| 09:13:52.642Z ~ 09:13:52.650Z | poh-bench | 0.008s | - | 0 | 4406.371s | publish = false |  |
| 09:13:52.650Z ~ 09:14:57.976Z | download-utils | 65.326s | 31.18s + 19.55s | 1 | 4471.697s | 92 | 7287.17s + 31.18s + 60s |
| 09:14:57.976Z ~ 09:16:01.886Z | send-transaction-service | 63.910s | 32.19s + 18.97s | 1 | 4535.607s | 93 | 7378.35s + 32.19s + 60s |
| 09:16:01.886Z ~ 09:16:59.006Z | tps-client | 57.120s | 25.16s + 17.82s | 1 | 4592.727s | 94 | 7470.54s + 25.16s + 60s |
| 09:16:59.006Z ~ 09:17:58.684Z | stake-accounts | 59.678s | 27.49s + 19.80s | 1 | 4652.405s | 95 | 7555.70s + 27.49s + 60s |
| 09:17:58.684Z ~ 09:19:01.964Z | genesis-utils | 63.280s | 29.41s + 19.96s | 1 | 4715.685s | 96 | 7643.19s + 29.41s + 60s |
| 09:19:01.964Z ~ 09:19:45.045Z | banks-server | 43.081s | 35.73s | 0 | 4758.766s | 97 | 7732.60s + 35.73s + 60s |
| 09:19:45.046Z ~ 09:21:01.152Z | ledger | 76.106s | 66.00s | 0 | 4834.872s | 98 | 7828.33s + 66.00s + 60s |
| 09:21:01.152Z ~ 09:21:56.442Z | banks-client | 55.290s | 22.64s + 17.16s | 1 | 4890.162s | 99 | 7954.33s + 22.64s + 60s |
| 09:21:56.443Z ~ 09:22:46.185Z | gossip | 49.742s | 41.02s | 0 | 4939.904s | 100 | 8036.97s + 41.02s + 60s |
| 09:22:46.185Z ~ 09:23:47.743Z | poh | 61.558s | 24.27s + 18.08s | 1 | 5001.462s | 101 | 8137.99s + 24.27s + 60s |
| 09:23:47.743Z ~ 09:24:51.107Z | program-test | 63.364s | 30.92s + 18.46s | 1 | 5064.826s | 102 | 8222.26s + 30.92s + 60s |
| 09:24:51.107Z ~ 09:26:03.333Z | genesis | 72.226s | 37.11s + 22.18s | 1 | 5137.052s | 103 | 8313.18s + 37.11s + 60s |
| 09:26:03.334Z ~ 09:26:59.225Z | rpc | 55.891s | 46.97s | 0 | 5192.943s | 104 | 8410.29s + 46.97s + 60s |
| 09:26:59.225Z ~ 09:27:57.988Z | unified-scheduler-pool | 58.763s | 21.40s + 20.17s | 1 | 5251.706s | 105 | 8517.26s + 21.40s + 60s |
| 09:27:57.989Z ~ 09:28:45.659Z | gossip-cli | 47.670s | 40.17s | 0 | 5299.376s | 106 | 8598.66s + 40.17s + 60s |
| 09:28:45.660Z ~ 09:28:45.669Z | programs-bpf-loader-tests | 0.009s | - | 0 | 5299.385s | publish = false |  |
| 09:28:45.669Z ~ 09:28:45.674Z | programs-ed25519-tests | 0.005s | - | 0 | 5299.390s | publish = false |  |
| 09:28:45.674Z ~ 09:28:45.681Z | programs-zk-elgamal-proof-tests | 0.007s | - | 0 | 5299.397s | publish = false |  |
| 09:28:45.681Z ~ 09:29:47.332Z | votor | 61.651s | 25.42s + 18.73s | 1 | 5361.048s | 107 | 8698.83s + 25.42s + 60s |
| 09:29:47.333Z ~ 09:30:44.891Z | geyser-plugin-manager | 57.558s | 18.96s + 19.16s | 1 | 5418.606s | 108 | 8784.25s + 18.96s + 60s |
| 09:30:44.891Z ~ 09:31:43.154Z | turbine | 58.263s | 51.12s | 0 | 5476.869s | 109 | 8863.21s + 51.12s + 60s |
| 09:31:43.154Z ~ 09:33:04.419Z | core | 81.265s | 45.23s + 19.63s | 1 | 5558.134s | 110 | 8974.33s + 45.23s + 60s |
| 09:33:04.420Z ~ 09:34:11.514Z | local-cluster | 67.094s | 29.97s + 18.92s | 1 | 5625.228s | 111 | 9079.56s + 29.97s + 60s |
| 09:34:11.515Z ~ 09:35:25.231Z | test-validator | 73.716s | 64.00s | 0 | 5698.944s | 112 | 9169.53s + 64.00s + 60s |
| 09:35:25.232Z ~ 09:35:25.239Z | accounts-cluster-bench | 0.007s | - | 0 | 5698.951s | publish = false |  |
| 09:35:25.239Z ~ 09:36:08.986Z | cli | 43.747s | 38.01s | 0 | 5742.698s | 113 | 9293.53s + 38.01s + 60s |
| 09:36:08.987Z ~ 09:36:08.993Z | client-test | 0.006s | - | 0 | 5742.704s | publish = false |  |
| 09:36:08.993Z ~ 09:36:09.000Z | rpc-test | 0.007s | - | 0 | 5742.711s | publish = false |  |
| 09:36:09.000Z ~ 09:36:51.001Z | tokens | 42.001s | 33.68s | 0 | 5784.712s | 114 | 9391.54s + 33.68s + 60s |
| 09:36:51.002Z ~ 09:37:46.459Z | validator | 55.457s | 47.61s | 0 | 5840.169s | 115 | 9485.22s + 47.61s + 60s = 9592.83s |

</details>

Comment (mircea-c) [reply ci/publish-crate.sh]: OK, the sleep is dropped. It now sleeps after getting a 429. 48e39be

Comment (t-nelson) [reply ci/publish-crate.sh]: do we know why we start getting 429 after the 30th crate even though five crates are publish = false?

Comment (yihau) [reply ci/publish-crate.sh]: > do we know why we start getting 429 after the 30th crate even though five crates are publish = false?

oh, actually `publish = false` doesn't increase the count. so the 30th crate is the real 30th published crate, which matches their docs. (the first 30 crates can be published without issues) after that we start getting 429

**Review by yihau — APPROVED** [review]
relying on their error messages feels a bit fragile. they could change the behavior at any time without notice. but I'm okay to update it once it actually happens

**Comment by t-nelson** [comment]
> relying on their error messages feels a bit fragile. they could change the behavior at any time without notice. but I'm okay to update it once it actually happens

we could split testing for 429 and parsing out the back off until timestamp. then we can fallback and warn if the message format changes

**Comment by mircea-c** [comment]
> we could split testing for 429 and parsing out the back off until timestamp. then we can fallback and warn if the message format changes

Not sure what sleep duration would work well for the fallback

**Comment by t-nelson** [comment]
> Not sure what sleep duration would work well for the fallback

from chido's table, it looks like if we had the start time of the last successfully completed publication, `60 - (now - last)` would be pretty safe

---

in reality i don't think we're going to get much _faster_ than we are today. we're effectively using retry build time as an expensive and abusive sleep. we _can_ cut down on the abuse at least
