### PR TITLE
cli: Fixes snapshot paths

### LINKED ISSUE #1563: the incremental folder is not cleaned up and grows 1000% while the snap is made.
Hi Solan@s
While creating a new snap, incremental ones are not made. This is ok.
Depending on the validator configuration, the default creation of a snap is every 12k slots = around every 3 hours and lasts half an hour.

The problem is that while no incremental is created during this half hour that the snap creation lasts, the incremental folder starts to grow to more than 40GB in that half hour.
Then, after the snap is created and the first incremental for that snap is made, the size of the incremental folder becomes stable again until the creation of the next snap begins and the folder grows again over 40GB.

The solution would be that while the snap is being created and new incremental are not made, the incremental folder does not grow more than what it normally needs, around 10GB and not +40Gb.

Here are some results of the script I wrote to capture where the excess storage was. As you can see, it is normal for the snap folder to grow 100% when creating the other snap, but it is not normal for the incremental folder to grow 1000% during this moment too.

```
incremental folder Fri May 31 14:44:40 UTC 2024
44G	/mnt/soldisk/inc_snaps
40	/mnt/soldisk/inc_snaps/remote
incremental-snapshot-269025974-269051552-4oJEXWfXGjz6V2cSaLfHG8mQSL5dV4jUfXMmWErGqjvv.tar.zst  remote  snapshot
snap folder
143G	/mnt/soldiskb/snapsMB
snapshot-269025974-9u7puB8w97d9edf8UqBWgTZvFVrL15gD1MhryEwDgZtU.tar.zst  tmp-snapshot-archive-269051656-ZAPAjz  tmp-snapshot-archive-269051656.tar.zst
```
then after the snap is made

```
incremental folder Fri May 31 14:47:00 UTC 2024
4.3G	/mnt/soldisk/inc_snaps
40	/mnt/soldisk/inc_snaps/remote
incremental-snapshot-269051656-269055541-Hn6K8dam4wvT7166688dkriUDJiboQBsS9454ESjHbfQ.tar.zst  remote  snapshot
snap folder
73G	/mnt/soldiskb/snapsMB
snapshot-269051656-GLADZGajspVkjMvC9cJhnmExXgW34G1Ej8cCXAfk54cS.tar.zst
```
Solana Jito `v1.18.14`

Thanks

### PR DESCRIPTION
**Pull request by brooksprumo**
#### Problem

The CLI snapshot paths for the validator are wonky. This results in issues like #1563: if a validator wants to put the incremental snapshot *archives* into their own path, it'll also put the bank snapshots there too. This can be especially bad if the operator is trying to put only the incremental snapshot archives in a ram-backed file system.

There should be a way to intuitively and distinctly specify all three snapshot paths: bank snapshots, full snapshot archives, and incremental snapshot archives.

Example:
Operator sets `--snapshots snap --incremental-snapshot-archive-path incr`

Here's what currently happens vs what's expected:

| directory | expected | actual |
|--------|--------|--------|
| full snapshot archives | snap | snap |
| incremental snapshot archives | incr | incr | 
| bank snapshots | snap/snapshots | incr/snapshots |

#### Summary of Changes

* Add a CLI arg for the full snapshot archives dir
* Fix the logic such that all three snapshot paths are distinct
* Update the help text for --snapshots

Fixes #1563

### CODE REVIEW

File: ledger-tool/src/main.rs [hunk 1]
```diff
@@ -808,6 +808,7 @@ fn main() {
             Arg::with_name("snapshots")
                 .long("snapshots")
                 .alias("snapshot-archive-path")
+                .alias("full-snapshot-archive-path")
```
Comment (brooksprumo) [inline ledger-tool/src/main.rs:811]: In ledger-tool, we don't use the bank snapshots dir in the same way. This `--snapshots` CLI arg is used as the full snapshot archives dir, so adding an alias here gets us the same behavior as the validator.

File: validator/src/main.rs
Comment (brooksprumo) [inline validator/src/main.rs:1]: The old logic here was convoluted. Now, all three snapshot dirs follow the same pattern:

1. if arg present, use it, else here's the default
2. create the dir, if not already there; exit on error

This makes seeing the defaults much easier.

File: validator/src/cli.rs [hunk 2]
```diff
@@ -343,14 +343,24 @@ pub fn app<'a>(version: &'a str, default_args: &'a DefaultArgs) -> App<'a, 'a> {
...
                 .long_help(use_snapshot_archives_at_startup::cli::LONG_HELP),
         )
+        .arg(
+            Arg::with_name("full_snapshot_archive_path")
+                .long("full-snapshot-archive-path")
+                .value_name("DIR")
+                .takes_value(true)
+                .help(
+                    "Use DIR as full snapshot archives location \
+                     [default: --snapshots value]",
```
Comment (steviez) [inline validator/src/cli.rs:357]: If none of the args are set, `--snapshots` is `LEDGER_DIR/snapshots`. But, `--full-snapshot-archive-path` would actually be `LEDGER_DIR` without the extra `snapshots` subdirectory. So the default value listed here is technically incorrect right ?

Comment (brooksprumo) [reply validator/src/cli.rs:357]: Yes and no. Originally in this PR I did change the wording of the help text to say the default is `--ledger value`.

I ended up settling on the idea that `--snapshots` is really setting a "base" snapshots directory to be used by the three real snapshot paths: full snapshot archives, incremental snapshot archives, and bank snapshots.

The bank snapshots create the "snapshots" subdirectory inside of whatever `--snapshots` is. I personally find this confusing. And I also find the help text for `--snapshots` misleading. But, I didn't want to address both this here in this PR, so I've left that.

Since `--snapshots` sets a base path, that means if no args are set, the full/incremental archives paths *will* use the value from `--snapshots`. The code does the right thing, but the help text is wrong/misleading.

Comment (brooksprumo) [reply validator/src/cli.rs:357]: (And it's also bad that `ledger-tool` has a `--snapshots` arg, but it behaves differently...)

Comment (brooksprumo) [reply validator/src/cli.rs:357]: I could update the help text for `--snaphots` in this PR too. Would that be beneficial?

Something like:

> Use DIR as the base location for snapshots. A subdirectory named "snapshots" will be created. [default: --ledger value]

Comment (steviez) [reply validator/src/cli.rs:357]: > I ended up settling on the idea that --snapshots is really setting a "base" snapshots directory to be used by the three real snapshot paths: full snapshot archives, incremental snapshot archives, and bank snapshots.

Agreed, I also came to a similar conclusion running through the code again

> Something like:
>>Use DIR as the base location for snapshots. A subdirectory named "snapshots" will be created. [default: --ledger value]

I like it and I think it conveys the idea of this being a "base" directory

Comment (brooksprumo) [reply validator/src/cli.rs:357]: Ok. I've updated the help for `--snapshots` in https://github.com/anza-xyz/agave/pull/1631/commits/a7eec6f0c2aaca63e70e852da47708720b585f80.

**Review by steviez — APPROVED** [review]
