### PR TITLE
fix: genesis: feature-gated vote state

### LINKED ISSUE #9377: feature gate genesis vote account creation
#### Problem
We are unable to spin up clusters where the vote_state_v4 feature flag is not active (e.g. cluster_type == MainnetBeta)

To repro: `solana-test-validator --deactivate-feature Gx4XFcrVMt4HUvPzTpTSVkdDVgcDSjKhDN1RqRS6KDuZ` - no slots will be finalized.

We've seen similar reports from users running local clusters (e.g. fd / jito)

https://github.com/anza-xyz/agave/blob/9992b9ce6d693618828c3fe94e566112bcf92c4a/runtime/src/genesis_utils.rs#L351
https://github.com/anza-xyz/agave/blob/9992b9ce6d693618828c3fe94e566112bcf92c4a/runtime/src/genesis_utils.rs#L198

#### Proposed Solution
We should feature gate initial vote account creation to create v3 accounts if the feature is not active

### PR DESCRIPTION
**Pull request by buffalojoec**
#### Problem
As described in #9377, development clusters who deactivate the vote state v4 feature are stalling since the genesis config will create vote state v4 accounts anyway.

#### Summary of Changes
Changes the no-features variant (`create_genesis_config_with_leader_ex_no_features`) to first check the provided `initial_accounts` for the vote account, and default to vote state V3 if not provided. For the variant with all features enabled (`create_genesis_config_with_leader_ex`), use vote state V4.

Also removes the BLS pubkey arg from the no-features variant since it's unused.

Fixes #9377

### CODE REVIEW

File: runtime/src/genesis_utils.rs
Comment (buffalojoec) [inline runtime/src/genesis_utils.rs:1]: Here I dropped helpers that were sparingly used to avoid any confusion if someone was to activate/deactivate the vote state v4 feature, but they already were vended a vote account for their validator.

File: runtime/src/genesis_utils.rs [hunk 1]
```diff
@@ -430,17 +442,85 @@ pub fn create_genesis_config_with_leader_ex(
...
+        fee_rate_governor,
+        rent,
+        cluster_type,
+        initial_accounts,
+    )
+}
 
-    genesis_config
+#[allow(clippy::too_many_arguments)]
+pub fn create_genesis_config_with_leader_ex(
```
Comment (buffalojoec) [inline runtime/src/genesis_utils.rs]: Functionally equivalent to its original.

File: test-validator/src/lib.rs [hunk 2]
```diff
@@ -960,11 +959,14 @@ impl TestValidator {
...
-        let mut feature_set = FeatureSet::default().inactive().clone();
+        // Activate all features besides those explicitly deactivated.
+        let mut feature_set = FeatureSet::all_enabled();
         for feature in &config.deactivate_feature_set {
-            if feature_set.remove(feature) {
+            if feature_set.is_active(feature) {
+                feature_set.deactivate(feature);
                 info!("Feature for {feature:?} deactivated")
+            } else if feature_set.inactive().contains(feature) {
+                // Continue silently if the user provided a feature ID twice.
```
Comment (buffalojoec) [inline test-validator/src/lib.rs]: This is a small fix to repair a "not a warning" scenario that I noticed while implementing this fix.

File: runtime/src/genesis_utils.rs [hunk 3]
```diff
@@ -280,20 +280,9 @@ pub fn create_genesis_config_with_leader_with_mint_keypair(
     }
 }
 
-pub fn activate_all_features_alpenglow(genesis_config: &mut GenesisConfig) {
-    do_activate_all_features::<true>(genesis_config);
-}
-
 pub fn activate_all_features(genesis_config: &mut GenesisConfig) {
```
Comment (AshwinSekar) [inline runtime/src/genesis_utils.rs:310]: i do think we want to keep alpenglow out of this for now.
I see a lot of our testing code uses `activate_all_features`, and not sure if this is used elsewhere. I would hate for Alpenglow to be active while it's not complete and cause problems.

Comment (buffalojoec) [reply runtime/src/genesis_utils.rs:310]: Ok sure, added a commit for this but I renamed the function.

**Review by AshwinSekar — COMMENTED** [review]
LGTM, cc @t-nelson for approval since I believe we want to backport this to 3.1

**Comment by t-nelson** [comment]
can we get the feature set plumbing changes factored out of the first commit and i think the last two commits of ag slop dropped?

**Comment by buffalojoec** [comment]
> can we get the feature set plumbing changes factored out of the first commit and i think the last two commits of ag slop dropped?

Ok so you basically want just a simpler fix here for the sake of backport? I'll probably just rewrite the commits.

**Comment by buffalojoec** [comment]
> > can we get the feature set plumbing changes factored out of the first commit and i think the last two commits of ag slop dropped?
> 
> Ok so you basically want just a simpler fix here for the sake of backport? I'll probably just rewrite the commits.

@t-nelson I think this new commit will backport better, and avoids any unnecessary refactoring.

File: runtime/src/genesis_utils.rs [hunk 4]
```diff
@@ -419,15 +423,39 @@ pub fn create_genesis_config_with_leader_ex(
     fee_rate_governor: FeeRateGovernor,
     rent: Rent,
     cluster_type: ClusterType,
-    initial_accounts: Vec<(Pubkey, AccountSharedData)>,
+    mut initial_accounts: Vec<(Pubkey, AccountSharedData)>,
 ) -> GenesisConfig {
+    if cluster_type == ClusterType::Development {
```
Comment (t-nelson) [inline runtime/src/genesis_utils.rs]: this isn't really the dependency tho. we should
1) factor feature gate activation as early as possible
2) plumb the feature set to where it needs to be
3) select the correct account format based on the feature gate status

File: programs/vote/src/vote_state/mod.rs [hunk 5]
```diff
@@ -1066,8 +1066,7 @@ fn do_process_tower_sync(
     )
 }
 
-#[cfg(test)]
-pub fn create_account_with_authorized(
+pub fn create_v3_account_with_authorized(
```
Comment (t-nelson) [inline programs/vote/src/vote_state/mod.rs:1192]: this is what modules are for

File: runtime/src/genesis_utils.rs (hunk 4 above)
Comment (buffalojoec) [reply runtime/src/genesis_utils.rs]: This is precisely what my first PR was doing - maybe I misunderstood your request, but you said you wanted feature set plumbing factored out of the commit?

Comment (t-nelson) [reply runtime/src/genesis_utils.rs]: yeah I just wanted it in separate commits so it was actually reviewable

Comment (buffalojoec) [reply runtime/src/genesis_utils.rs]: Ok I pushed up commits as you requested.

File: runtime/src/genesis_utils.rs [hunk 6]
```diff
@@ -199,14 +199,32 @@ pub fn create_genesis_config_with_vote_accounts_and_cluster_type(
...
+                &node_pubkey,
+                &vote_pubkey,
+                &vote_pubkey,
+                bls_pubkey_compressed,
+                0,
+                *stake,
+            )
+        } else {
+            // Vote state v4 feature inactive. Create a v3 account.
+            if bls_pubkey_compressed.is_some() {
```
Comment (t-nelson) [inline runtime/src/genesis_utils.rs:214]: probably for a followup, but this can probably be enforced by clap. if not, it should at least be moved up to where cli args are initially resolved

**Review by t-nelson — APPROVED** [review]
much more reviewable, thanks!
