### PR TITLE
Checks if bank snapshot is loadable before fastbooting

### LINKED ISSUE #35367: Fastboot fails if the node crashes while archiving a full snapshot
#### Problem

If a node crashes will archiving a full snapshot, *and if it has created more (incremental) bank snapshots based on that full snapshot*, then fastboot will likely fail with an error message like:

```
incremental snapshot requires accounts hash and capitalization from the full snapshot it is based on
```

##### Problem Details

Here's an example based on an error message that @jstarry sent me, after he added the patch from https://github.com/solana-labs/solana/pull/35353:
```
[2024-02-29T01:51:48.833574440Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="solAcctHashVer" one=1i message="panicked at core/src/accounts_hash_verifier.rs:328:21:
   0: rust_begin_unwind
             at ./rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at ./rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: solana_core::accounts_hash_verifier::AccountsHashVerifier::process_accounts_package
    incremental snapshot requires accounts hash and capitalization from the full snapshot it is based on 
    package: AccountsPackage { kind: Snapshot(IncrementalSnapshot(251086076)), slot: 251099346, block_height: 231733000, .. } 
    accounts hashes: {251098305: (AccountsHash(BNauzhxdBL7ZjVdQYwA5sFX6U4ZFnX8x1z2faXhCx5vy), 570710273002510414)} 
    incremental accounts hashes: {251099045: (IncrementalAccountsHash(HTXWvmVKKHB8RYwHfjdgr1oX1rmchDQC6kuBH2jeAo18), 20095246361845682)} 
    full snapshot archives: [FullSnapshotArchiveInfo(SnapshotArchiveInfo { path: \"/mnt/snapshots/snapshot-251086076-7ZCZ8PiKRTxjgmaQTXKGaPoEYA688deZ4x8r6FHUS5qQ.tar.zst\", slot: 251086076, hash: SnapshotHash(7ZCZ8PiKRTxjgmaQTXKGaPoEYA688deZ4x8r6FHUS5qQ), archive_format: TarZstd }), FullSnapshotArchiveInfo(SnapshotArchiveInfo { path: \"/mnt/snapshots/snapshot-251073753-325bXiW6oATv8i6LezYPR2hNu4P3JtrCECQLZBiJ9J22.tar.zst\", slot: 251073753, hash: SnapshotHash(325bXiW6oATv8i6LezYPR2hNu4P3JtrCECQLZBiJ9J22), archive_format: TarZstd })] 
    bank snapshots: [BankSnapshotInfo { slot: 251099346, snapshot_type: Pre, snapshot_dir: \"/mnt/incremental-snapshots/snapshot/251099346\", snapshot_version: V1_2_0 }, BankSnapshotInfo { slot: 251099045, snapshot_type: Post, snapshot_dir: \"/mnt/incremental-snapshots/snapshot/251099045\", snapshot_version: V1_2_0 }]" location="core/src/accounts_hash_verifier.rs:328:21" version="1.17.22 (src:2c5aa387; feat:3580551090, client:JitoLabs)"
```

Here's an example for the error:
* SPS is in the middle of archiving a full snapshot (slot 251098305 in this case)
* AHV processes the next incremental snapshot successfully. So the bank snapshot for AHV is created. And its expected full snapshot slot is 251098305.
* Maybe a few more incremental bank snapshots are created too.
* The node crashes before the full snapshot finishes being archived
* At next startup, fastboot will grab the latest bank snapshot (slot 251099346), which will contain the account hashes for full snapshot at slot 251098305
* When ABS starts up, it is told what the last full snapshot archive's slot is, which is slot 251086076
* The first new snapshot request will get sent to ABS, and it'll be an incremental snapshot. ABS knows that the last full snapshot was for slot 251086076, so ABS packages up new snapshot with the old full snapshot slot and sends it over to AHV
* AHV sees the incremental snapshot request and so it says "You asked me to make an incremental snapshot, so I need to know about the full snapshot you were based on. Please tell me about the full snapshot slot and its accounts hash". The request will say it's full snapshot is 251086076, but AccountsDb will only know about 251098305.
* And then the panic is triggered.

<details><summary>More info</summary>
<p>

Here's more logs from Justin's machine. `

```
[2024-02-29T01:33:55.752948313Z INFO  solana_runtime::snapshot_bank_utils] Creating bank snapshot for slot 251098305, path: /mnt/incremental-snapshots/snapshot/251098305/251098305.pre
[2024-02-29T01:34:06.521515316Z INFO  solana_runtime::snapshot_bank_utils] bank serialize took 3.9s for slot 251098305 at /mnt/incremental-snapshots/snapshot/251098305/251098305.pre
[2024-02-29T01:34:06.522263848Z INFO  solana_runtime::snapshot_package] Package snapshot for bank 251098305 has 421257 account storage entries (snapshot kind: FullSnapshot)
[2024-02-29T01:34:06.522275888Z INFO  solana_runtime::accounts_background_service] Took bank snapshot. accounts package kind: Snapshot(FullSnapshot), slot: 251098305, bank hash: DrAkL3ceUCtYC5TEGx5orqkLn3FXiPQ5JxwWK8jgn1vT
[2024-02-29T01:34:06.859756460Z INFO  solana_core::accounts_hash_verifier] handling accounts package: AccountsPackage { kind: Snapshot(FullSnapshot), slot: 251098305, block_height: 231732000, .. }
[2024-02-29T01:34:51.320797198Z INFO  solana_runtime::snapshot_package] Package snapshot for bank 251098409 has 421253 account storage entries (snapshot kind: IncrementalSnapshot(251098305))
[2024-02-29T01:34:51.320814578Z INFO  solana_runtime::accounts_background_service] Took bank snapshot. accounts package kind: Snapshot(IncrementalSnapshot(251098305)), slot: 251098409, bank hash: 7RiJFiJqvkZ4YchCo7SxtdjrwN4F5zrKXz4Ngy5NwpUE
[2024-02-29T01:34:53.575408055Z INFO  solana_accounts_db::accounts_db] calculate_accounts_hash_from_storages: slot: 251098305, Full(AccountsHash(BNauzhxdBL7ZjVdQYwA5sFX6U4ZFnX8x1z2faXhCx5vy)), capitalization: 570710273002510414
[2024-02-29T01:35:06.154583143Z INFO  solana_metrics::metrics] datapoint: fastboot slot=251098305i num_storages_total=421257i num_storages_kept_alive=15i
[2024-02-29T01:35:06.154587592Z INFO  solana_core::accounts_hash_verifier] handling accounts package: AccountsPackage { kind: Snapshot(IncrementalSnapshot(251098305)), slot: 251098409, block_height: 231732100, .. }
[2024-02-29T01:35:06.233502620Z INFO  solana_core::snapshot_packager_service] handling snapshot package: SnapshotPackage { type: FullSnapshot, slot: 251098305, block_height: 231732000, .. }
[2024-02-29T01:35:06.233526780Z INFO  solana_runtime::snapshot_utils] Generating snapshot archive for slot 251098305
[2024-02-29T01:35:27.307496396Z INFO  solana_runtime::snapshot_package] Package snapshot for bank 251098509 has 421247 account storage entries (snapshot kind: IncrementalSnapshot(251098305))
[2024-02-29T01:35:27.307507596Z INFO  solana_runtime::accounts_background_service] Took bank snapshot. accounts package kind: Snapshot(IncrementalSnapshot(251098305)), slot: 251098509, bank hash: HggkzD851JtZK6JxpHuadqRayB5yUh1zU5Dn2ZKu7xLG
[2024-02-29T01:35:27.592021341Z INFO  solana_core::accounts_hash_verifier] handling accounts package: AccountsPackage { kind: Snapshot(IncrementalSnapshot(251098305)), slot: 251098509, block_height: 231732200, .. }
[2024-02-29T01:36:08.734285801Z INFO  solana_runtime::snapshot_package] Package snapshot for bank 251098613 has 421251 account storage entries (snapshot kind: IncrementalSnapshot(251098305))
[2024-02-29T01:36:08.734305441Z INFO  solana_runtime::accounts_background_service] Took bank snapshot. accounts package kind: Snapshot(IncrementalSnapshot(251098305)), slot: 251098613, bank hash: 3FRAp6Yn6EKibVTXDhEmVxsppvSSRFXP3PAZidj5UFgV
[2024-02-29T01:36:08.737970571Z INFO  solana_core::accounts_hash_verifier] handling accounts package: AccountsPackage { kind: Snapshot(IncrementalSnapshot(251098305)), slot: 251098613, block_height: 231732300, .. }
[2024-02-29T01:36:53.860137018Z INFO  solana_runtime::snapshot_package] Package snapshot for bank 251098713 has 421255 account storage entries (snapshot kind: IncrementalSnapshot(251098305))
[2024-02-29T01:36:53.860152468Z INFO  solana_runtime::accounts_background_service] Took bank snapshot. accounts package kind: Snapshot(IncrementalSnapshot(251098305)), slot: 251098713, bank hash: B5ciX3tdiSdAZVoHz6vQ2THRGdhuhfBiBPY7ZPjvR97p
```

In particular:

```
solana_core::snapshot_packager_service] handling snapshot package: SnapshotPackage { type: FullSnapshot, slot: 251098305, block_height: 231732000, .. }
solana_runtime::snapshot_utils] Generating snapshot archive for slot 251098305
```

This confirms that:
* The node was archiving a full snapshot for slot 251098305 when it crashed
* The node had created multiple incremental bank snapshots beyond slot 251098305

</p>
</details> 

#### Proposed Solution

Yikes! So we need some way to identify if the fastboot bank snapshot matches the actual full snapshot archives on disk or not. And if they don't, this bank snapshot should be purged.

Unfortunately, we cannot use older bank snapshots, because their account storage files have likely been recycled/shrunk. So we need to fallback on using a snapshot archive.
(Edit: [The recycler has now been removed](https://github.com/anza-xyz/agave/pull/118), so in theory we could use older bank snapshots. This needs testing first.)

Option 1:
When taking a snapshot, add a new file to indicate full vs incremental, and the important slots. Then, at load time, fastboot can see if it's an incremental, and what the base slot is. If there's not a full snapshot archive with the given slot, then we cannot use this snapshot. Delete it. 

If this process is done before we decide to fastboot or not, then it should correctly restart with a snapshot archive.

Option 2:
Similar to Option 1, we add the same new file to indicate the important slots. But instead, at load time, if there's not a full snapshot archive for the given slot, then we immediately generate a new full snapshot archive for the next snapshot request. This may have more code changes to handle. And may increase disk io. But does start up from a more-recent slot than Option 1. If there's another crash before the new full snapshot archive is made, we'll likely be in the same scenario.
(h/t to @apfitzge for this possible solution)

#### Work-arounds

There are some work-arounds available already, and they boil down to loading from a snapshot archive, instead of local state.

1. Use `--use-snapshot-archives-at-startup always`, to force loading from a snapshot archive
2. Delete the (non-archive) snapshots *directory* (often `ledger/snapshots/`), which is where the local state lives. By deleting this directory, startup will fallback to loading from a snapshot archive.

Now that https://github.com/solana-labs/solana/pull/35350 has merged, the problematic local state will be removed automatically. So a subsequent restart—without needing to do anything manually—should work.

### PR DESCRIPTION
**Pull request by brooksprumo**
#### Problem

Please refer to https://github.com/solana-labs/solana/issues/35367

#### Summary of Changes

Before loading a bank snapshot for fastboot, ensure it can be used! This means that if we do fastboot the bank snapshot, it has the correct other stuff on disk (aka the right full snapshot archive) so that *subsequent* snapshots will succeed, and we won't hit the error described in the problem.

Fixes https://github.com/solana-labs/solana/issues/35367

### CODE REVIEW

File: core/src/accounts_hash_verifier.rs [hunk 1]
```diff
@@ -303,6 +303,16 @@ impl AccountsHashVerifier {
...
+
+            // now write the fastboot file after reserializing so this bank snapshot is loadable
+            let fastboot_slot = match accounts_package.package_kind {
+                AccountsPackageKind::Snapshot(SnapshotKind::IncrementalSnapshot(base_slot)) => {
+                    base_slot
+                }
+                _ => accounts_package.slot,
+            };
+            snapshot_utils::write_fastboot_file(&snapshot_info.bank_snapshot_dir, fastboot_slot)
+                .unwrap();
```
Comment (jeffwashington) [inline core/src/accounts_hash_verifier.rs]: unwrap?

File: ledger/src/bank_forks_utils.rs [hunk 2]
```diff
@@ -294,11 +294,19 @@ fn bank_forks_from_snapshot(
         })?;
         bank
     } else {
-        let bank_snapshot =
-            latest_bank_snapshot.ok_or_else(|| BankForksUtilsError::NoBankSnapshotDirectory {
+        // fastboot from local state
+        let Some(bank_snapshot) = latest_bank_snapshot else {
+            // If we do *not* have a local snapshot to fastboot, then it must be because there was
+            // *not* a loadable local snapshot AND we shall *not* startup from a snapshot archive.
+            assert_eq!(
```
Comment (jeffwashington) [inline ledger/src/bank_forks_utils.rs]: what's going on here?

File: core/src/accounts_hash_verifier.rs (hunk 1 above)
Comment (brooksprumo) [reply core/src/accounts_hash_verifier.rs]: Oops, missed this one. Let me fix that.

File: ledger/src/bank_forks_utils.rs (hunk 2 above)
Comment (brooksprumo) [reply ledger/src/bank_forks_utils.rs]: Yep, a little hairy.

If we get inside this `else` of the `let-else`, then we are in a condition where (1) we're supposed to fastboot, and (2) there is no local state (i.e. a bank snapshot) to fastboot from. This should only happen if we've specified to *never* use a snapshot archive. So we assert that here. 

If instead we used either `when-newest` or `always` for when to load from snapshot archives, then we should not be in this `else` of the outer `if-else`. Instead we should've set `will_startup_from_snapshot_archives` to `true`, since `latest_bank_snapshot` would've been `None`.

File: core/src/accounts_hash_verifier.rs (hunk 1 above)
Comment (brooksprumo) [reply core/src/accounts_hash_verifier.rs]: Done. Fixed in https://github.com/anza-xyz/agave/pull/343/commits/3c2e77a884795bf96d115c46a8dcf76b85dc749f.

File: core/src/accounts_hash_verifier.rs [hunk 3]
```diff
@@ -303,6 +311,20 @@ impl AccountsHashVerifier {
                 &accounts_hash_for_reserialize,
                 bank_incremental_snapshot_persistence.as_ref(),
             );
+
+            // now write the fastboot file after reserializing so this bank snapshot is loadable
+            let fastboot_slot = match accounts_package.package_kind {
```
Comment (apfitzge) [inline core/src/accounts_hash_verifier.rs]: Could we rename this? It's more like "fastboot_most_recent_fullsnapshot_slot" or "fastboot_base_slot".

Same with the "fastboot_file". It seems like it should be "fastboot_base_slot_file".
Current naming made me think it contained the slot we were fastbooting from.

File: ledger/src/bank_forks_utils.rs (hunk 2 above)
Comment (apfitzge) [reply ledger/src/bank_forks_utils.rs]: I agree with Jeff here, it seems odd to me. We are basically assigning a bool, then having an assert we're assigning it correctly?

Line 250:
```rust
    let will_startup_from_snapshot_archives = match process_options.use_snapshot_archives_at_startup
    {
        UseSnapshotArchivesAtStartup::Always => true,
        UseSnapshotArchivesAtStartup::Never => false,
        UseSnapshotArchivesAtStartup::WhenNewest => latest_bank_snapshot
            .as_ref()
            .map(|bank_snapshot| latest_snapshot_archive_slot > bank_snapshot.slot)
            .unwrap_or(true),
    };
```

```rust
    let bank = if will_startup_from_snapshot_archives {
        // ...stuff
    } else {
            // fastboot from local state
            let Some(bank_snapshot) = latest_bank_snapshot else {
            // If we do *not* have a local snapshot to fastboot, then it must be because there was
            // *not* a loadable local snapshot AND we shall *not* startup from a snapshot archive.
            assert_eq!(
                process_options.use_snapshot_archives_at_startup,
                UseSnapshotArchivesAtStartup::Never,
            );
            return Err(BankForksUtilsError::NoBankSnapshotDirectory {
                flag: use_snapshot_archives_at_startup::cli::LONG_ARG.to_string(),
                value: UseSnapshotArchivesAtStartup::Never.to_string(),
            });
        };
    }
```

File: runtime/src/snapshot_utils.rs [hunk 4]
```diff
@@ -625,6 +627,64 @@ fn is_bank_snapshot_complete(bank_snapshot_dir: impl AsRef<Path>) -> bool {
     state_complete_path.is_file()
 }
 
+/// Writes the fastboot file into the bank snapshot dir
```
Comment (apfitzge) [inline runtime/src/snapshot_utils.rs]: see other comment about naming

File: ledger/src/bank_forks_utils.rs [hunk 5]
```diff
@@ -244,8 +244,8 @@ fn bank_forks_from_snapshot(
             .map(SnapshotArchiveInfoGetter::slot)
             .unwrap_or(0),
     );
-    let latest_bank_snapshot =
-        snapshot_utils::get_highest_bank_snapshot_post(&snapshot_config.bank_snapshots_dir);
+
+    let latest_bank_snapshot = snapshot_utils::get_highest_loadable_bank_snapshot(snapshot_config);
```
Comment (apfitzge) [inline ledger/src/bank_forks_utils.rs]: This strikes me as a bit odd as well, though not much different than previously.
We're reading & checking the bank snapshot even if we're `Always` using archives.

**Review by apfitzge — CHANGES_REQUESTED** [review]
I think it makes sense but some of the naming could be more explicit.

I think we might do a small refactor to make some of this more clear. We have this odd pattern where we are getting highest loadable snapshot, doing match on how we start up, then an if based on the result of the previous match.

Can we do something like this?
```rust
    let fastboot_snapshot = match process_options.use_snapshot_archives_at_startup {
        UseSnapshotArchivesAtStartup::Always => None,
        UseSnapshotArchivesAtStartup::Never => {
            let fastboot_snapshot =
                snapshot_utils::get_highest_loadable_bank_snapshot(snapshot_config);
            if fastboot_snapshot.is_none() {
                return Err(BankForksUtilsError::NoBankSnapshotDirectory {
                    flag: use_snapshot_archives_at_startup::cli::LONG_ARG.to_string(),
                    value: UseSnapshotArchivesAtStartup::Never.to_string(),
                });
            }
            fastboot_snapshot
        }
        UseSnapshotArchivesAtStartup::WhenNewest => {
            snapshot_utils::get_highest_loadable_bank_snapshot(snapshot_config)
                .filter(|bank_snapshot| bank_snapshot.slot >= latest_snapshot_archive_slot)
        }
    };

    if let Some(fastboot_snapshot) = fastboot_snapshot {
        // fast boot code
    } else {
        // slow boot code
    }
```
The `get_highest_loadable_bank_snapshot` call is in multiple places, but we treat it differently because the behavior is different for those cases.
The error handling is more upfront if we cannot find it for `Never` case, and don't have this (match, if, match) thing going on.
At least to me something like this is more clear, wdyt?

File: ledger/src/bank_forks_utils.rs (hunk 5 above)
Comment (apfitzge) [reply ledger/src/bank_forks_utils.rs]: Ended up making my review comment about this, so can just ignore this individual comment

File: ledger/src/bank_forks_utils.rs (hunk 2 above)
Comment (brooksprumo) [reply ledger/src/bank_forks_utils.rs]: Effectively yes 😅 The assert is there to ensure we don't refactor something and cause the returned error message to be wrong/misleading.

(I do like your suggestion here https://github.com/anza-xyz/agave/pull/343#pullrequestreview-1953497832 too, so likely will go in that direction.)

File: core/src/accounts_hash_verifier.rs (hunk 3 above)
Comment (brooksprumo) [reply core/src/accounts_hash_verifier.rs]: Good suggestion; will do.

**Comment by brooksprumo** [comment]
> I think we might do a small refactor to make some of this more clear. [..]
> Can we do something like this? [..]

Done! First https://github.com/anza-xyz/agave/pull/343/commits/ff1867c759982df7101d6bd60ee39a089e8f3400 swaps the `if-else` block (to make the next diff easier). And second, https://github.com/anza-xyz/agave/pull/343/commits/8b80597650d396fba44461d6eba1ec5418abb187 does the refactor.

File: core/src/accounts_hash_verifier.rs (hunk 3 above)
Comment (brooksprumo) [reply core/src/accounts_hash_verifier.rs]: For the fastboot file, do you want the function renamed, the comment reworded, or the file itself renamed?

Comment (brooksprumo) [reply core/src/accounts_hash_verifier.rs]: Renaming `fastboot_slot` has been fixed in https://github.com/anza-xyz/agave/pull/343/commits/2e351f3a806c69343a0f380c579a1dde375a3624.

File: core/src/accounts_hash_verifier.rs [hunk 6]
```diff
@@ -71,12 +72,17 @@ impl AccountsHashVerifier {
...
-                    let (_, handling_time_us) = measure_us!(Self::process_accounts_package(
+                    let (result, handling_time_us) = measure_us!(Self::process_accounts_package(
                         accounts_package,
                         snapshot_package_sender.as_ref(),
                         &snapshot_config,
                         &exit,
                     ));
+                    if let Err(err) = result {
+                        error!("Stopping AccountsHashVerifier! Fatal error while processing accounts package: {err}");
+                        exit.store(true, Ordering::Relaxed);
```
Comment (apfitzge) [inline core/src/accounts_hash_verifier.rs:83]: 🤔 so this is pretty new behavior right? We are going to shutdown the entire validator if AHV encounters an error.

What would have happened previously?

File: core/src/accounts_hash_verifier.rs (hunk 3 above)
Comment (apfitzge) [reply core/src/accounts_hash_verifier.rs]: Sorry for not being more clear. I was hoping to rename the file and whole "concept" of this file.
We're using it for fastboot, sure, but the file itself contains the slot of the full snapshot this snapshot is based on. Seems like that's potentially useful info even without fastboot, so giving it a more clear name everywhere (file name, function names, variable names) would make it more obvious what information is available there.

**Review by apfitzge — COMMENTED** [review]
Think the refactor made it a lot clearer, thanks! A couple more comments/questions

File: core/src/accounts_hash_verifier.rs (hunk 6 above)
Comment (brooksprumo) [reply core/src/accounts_hash_verifier.rs:83]: There were no returned Results in AHV before, so we didn't have to worry about this. However, multiple methods that AHV calls either unwrap or panic inside them.

I made the choice to return a Result from `write_fastboot_file()`, which is the only error source here. Writing any snapshot-related file to disk is a fatal error, so we're not changing that particular behavior. Instead we're catching the error, logging a operator-friendly message, and gracefully shutting down.

In reality, if the fastboot file cannot be written, something is very wrong with the validator machine itself. It's not an invariant in the code that we can check, so I don't think a panic/unwrap is the right call here, but the validator itself cannot continue running.

File: core/src/accounts_hash_verifier.rs (hunk 3 above)
Comment (brooksprumo) [reply core/src/accounts_hash_verifier.rs]: Got it. Yeah, that makes sense. The file could be "full_snapshot_archive_slot" instead. I was purposely going the opposite way; being ambiguous about what's inside the file, but indicating that it is used for fastboot. Renaming the file would be clear about the contents of the file, but ambiguous about usage.

I think for the sake of any forward compatibility/breaking changes, I'll go with the "full_snapshot_archive_slot" idea. This is unlikely to change. If we need more/different information later, we'll create another file.

Does that sound ok?

Comment (apfitzge) [reply core/src/accounts_hash_verifier.rs]: Sounds good, thanks @brooksprumo!

Comment (brooksprumo) [reply core/src/accounts_hash_verifier.rs]: Done. Renamed in https://github.com/anza-xyz/agave/pull/343/commits/796f5d1bdce4de0af01c6f711370b83e29d1042d.

File: ledger/src/bank_forks_utils.rs (hunk 2 above)
Comment (brooksprumo) [reply ledger/src/bank_forks_utils.rs]: This has been refactored. Please refer to https://github.com/anza-xyz/agave/pull/343#issuecomment-2015311836.

File: runtime/src/snapshot_utils.rs [hunk 7]
```diff
@@ -625,6 +627,76 @@ fn is_bank_snapshot_complete(bank_snapshot_dir: impl AsRef<Path>) -> bool {
...
+    Ok(slot)
+}
+
+/// Gets the highest, loadable, bank snapshot
+///
+/// The highest bank snapshot is the one with the highest slot.
+/// To be loadable, the bank snapshot must be a BankSnapshotKind::Post.
+/// And if we're generating snapshots (e.g. running a normal validator), then
+/// the full snapshot file's slot must match the highest full snapshot archive's.
+pub fn get_highest_loadable_bank_snapshot(
```
Comment (apfitzge) [inline runtime/src/snapshot_utils.rs:679]: Had a separate discussion with @brooksprumo about this function.
There is an edge-case that is not handled as efficiently as we'd like, but we decided to leave it as a follow-up since this PR covers the majority of cases and already has a lot going on.

The edge case is when we have a higher full snapshot **archive** than our highest snapshot. This can happen if ledger-tool is used to create a full snapshot archive - this does not create a snapshot.

This function could likely be improved so that we only check the existence of the full snapshot archive matching the `full_snapshot_file_slot`, even if it not the latest full snapshot archive. However, it requires changes elsewhere in ABS (others?) to gate cleaning properly.

**Review by apfitzge — APPROVED** [review]
Happy with changes as they are, as mentioned in my comment, it covers most of the cases and we are leaving an edge-case as follow-up work.

File: runtime/src/snapshot_utils.rs (hunk 7 above)
Comment (brooksprumo) [reply runtime/src/snapshot_utils.rs:679]: Good find! I'll handle this in a follow-up PR.
