### PR TITLE
Retry IO on short write in io_uring file creator

### LINKED ISSUE #8036: validator wont start on kernel 5.15 with agave v3.0.0
on Kernel 5.15.0-153-generic (ubuntu22) i cant run agave v3.0.0, I always get the error `IO error: Resource temporarily unavailable (os error 11)` when it tries to unpack either the gengesis.bin or a snapshot.
ive tried to reboot the server, but that didnt helped.
afterwards ive installed the kernel 6.8.0-79-generic, rebooted again and agave-validator ran instantly without any issues.
thats my service file, see my log attached.

```
[Unit]
Description=Solana Validator
After=network.target
StartLimitIntervalSec=0

[Service]
Type=exec
Restart=always
RestartSec=1
User=sfadmin
LimitNOFILE=1000000
LimitMEMLOCK=2000000000
ExecStart=/home/sfadmin/.local/share/solana/install/releases/v3.0.0/bin/agave-validator \
          --identity /home/sfadmin/sf-keys/identity-keypair.json \
          --limit-ledger-size 50000000 \
          --ledger /home/sfadmin/validator-ledger \
          --vote-account /home/sfadmin/sf-keys/vote-keypair.json \
          --authorized-voter /home/sfadmin/sf-keys/staked-identity-keypair.json \
          --accounts /mnt/accounts \
          --entrypoint entrypoint.testnet.solana.com:8001 \
          --entrypoint entrypoint2.testnet.solana.com:8001 \
          --entrypoint entrypoint3.testnet.solana.com:8001 \
          --rpc-port 58000 \
          --private-rpc \
          --full-rpc-api \
          --disable-accounts-disk-index \
          --use-snapshot-archives-at-startup when-newest \
          --expected-genesis-hash 4uhcVJyU9pJkvQyS88uRDiswHXSCkY3zQawwpjk2NsNY \
          --wal-recovery-mode skip_any_corrupted_record \
          --no-snapshot-fetch \
          --block-verification-method unified-scheduler \
          --log /home/sfadmin/agave.log
[Install]
WantedBy=multi-user.target
```

[agave.log](https://github.com/user-attachments/files/22300944/agave.log)

### PR DESCRIPTION
**Pull request by kskalski**
#### Problem
As reported in https://github.com/anza-xyz/agave/issues/8036#issuecomment-3289403923 ubuntu 22 with 5.15 kernel and ZFS filesystem experiences error due to short writes.
It's not completely clear which kernel / FS combination give 100% guarantee of not returning `EAGAIN` or short write, this comment https://github.com/axboe/liburing/issues/766#issuecomment-1384274838 suggests 5.15 fixed some issues, but given reports from the wild it's worth fixing.

#### Summary of Changes
Re-submit write when:
* getting resource temporarily unavailable error (`EAGAIN` aka `WouldBlock`)
* getting short write (unless `Ok` with 0-size write happens, which is treated as hard error)

Fixes #8036 (it's not clear where the resource busy errors come from, but write completion is the most likely place)

### CODE REVIEW

**Comment by kskalski** [comment]
I also found some panics from a few days ago in JitoLabs:
```
ELwVbNrN4q5UhwvVtz94jBxGZULsYQ4bm7XbK8mSDJSV 3.0.1 (src:8a176bcf; feat:128318206, client:JitoLabs)
assertion `left == right` failed: short write
  left: 109056
 right: 524288">panicked at accounts-db/src/io_uring/file_creator.rs:475:9:
```

**Review by brooksprumo — COMMENTED** [review]
How was this change tested?

**Comment by alessandrod** [comment]
Pls don’t merge this yet give me a chance to look at the original issue

**Comment by kskalski** [comment]
> How was this change tested?

so far only on regular devbox, which never experienced such errors, so for now I treat this PR as a reference for anyone to test if they see them.

**Comment by Lusitaniae** [comment]
Solana seems to be stuck for >10 mins during startup on this line when using this patch on top of 3.0.2

```
incremental-snapshot-367177550-367226598-5ECRCsPkt8C1DfTP3Qsm66wKof1wtwzZ34vSiQUDenj4.tar.zst
```

Without the patch (3.0.2 release) the error comes up immediately 

going back to 2.3.6 we can see next log message comes up within 14 seconds

```
Sep 16 15:31:22 tyo162 solana-rpc.sh[3772]: [2025-09-16T15:31:22.412669606Z INFO  solana_runtime::snapshot_bank_utils] Loading bank from full snapshot archive: /solana/snapshots/snapshot-367177550-3GAd3xdqzzvvqzrMNaJf8eQwGSDpLm3a8EK49GNhp5jr.tar.zst, and incremental snapshot archive: Some("/solana/snapshots/incremental-snapshot-367177550-367226598-5ECRCsPkt8C1DfTP3Qsm66wKof1wtwzZ34vSiQUDenj4.tar.zst")
Sep 16 15:31:36 tyo162 solana-rpc.sh[3772]: [2025-09-16T15:31:36.198758883Z INFO  solana_runtime::snapshot_utils::snapshot_storage_rebuilder] rebuilt storages for 41553/428935 slots with 0 collisions

```

**Comment by kskalski** [comment]
If it's stuck, it probably hits this condition repeatedly:
>    Err(err) if err.kind() == io::ErrorKind::WouldBlock => 0, // treat as a kind of short write

which is unfortunate, as it looks like the kernel requires IO to be submitted with ASYNC flag. It might be somehow related to fixed (file-descriptor) writes we are using, it is actually because of weird scheduling into non-blocking workers for fixed writes that we are not marking all IOs as ASYNC.

Maybe we can selectively mark as ASYNC when encountering `WouldBlock` error - this won't hurt performance / the way IOs are scheduled to workers for common case / newer kernels, but won't block / crash on old kernel.

**Comment by kskalski** [comment]
Ok, confirmed on triton's node (5.15 kernel) that adding async flag makes unpacking proceed at more or less normal pace and succeed (I didn't check though if the issue happens for all or only some write ops).
I think at some point we should re-check setting async as default for writes, but I would prefer to do it after all pending PRs on io_uring as merged (specifically https://github.com/anza-xyz/agave/pull/6878), since they changed the mode of io_uring writes (e.g. putting them in sqpoll).

**Comment by kskalski** [comment]
Also confirmed that `EAGAIN` error occurs for all writes when they are in directory backed by `/dev/zram0`, which is reproducible using our `file_io::tests::test_create_writes_contents` test when tempdir is pointed to that mount.

**Comment by alessandrod** [comment]
> Also confirmed that `EAGAIN` error occurs for all writes when they are in directory backed by `/dev/zram0`, which is reproducible using our `file_io::tests::test_create_writes_contents` test when tempdir is pointed to that mount.

Can you please add a test for this? Something that does whatever setup is needed to trigger the error.

**Comment by alessandrod** [comment]
> but I would prefer to do it after all pending PRs on io_uring as merged (specifically #6878), since they changed the mode of io_uring writes (e.g. putting them in sqpoll).

we need to do the smallest possible change that fixes whatever we've broken for people (I'm assuming 3.0?)

**Comment by kskalski** [comment]
> Can you please add a test for this? Something that does whatever setup is needed to trigger the error.

There was a bit of discussion about that on slack and the suggestion was to do a one-off fix without support for it in the test automation - the problem is that this only happens with a zram disk, which is not something normally available in the test environment. Unless we get a repro with vanilla disks, I'm not sure how to better test it.

> we need to do the smallest possible change that fixes whatever we've broken for people (I'm assuming 3.0?)

Agree, I believe this PR is the least resistance change, i.e. it fixes the issue without affecting runtime / performance of the baseline, while fixing it in a different way could bring some unknowns.

**Comment by alessandrod** [comment]
> the problem is that this only happens with a zram disk

how sure are we about this? Is it "only people with zram have complained" or "we're 100% positive it's only zram"?

**Comment by alessandrod** [comment]
> Also confirmed that `EAGAIN` error occurs for all writes when they are in directory backed by `/dev/zram0`, which is reproducible using our `file_io::tests::test_create_writes_contents` test when tempdir is pointed to that mount.

This is why I'm not comfortable with this patch. I suspect that we're doing all submissions twice when we hit this bug: non async => EAGAIN => async.

Also I don't think this is a case of short writes. Short write = written < requested_write, but here we're writing 0 and getting EAGAIN. The patch is kinda confusing since we're restoring the short write offet code (which we should implement to be clear), but in this case we always hit WouldBlock so written=0 so we never update offsets.

I think we need to add a test for zram, RCA, make sure that either everyone who's hitting this bug is doing so because of zram or RCA further.

**Comment by kskalski** [comment]
> how sure are we about this? Is it "only people with zram have complained" or "we're 100% positive it's only zram"?

Short writes / EAGAIN do happen in the wild, though not often, e.g. I've seen a panic from JitoLabs from a few weeks ago, now I also see one for 335NaZ18GDW4rEmcoTb3Fae5CwKyqY8iVp6BtPAWc8A7 (using 3.1 release) from Sep-17.
Reported problems are with:
* zram - happen on 100% of writes, reproducible with a unittest
* tmpfs - so far I wasn't able to reproduce with test on our CI
* none of the Anza servers, including those running 5.15 kernel, experienced this, 
* upgrading the kernel always fixes the issue, which suggests it is actual kernel bug that was fixed somewhere in >5.15

> This is why I'm not comfortable with this patch. I suspect that we're doing all submissions twice when we hit this bug: non async => EAGAIN => async.

Yes, this is exactly what happens.

> Also I don't think this is a case of short writes. Short write = written < requested_write, but here we're writing 0 and getting EAGAIN. The patch is kinda confusing since we're restoring the short write offet code (which we should implement to be clear), but in this case we always hit WouldBlock so written=0 so we never update offsets.

True, this patch fixes both short writes and would block in one go (both cases were actually reported from user with zram), maybe it would be less confusing if `use_async` val were derived directly from error kind == would block... I find the current code more succinct though as `written` is calculated in one place and all cases of retry are gated by checking it, but can change it in any way.  

> I think we need to add a test for zram, RCA, make sure that either everyone who's hitting this bug is doing so because of zram or RCA further.

Well, the test itself is quite simple:
```
    #[test]
    fn test_create_writes_contents() -> io::Result<()> {
-        let temp_dir = tempfile::tempdir()?;
+        let temp_dir = tempfile::tempdir_in("/zram/")?;
```
though technically it would only test that the fix is a proper one for zram. 
Since the fix is a generic one for all cases of short write / EAGAIN irrespective of their cause, in order to verify that the issue doesn't happen in other context we would need to add some metric to detect the situation and dig on each of its elevated occurrence.

**Comment by alessandrod** [comment]
Ok I've gone pretty deep on this, here's my findings so far:

- virtually no filesystems implement NOWAIT so submitting in non-blocking (non-async) mode doesn't make much sense, we just execute extra code then io-uring will fallback ASYNC anyway
- brtfs (and xfs) can do NOWAIT if you write to something that is already in the page cache - this is probably why we get brtfs specific bugs
- tmpfs can also do NOWAIT but only when it doesn't require allocations
- when EAGAIN is retried
    - the first time when an entry is submitted with NOWAIT (when we don't set the ASYNC flag), EAGAIN causes re-submission in a worker
    - indefinitely in a worker ONLY IF IORING_SETUP_IOPOLL is set (only works for O_DIRECT)
    - only once in a worker if the ASYNC flag is set

See https://github.com/torvalds/linux/commit/e0deb6a025ae8c850dc8685be39fb27b06c88736

So I think we must always handle EAGAIN in our code. And we must make sure we don't loop indefinitely retrying always the same write - for example if we run out of memory (tmpfs) or disk (although maybe we get ENOSPC in that case?).

I haven't looked at what's happening with zram specifically yet, I'll do that next.

EDIT: zram doesn't seem to be have differently from ext4.

> Ok, confirmed on triton's node (5.15 kernel) that adding async flag makes unpacking proceed at more or less normal pace and succeed 

I am now skeptical that ASYNC is fixing any issues here?

**Comment by kskalski** [comment]
> Ok I've gone pretty deep on this, here's my findings so far:

Thanks for the in-depth research.

> 
>       * the first time when an entry is submitted with NOWAIT (when we don't set the ASYNC flag), EAGAIN causes re-submission in a worker

I think this is the culprit of the problem - my guess is 5.15 had a bug in this path. Do you know a specific point in code where this happens? If we really want to get to the root cause, we should compare how it was in 5.15. On the other hand it's just a couple more months while we need to support that kernel - not knowing what exactly is happening will probably keep this code here indefinitely. :/

>       * indefinitely in a worker ONLY IF IORING_SETUP_IOPOLL is set (only works for O_DIRECT)

FWIW I tested enabling *sqpoll* on the machine with reproduction, and it didn't fix the issue, it wasnt IOPOLL / O_DIRECT though, so I guess it wouldn't apply.

> So I think we must always handle EAGAIN in our code. And we must make sure we don't loop indefinitely retrying always the same write - for example if we run out of memory (tmpfs) or disk (although maybe we get ENOSPC in that case?).

Ok, I added the check that we only retry `WouldBlock` when original write wasn't async.

> I am now skeptical that ASYNC is fixing any issues here?

Hm, not sure, my bet is 5.15 had some serious bug. Also, from the report it seems ZFS version might matter too, there is a comment
```
1st server (accounts in ZFS): Upgrading kernel (5.15.0 to 6.8.0) + zfs (2.2.6 to latest 2.3.4) seems to have solved it
2nd server (accounts ZRAM): Upgrading kernel (5.15.0 to 6.8.0) alone worked
```

Irrespective of that - this PR is kind of implementing the standard IO API, i.e. when you see short write, retry with remaining payload, when you see `WouldBlock`, retry in async mode (usually `EAGAIN` and `EWOULDBLOCK` are the same errors, so let's say it does relate only to async)

**Comment by alessandrod** [comment]
> when you see WouldBlock, retry in async mode

This is not how it works tho. EAGAIN has nothing to do with ASYNC. I don't think we should be submitting with ASYNC in case of short write. 

I think we should watch the offset/written amount, resubmit, if we detect no progress bail.

**Comment by alessandrod** [comment]
too lazy to type but 

Screenshot 2025-09-23 at 9 45 02 pm

we should remove O_NONBLOCK from FileCreator (separate PR), handle short writes making sure we don't loop if we don't make progress, and remove the ASYNC resubmission from this PR

**Comment by kskalski** [comment]
Created https://github.com/anza-xyz/agave/pull/8161 for removing `O_NONBLOCK` flag and changed this PR to only handle short-writes, which I think is also necessary to fix https://github.com/anza-xyz/agave/issues/8036 completely.

I will try to add a testcase for disk-full in a separate PR, since I think it will contain a lot of set-up code / changes that should be separate (for purpose of more confident back-porting).

File: accounts-db/src/io_uring/file_creator.rs [hunk 1]
```diff
@@ -462,22 +466,37 @@ impl<'a> WriteOp {
...
         } = self;
 
-        // unless specified otherwise, the io uring worker will retry automatically on EAGAIN
-        assert_eq!(written, *write_len, "short write");
-
         let buf = mem::replace(buf, FixedIoBuffer::empty());
+        let total_written = *buf_offset + written;
+
+        if written < *write_len {
+            ring.push(FileCreatorOp::Write(WriteOp {
```
Comment (alessandrod) [inline accounts-db/src/io_uring/file_creator.rs:488]: nit: add a warn!() here?

**Review by alessandrod — APPROVED** [review]

**Review by brooksprumo — APPROVED** [review]
:shipit:
