### PR TITLE
[rpc] Fatal `getSignaturesForAddress()` when Bigtable errors

### LINKED ISSUE #3696: `getSignaturesForAddress` return `[]` (empty result) instead of json error, if BigTable connection is broken
## Problem

If the BigTable connection is broken (e.g., timeout, connection error, etc.), `getSignaturesForAddress` returns `[]` (an empty result) instead of a JSON error. This makes it impossible to differentiate whether the account does not exist or is a BT connection error.

### Examples

**This request returns an empty response**

```sh
$ curl http://BAD-bt-connection-host:8899 -d '{
  "id": "1",
  "jsonrpc": "2.0",
  "method": "getSignaturesForAddress",
  "params": [
    "BCeczqpTRPigndHVJu1KEzno1Uhb4hjrE7ttmAndrV1p",
    {
      "before": "4LYF9dfwdynWDAGjyaS8VxTrZhtXtbThCztnCrRtA8iUf4ZfHTw87NdUfJVJiL3VdrZLuJC3GmhqFA4iBgh2Vhmy",
      "commitment": "finalized"
    }
  ]
}' --header 'Content-Type: application/json'
{"jsonrpc":"2.0","result":[],"id":"1"}
```

**While matching data exists in the BT**
```sh
$ curl -s http://GOOD-bt-connection-host:8899 -d '{
  "id": "1",
  "jsonrpc": "2.0",
  "method": "getSignaturesForAddress",
  "params": [
    "BCeczqpTRPigndHVJu1KEzno1Uhb4hjrE7ttmAndrV1p",
    {
      "before": "4LYF9dfwdynWDAGjyaS8VxTrZhtXtbThCztnCrRtA8iUf4ZfHTw87NdUfJVJiL3VdrZLuJC3GmhqFA4iBgh2Vhmy",
      "commitment": "finalized"
    }
  ]
}' --header 'Content-Type: application/json' | jq '.result |  first'
{
  "blockTime": 1727421527,
  "confirmationStatus": "finalized",
  "err": null,
  "memo": null,
  "signature": "2pfkzDaAYDoZvL5pEbNhh7dJVxGRYfRAM29yywnhtdS7W1VpqbjebkHxVonGd9azusxG9TA2a8jfAKDLtow8Kbhm",
  "slot": 292262085
}
```
So, this output might make you think that data does not exist, while it does.

**Example of the request empty account:**
```sh
$ curl localhost:8899 -d '{
  "id": "1",
  "jsonrpc": "2.0",
  "method": "getSignaturesForAddress",
  "params": [
    "BzszvNFvokG4v4qb1ipYSDGtKuhen8PMtYjevfZeAkKZ"
  ]
}' --header 'Content-Type: application/json'
{"jsonrpc":"2.0","result":[],"id":"1"}
```

## How to reproduce

- blackhole the BT host to 127.0.0.1
```sh
$ cat /etc/hosts
<...>
127.0.0.1 bigtable.googleapis.com
```
- restart the validator with the BT credential settings

## Proposed Solution

I expect `getSignaturesForAddress` to respond with a JSON error, like `getBlocks` method does: 

```sh
$ curl BAD-bt-connection-host:8899 -X POST -H "Content-Type: application/json" -d '
  {
    "jsonrpc": "2.0", "id": 1,
    "method": "getBlocks",
    "params": [
      5, 10
    ]
  }
'
{"jsonrpc":"2.0","error":{"code":-32602,"message":"BigTable query failed (maybe timeout due to too large range?)"},"id":1}
```

## Environment

This happens on both `1.18.26` and `2.0.15` agave.

### PR DESCRIPTION
**Pull request by steveluscher**
### Problem

Consider a request to `getSignaturesForAddress()`. Imagine that there are no signatures in blockstore, but there _are_ signatures in long-term storage (ie. Bigtable).

Currently, if we fail to _reach_ Bigtable – because of a timeout or a connection failure – we return whatever signatures we have. This means that people who query the RPC can't distinguish between the following cases:

* No signatures were found because there are none, or
* No signatures were found because Bigtable was temporarily unavailable

### Summary of Changes

1. When doing a range query in `get_confirmed_signatures_for_address` and the `before`/`until` can't be found, throw a `SignatureNotFound` error instead of `RowNotFound`.
2. Now that we can match on actual connection errors – separate from `SignatureNotFound` errors – return a JSON-RPC error in the event that long-term storage errors out.

#### With the Bigtable emulator

```shell
> gcloud beta emulators bigtable start
> ./init-bigtable.sh
```

```shell
> tail -f validator.log | grep [Bb]ig[Tt]able
[2024-11-19T23:06:05.994676924Z INFO  solana_rpc::rpc_service] rpc configuration: JsonRpcConfig { enable_rpc_transaction_history: true, enable_extended_tx_metadata_storage: true, faucet_addr: Some(0.0.0.0:9900), health_check_slot_distance: 0, skip_preflight_health_check: false, rpc_bigtable_config: Some(RpcBigtableConfig { enable_bigtable_ledger_upload: false, bigtable_instance_name: "solana-ledger", bigtable_app_profile_id: "default", timeout: None, max_message_size: 67108864 }), max_multiple_accounts: None, account_indexes: AccountSecondaryIndexes { keys: None, indexes: {} }, rpc_threads: 0, rpc_niceness_adj: 0, full_api: true, rpc_scan_and_fix_roots: false, max_request_body_size: None, disable_health_check: true }
[2024-11-19T23:06:05.995145895Z INFO  solana_storage_bigtable::bigtable] Connecting to bigtable emulator at localhost:8086
[2024-11-19T23:06:05.995411312Z INFO  solana_rpc::rpc_service] BigTable ledger storage initialized
```

##### Fetching a signature for an address that does not exist locally

Observe that the RPC goes out to Bigtable and fetches successfully (finds nothing)

```shell
curl localhost:8899 -d '{
  "id": "1",
  "jsonrpc": "2.0",
  "method": "getSignaturesForAddress",
  "params": [
    "BzszvNFvokG4v4qb1ipYSDGtKuhen8PMtYjevfZeAkKZ"
  ]
}' --header 'Content-Type: application/json'
{"jsonrpc":"2.0","result":[],"id":"1"}
```

##### Fetching a signature for an address _and_ before signature that don't exist locally

Observe that Bigtable can't find the before signature, but doesn't fatal the request

```shell
curl localhost:8899 -d '{
  "id": "1",
  "jsonrpc": "2.0",
  "method": "getSignaturesForAddress",
  "params": [
    "BzszvNFvokG4v4qb1ipYSDGtKuhen8PMtYjevfZeAkKZ",
    {"before":"31AUDAUXgD4B5DqqtFZZe8udgHUfbJX9dQbiXQGmNiRqeKRkzRTYitrRbJDtpt4DMd4P3G8haaXMJ8TU6wwQmf3h"}
  ]
}' --header 'Content-Type: application/json'
{"jsonrpc":"2.0","result":[],"id":"1"}
```

##### Fetching a signature for an address that is completely available locally

Observe Bigtable is never contacted.

```shell
curl localhost:8899 -d '{
  "id": "1",
  "jsonrpc": "2.0",
  "method": "getSignaturesForAddress",
  "params": [
    "jZ2L6sHvF862QMKYxD7ho7JQAX5m1rT9VzVKvzSSbin",
    {"limit": 1}
  ]
}' --header 'Content-Type: application/json'
{"jsonrpc":"2.0","result":[{"blockTime":1732058393,"confirmationStatus":"finalized","err":null,"memo":null,"signature":"3mZUQjhaGA7ytwb3g9PnjYL4d1ErsWf7nheMCqnSuwW6x2hF8tx4DuuvG1u7j6qVCC2J9JqpRHbJ7z57ayhJZyW2","slot":9284}],"id":"1"}
```

##### Fetching a signature for an address that does exist but with a bad `before` signature

Observe that Bigtable can't find the before signature, but doesn't fatal the request

```shell
curl localhost:8899 -d '{
  "id": "1",
  "jsonrpc": "2.0",
  "method": "getSignaturesForAddress",
  "params": [
    "jZ2L6sHvF862QMKYxD7ho7JQAX5m1rT9VzVKvzSSbin",
    {"before":"419mQJ2ZpM1uJ2VJyHckWNzmEpRKkyuirvRQH9NfgKvzQJxTcTa5v8U7tXJ4VkqEH8GsTtG7iqSsQBJe8VxxC2XQ","limit": 1}
  ]
}' --header 'Content-Type: application/json'
{"jsonrpc":"2.0","result":[],"id":"1"}
```

##### Fetching a signature before the last signature, forcing the RPC to go to Bigtable where there is no data

Observe that the RPC goes out to Bigtable and fetches successfully (finds nothing)

```shell
curl localhost:8899 -d '{
  "id": "1",
  "jsonrpc": "2.0",
  "method": "getSignaturesForAddress",
  "params": [
    "jZ2L6sHvF862QMKYxD7ho7JQAX5m1rT9VzVKvzSSbin",
    {
      "before":"45z1V6qdGUXRHid4YDzSSqV13pegyP2naBaA3aG4ZoS4xMdKjC3eBvhwTkbXrqEXJT38grfRJ11wCTn5Qop67AEv",
      "limit": 1
    }
  ]
}' --header 'Content-Type: application/json'
{"jsonrpc":"2.0","result":[],"id":"1"}
```

##### Fetching a signature for an address that does not exist locally

```shell
curl localhost:8899 -d '{
  "id": "1",
  "jsonrpc": "2.0",
  "method": "getSignaturesForAddress",
  "params": [
    "BzszvNFvokG4v4qb1ipYSDGtKuhen8PMtYjevfZeAkKZ"
  ]
}' --header 'Content-Type: application/json'
{"jsonrpc":"2.0","error":{"code":-32019,"message":"Failed to query long-term storage; please try again"},"id":"1"}
```

##### Fetching a signature for an address _and_ before signature that don't exist locally

Observe that Bigtable experiences a connection error.

```shell
curl localhost:8899 -d '{
  "id": "1",
  "jsonrpc": "2.0",
  "method": "getSignaturesForAddress",
  "params": [
    "BzszvNFvokG4v4qb1ipYSDGtKuhen8PMtYjevfZeAkKZ",
    {"before":"31AUDAUXgD4B5DqqtFZZe8udgHUfbJX9dQbiXQGmNiRqeKRkzRTYitrRbJDtpt4DMd4P3G8haaXMJ8TU6wwQmf3h"}
  ]
}' --header 'Content-Type: application/json'
{"jsonrpc":"2.0","error":{"code":-32019,"message":"Failed to query long-term storage; please try again"},"id":"1"}
```

##### Fetching a signature for an address that is completely available locally

Observe Bigtable is never contacted.

```shell
curl localhost:8899 -d '{
  "id": "1",
  "jsonrpc": "2.0",
  "method": "getSignaturesForAddress",
  "params": [
    "jZ2L6sHvF862QMKYxD7ho7JQAX5m1rT9VzVKvzSSbin",
    {"limit": 1}
  ]
}' --header 'Content-Type: application/json'
{"jsonrpc":"2.0","result":{"jsonrpc":"2.0","result":[{"blockTime":1732058393,"confirmationStatus":"finalized","err":null,"memo":null,"signature":"3mZUQjhaGA7ytwb3g9PnjYL4d1ErsWf7nheMCqnSuwW6x2hF8tx4DuuvG1u7j6qVCC2J9JqpRHbJ7z57ayhJZyW2","slot":9284}],"id":"1"}
```

##### Fetching a signature for an address that does exist but with a bad `before` signature

Observe that Bigtable experiences a connection error.

```shell
curl localhost:8899 -d '{
  "id": "1",
  "jsonrpc": "2.0",
  "method": "getSignaturesForAddress",
  "params": [
    "jZ2L6sHvF862QMKYxD7ho7JQAX5m1rT9VzVKvzSSbin",
    {"before":"419mQJ2ZpM1uJ2VJyHckWNzmEpRKkyuirvRQH9NfgKvzQJxTcTa5v8U7tXJ4VkqEH8GsTtG7iqSsQBJe8VxxC2XQ","limit": 1}
  ]
}' --header 'Content-Type: application/json'
{"jsonrpc":"2.0","error":{"code":-32019,"message":"Failed to query long-term storage; please try again"},"id":"1"}
```

##### Fetching a signature before the last signature, forcing the RPC to go to Bigtable where there is no data

Observe that Bigtable experiences a connection error.

```shell
curl localhost:8899 -d '{
  "id": "1",
  "jsonrpc": "2.0",
  "method": "getSignaturesForAddress",
  "params": [
    "jZ2L6sHvF862QMKYxD7ho7JQAX5m1rT9VzVKvzSSbin",
    {
      "before":"45z1V6qdGUXRHid4YDzSSqV13pegyP2naBaA3aG4ZoS4xMdKjC3eBvhwTkbXrqEXJT38grfRJ11wCTn5Qop67AEv",
      "limit": 1
    }
  ]
}' --header 'Content-Type: application/json'
{"jsonrpc":"2.0","error":{"code":-32019,"message":"Failed to query long-term storage; please try again"},"id":"1"}
```

Fixes #3696

### CODE REVIEW

**Comment by steveluscher** [comment]
How would I go about testing/mocking a Bigtable failure. I wanted to at least write something like this:

```rs
#[test]
fn test_signatures_for_address_blockstore_query_failure() {
    let rpc = RpcHandler::start_with_config(JsonRpcConfig {
        enable_rpc_transaction_history: true,
        rpc_bigtable_config: # ???
        ..Default::default()
    });
    let pubkey = Pubkey::new_unique();
    // This address is guaranteed to have no signatures, thereby forcing
    // `getSignaturesForAddress` to go looking in long-term storage.
    let address = pubkey.to_string();
    let request = create_test_request(
        "getSignaturesForAddress",
        Some(json!([address, {"limit": 10}])),
    );
    let (code, _message) = parse_failure_response(rpc.handle_request_sync(request));

    assert_eq!(code, JSON_RPC_SERVER_ERROR_LONG_TERM_STORAGE_UNREACHABLE);
}
```

…but I can't figure out how to supply ‘a bigtable instance that will always fail.’

File: rpc/src/rpc.rs [hunk 1]
```diff
@@ -1689,118 +1689,116 @@ impl JsonRpcRequestProcessor {
...
-            } else {
-                let min_context_slot = config.min_context_slot.unwrap_or_default();
-                if highest_super_majority_root < min_context_slot {
-                    return Err(RpcCustomError::MinContextSlotNotReached {
-                        context_slot: highest_super_majority_root,
-                    }
-                    .into());
+        if !self.config.enable_rpc_transaction_history {
+            return Err(RpcCustomError::TransactionHistoryNotAvailable.into());
+        }
```
Comment (steveluscher) [inline rpc/src/rpc.rs:1694]: This is the meat of the unindenting. All of the code below is unchanged.

File: rpc-client-api/src/custom_error.rs [hunk 2]
```diff
@@ -26,6 +26,7 @@ pub const JSON_RPC_SERVER_ERROR_UNSUPPORTED_TRANSACTION_VERSION: i64 = -32015;
 pub const JSON_RPC_SERVER_ERROR_MIN_CONTEXT_SLOT_NOT_REACHED: i64 = -32016;
 pub const JSON_RPC_SERVER_ERROR_EPOCH_REWARDS_PERIOD_ACTIVE: i64 = -32017;
 pub const JSON_RPC_SERVER_ERROR_SLOT_NOT_EPOCH_BOUNDARY: i64 = -32018;
+pub const JSON_RPC_SERVER_ERROR_LONG_TERM_STORAGE_UNREACHABLE: i64 = -32019;
```
Comment (steveluscher) [inline rpc-client-api/src/custom_error.rs:29]: Will dutifully add this to `@solana/web3.js` once landed.

File: rpc-client-api/src/custom_error.rs [hunk 3]
```diff
@@ -244,6 +247,11 @@ impl From<RpcCustomError> for Error {
                 ),
                 data: None,
             },
+            RpcCustomError::LongTermStorageUnreachable => Self {
+                code: ErrorCode::ServerError(JSON_RPC_SERVER_ERROR_LONG_TERM_STORAGE_UNREACHABLE),
+                message: "Failed to query long-term storage; please try again".to_string(),
```
Comment (steveluscher) [inline rpc-client-api/src/custom_error.rs:252]: I figured I'd say ‘please try again’ to indicate that the failure is transient.

File: storage-bigtable/src/lib.rs [hunk 4]
```diff
@@ -796,7 +796,11 @@ impl LedgerStorage {
             Some(before_signature) => {
                 let TransactionInfo { slot, index, .. } = bigtable
                     .get_bincode_cell("tx", before_signature.to_string())
-                    .await?;
+                    .await
+                    .map_err(|err| match err {
+                        bigtable::Error::RowNotFound => Error::SignatureNotFound,
+                        _ => err.into(),
```
Comment (steveluscher) [inline storage-bigtable/src/lib.rs:802]: Something similar was added to `get_signature_status` in https://github.com/anza-xyz/agave/commit/71e9958e061493d7545bd28d4ac7a85aaed6ffbb but we could use it here, to disambiguate between ‘couldn't find the thing’ and ‘o no bigtable down bad.’

File: rpc/src/rpc.rs [hunk 5]
```diff
@@ -1761,8 +1761,8 @@ impl JsonRpcRequestProcessor {
                             bigtable_before = None;
                         }
                         Err(err) => {
-                            warn!("{:?}", err);
-                            return Ok(map_results(results));
```
Comment (steveluscher) [inline rpc/src/rpc.rs]: Previously, this code would catch _all_ manner of Bigtable failure, including connection failures, and return whatever results we have so far.

File: rpc/src/rpc.rs [hunk 6]
```diff
@@ -1761,8 +1761,8 @@ impl JsonRpcRequestProcessor {
...
+                            warn!("Failed to query Bigtable: {:?}", err);
+                            return Err(RpcCustomError::LongTermStorageUnreachable.into());
```
Comment (steveluscher) [inline rpc/src/rpc.rs:1765]: Now that `storage_bigtable/lib.rs` properly throws `SignatureNotFound` errors, we can be sure that when this arm is matched, it's because of a Bigtable connection error.

File: rpc/src/rpc.rs [hunk 7]
```diff
@@ -1791,8 +1791,10 @@ impl JsonRpcRequestProcessor {
                             }
                         }
                     }
+                    Err(StorageError::SignatureNotFound) => {}
```
Comment (steveluscher) [inline rpc/src/rpc.rs:1794]: A failure to find the `before` or `until` signatures continues to behave like the old code: skip and move on.

File: rpc/src/rpc.rs [hunk 8]
```diff
@@ -1791,8 +1791,10 @@ impl JsonRpcRequestProcessor {
...
                     Err(err) => {
-                        warn!("{:?}", err);
+                        warn!("Failed to query Bigtable: {:?}", err);
+                        return Err(RpcCustomError::LongTermStorageUnreachable.into());
```
Comment (steveluscher) [inline rpc/src/rpc.rs:1797]: Now that `storage_bigtable/lib.rs` properly throws SignatureNotFound errors, we can be sure that when this arm is matched, it's because of a Bigtable connection error.

**Review by godmodegalactus — APPROVED** [review]
LGTM

File: rpc/src/rpc.rs [hunk 9]
```diff
@@ -1689,118 +1689,118 @@ impl JsonRpcRequestProcessor {
...
-                                    .get(item.slot)
-                                    .map(|bank| bank.clock().unix_timestamp);
-                            }
+        let map_results = |results: Vec<ConfirmedTransactionStatusWithSignature>| {
+            results
+                .into_iter()
+                .map(|x| {
+                    let mut item: RpcConfirmedTransactionStatusWithSignature = x.into();
+                    if item.slot <= highest_super_majority_root {
+                        item.confirmation_status = Some(TransactionConfirmationStatus::Finalized);
```
Comment (KirillLykov) [inline rpc/src/rpc.rs:1729]: looks like there was wrong indentation, weird that cargo fmt didn't complain on the old code.

**Review by KirillLykov — APPROVED** [review]
I looked through the code, looks like a really good change to me.
