### PR TITLE
SIMD-0160: static instruction limit

### LINKED ISSUE #8181: Feature Gate: Static Instruction Limit
### SIMD

https://github.com/solana-foundation/solana-improvement-documents/pull/160

### Description

Transactions will fail execution in SVM if the transactions use more than 64
instructions, including CPI calls.
This proposal is to make transactions that use more than 64 top-level
instructions fail sanitization checks and be rejected by the network.

### Feature ID

64ixypL1HPu8WtJhNSMb9mSgfFaJvsANuRkTbHyuLfnx

### Activation Method

Single Core Contributor

### Deployment Considerations

N/A

### Minimum Beta Version

_No response_

### Minimum Stable Version

_No response_

### Testnet Activation Epoch

_No response_

### Devnet Activation Epoch

_No response_

### Mainnet-Beta Activation Epoch

_No response_

### PR DESCRIPTION
**Pull request by tao-stones**
#### Problem
Issue #8181 for [SIMD-0160](https://github.com/solana-foundation/solana-improvement-documents/pull/160)

#### Summary of Changes
- Add feature gate to start apply limit to transaction's top level instructions during sanitization.

Fixes #8181

### CODE REVIEW

File: runtime/src/bank.rs [hunk 1]
```diff
@@ -4599,6 +4599,14 @@ impl Bank {
             }
             let message_hash = if verification_mode == TransactionVerificationMode::FullVerification
             {
+                // SIMD-0160, check instruction limit before signature verificaton
+                if self
+                    .feature_set
+                    .is_active(&agave_feature_set::static_instruction_limit::id())
+                    && tx.message.instructions().len() > 64
```
Comment (tao-stones) [inline runtime/src/bank.rs]: `64` will be replaced with CONST when #8177 lands

File: feature-set/src/lib.rs [hunk 2]
```diff
@@ -1137,6 +1137,10 @@ pub mod provide_instruction_data_offset_in_vm_r2 {
     solana_pubkey::declare_id!("5xXZc66h4UdB6Yq7FzdBxBiRAFMMScMLwHxk2QZDaNZL");
 }
 
+pub mod static_instruction_limit {
+    solana_pubkey::declare_id!("64ixypL1HPu8WtJhNSMb9mSgfFaJvsANuRkTbHyuLfnx");
```
Comment (apfitzge) [inline feature-set/src/lib.rs:1141]: 64ix 🫡

File: runtime/src/bank.rs [hunk 3]
```diff
@@ -4599,6 +4599,15 @@ impl Bank {
             }
             let message_hash = if verification_mode == TransactionVerificationMode::FullVerification
             {
+                // SIMD-0160, check instruction limit before signature verificaton
```
Comment (apfitzge) [inline runtime/src/bank.rs:4609]: I'm fine with leaving this check here because it's an optimization to discard on invalid ixs before we check sigs.

However, I think we should probably repeat the check inside of the `RuntimeTransaction::try_create`. That way it prevents us from creating the type we actually execute on/with in agave, without checking it.

Comment (apfitzge) [reply runtime/src/bank.rs:4609]: As is, we won't filter them out for the `sdk` path in block-production, which would lead to agave creating invalid blocks.

**Review by apfitzge — CHANGES_REQUESTED** [review]

File: runtime/src/bank.rs (hunk 3 above)
Comment (tao-stones) [reply runtime/src/bank.rs:4609]: Great point! #8183 checks this at sigverify for block production path; 

Can submit a change to SDK to include same check to sanitization, but perhaps *after* this feature activation, so don't have to passing feature_set around

Comment (apfitzge) [reply runtime/src/bank.rs:4609]: Ah true, but then I feel like SV should be part of this PR; otherwise the feature should be rekeyed since we changed it.

I think the ideal way though is just throw it in RuntimeTransaction. Then we know for sure any path executing transactions (including simulation!) will get this check.

Comment (tao-stones) [reply runtime/src/bank.rs:4609]: Good catch for `simulation`. I was trying not to bring a feature gate status to RuntimeTransaction, it looks like it is necessary.

As for SV part of change (#8183), thinking can have it merged without feature gate since it only agave's banking stage. not sure what you mean by "otherwise the feature should be rekeyed since we changed it."

Comment (tao-stones) [reply runtime/src/bank.rs:4609]: b13051fb3d8d838adf0f6462c5629b2b58d6b829 checks at `runtime-transaction::try_create()`

Comment (apfitzge) [reply runtime/src/bank.rs:4609]: Looks like that one only has it added in the sdk variant? I think we should have it in both for consistency

Comment (tao-stones) [reply runtime/src/bank.rs:4609]: Love to be consistent, but in this case, `RuntimeTransaction` only takes sanitized `TransactionView` (eg, either `SanitizedTransactionView` or `ResolvedTransactionView`), really doesn't need to check it again.

**Review by apfitzge — APPROVED** [review]
On it's own this PR does not support the transition into the feature correctly, but since #8183 has already been merged it seems this will work as intended.

My thought here was that `RuntimeTransaction`/`SanitizedTransactionView` types are not sufficient because we create these values ahead of time and store until we become leader. If ingested before the activation these can get past the filters of this PR for block-production, and a leader could include them. However, since #8183 we do not even reach this stage and they are dropped before we get here.
