### PR TITLE
fix: fix shell generation panic due to unnecessary 'conflicts_with'

### LINKED ISSUE #2929: [bug] `solana completion -s zsh` panics
#### Problem
Porting from https://github.com/solana-labs/solana/issues/35175

Root cause seems to be a clap v2 issue that was fixed in 2020 - https://github.com/clap-rs/clap/pull/2191

```
❯ RUST_BACKTRACE=full solana completion -s zsh
thread 'main' panicked at /Users/administrator/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap-2.33.3/src/completions/zsh.rs:407:29:
Fatal internal error. Please consider filing a bug report at https://github.com/clap-rs/clap/issues
stack backtrace:
   0:        0x101a722b8 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h298c9ab285ff3934
   1:        0x101a92288 - core::fmt::write::h4e276abdb6d0c2a1
   2:        0x101a6e92c - std::io::Write::write_fmt::hd421848f5f0bf9d0
   3:        0x101a720f4 - std::sys_common::backtrace::print::hd8bd9ecab1f94b94
   4:        0x101a73600 - std::panicking::default_hook::{{closure}}::h520eeb743fc98fb4
   5:        0x101a73348 - std::panicking::default_hook::ha6550ffe49b63df1
   6:        0x101a73a28 - std::panicking::rust_panic_with_hook::hddb0e884a202de7c
   7:        0x101a73928 - std::panicking::begin_panic_handler::{{closure}}::hd2798398a2fd9077
   8:        0x101a72720 - std::sys_common::backtrace::__rust_end_short_backtrace::h9201cc364dbb8a23
   9:        0x101a736c4 - _rust_begin_unwind
  10:        0x101ae6658 - core::panicking::panic_fmt::h4d5168028d4c43c7
  11:        0x101ae6624 - core::option::expect_failed::h055bb418ffad3409
  12:        0x101a307e0 - clap::completions::zsh::get_args_of::hccddb7dce72db024
  13:        0x101a2e9cc - clap::completions::zsh::get_subcommands_of::hcc45c115cfb61b53
  14:        0x101a2ea74 - clap::completions::zsh::get_subcommands_of::hcc45c115cfb61b53
  15:        0x100fe7e38 - clap::completions::zsh::ZshGen::generate_to::hd44dc13d9aa9823e
  16:        0x101087be4 - clap::completions::ComplGen::generate::h51a40881ae71e1f4
  17:        0x101031b14 - clap::app::App::gen_completions_to::heb85530fe8b8da04
  18:        0x100ff290c - solana_cli::cli::parse_command::h2a54377c749a2a68
  19:        0x100f01598 - solana::main::hd21846070d93d582
  20:        0x100f0c5e0 - std::sys_common::backtrace::__rust_begin_short_backtrace::h0c4665b679d3c185
  21:        0x100f0b9f8 - std::rt::lang_start::{{closure}}::hf78f1ec8a3da1308
  22:        0x101a6827c - std::rt::lang_start_internal::h5b246d44f1526226
  23:        0x100f0b9dc - std::rt::lang_start::h7c43e30160d78765
  24:        0x100f02f5c - _main
```

#### Proposed Solution

Further investigation is needed to determine how this can be patched in Agave whilst remaining on clap v2.33.1

### PR DESCRIPTION
**Pull request by zilayo**
#### Problem

`solana completions -s zsh` currently panics when trying to generate zsh completions.

The root cause is the below code which defines a conflicting arg `buffer_authority` for `solana program-v4 show`, however `buffer_authority` is not an argument in `program-v4 show`:

https://github.com/anza-xyz/agave/blob/fc0183d73477fc24ee4b7c46b80efdd44d4b9cf1/cli/src/program_v4.rs#L277-L283

This results in clap panicking due to `find_any_arg` returning `None`, but the calling macro uses `expect()`

https://github.com/clap-rs/clap/blob/v2.33.3/src/completions/macros.rs#L15
https://github.com/clap-rs/clap/blob/v2.33.3/src/app/parser.rs#L2168-L2179

#### Summary of Changes

- Replaced `.conflicts_with("buffer_authority")` with `.conflicts_with("authority")` in `program-v4 show`
- Added a unit test that ensures CLI completion works for all supported shells.

Fixes https://github.com/anza-xyz/agave/issues/2929

### CODE REVIEW

File: cli/src/program_v4.rs [hunk 1]
```diff
@@ -278,7 +278,6 @@ impl ProgramV4SubCommands for App<'_, '_> {
                             Arg::with_name("all")
                                 .long("all")
                                 .conflicts_with("account")
-                                .conflicts_with("buffer_authority")
```
Comment (t-nelson) [inline cli/src/program_v4.rs:281]: @pgarg66 it's supposed to be `.conflicts_with("authority")`, right?

Comment (joncinque) [reply cli/src/program_v4.rs:281]: Shall I push up that change so we can merge this? May as well fix this

Comment (pgarg66) [reply cli/src/program_v4.rs:281]: That's correct. It should've been the `authority`. Likely a copy-paste error from `program.rs`.
Thanks for catching it.

Comment (pgarg66) [reply cli/src/program_v4.rs:281]: Pushed the change to this PR.

**Review by joncinque — APPROVED** [review]
Looks good to me!
