### PR TITLE
Do not purge all bank snapshots after fastboot

### LINKED ISSUE #35431: Use case: Repeated `ledger-tool verify` from a downloaded snapshot and ledger
Repeatedly using ledger-tool starting from the same slot/snapshot with fastboot may/does not work.

From https://github.com/solana-labs/solana/pull/31921#issuecomment-1572387276

> You mentioned spinning up a validator to get your initial account set state. Another common workflow I'd say is grabbing a snapshot + blocks from some other source (copy from other node / pull from Google / etc), and then doing repeated verify runs locally. Am I accurate in believing that I could run `solana-ledger-tool verify` once without fast-boot which would unpack the snapshot, and then for subsequent `verify` runs, I'd be able use `--fast-boot` ?

### PR DESCRIPTION
**Pull request by brooksprumo**
#### Problem

Please see https://github.com/solana-labs/solana/issues/35431

#### Summary of Changes

Do *not* purge all bank snapshots after fastbooting.

Fixes https://github.com/solana-labs/solana/issues/35431

#### Additional Testing

I ran leger-tool built from this PR on a mnb bank snapshot and confirmed I was able to repeatably use fastboot. Yay!

What's also really cool, is now that the storages recycler has been removed, we can fastboot from *older* bank snapshots as well; not just the latest.

### CODE REVIEW

File: ledger/src/bank_forks_utils.rs [hunk 1]
```diff
@@ -297,15 +297,6 @@ fn bank_forks_from_snapshot(
...
             path: fastboot_snapshot.snapshot_path(),
         })?;
-
-        // If the node crashes before taking the next bank snapshot, the next startup will attempt
-        // to load from the same bank snapshot again.  And if `shrink` has run, the account storage
-        // files that are hard linked in bank snapshot will be *different* than what the bank
-        // snapshot expects.  This would cause the node to crash again.  To prevent that, purge all
-        // the bank snapshots here.  In the above scenario, this will cause the node to load from a
-        // snapshot archive next time, which is safe.
-        snapshot_utils::purge_all_bank_snapshots(&snapshot_config.bank_snapshots_dir);
```
Comment (brooksprumo) [inline ledger/src/bank_forks_utils.rs:307]: Now that #120 was merged, there are no more issues related to shrink. So this original concern has been mitigated.

Where was a second issue that purging all the bank snapshots here also fixed: https://github.com/solana-labs/solana/issues/35367. It has been fixed by #343, so now there are no more blockers to removing this code.

**Review by apfitzge — APPROVED** [review]
lgtm - `-` only PR!
