### PR TITLE
Configure snapshot usage as load and generate when creating snapshots

### LINKED ISSUE #11935: ledger-tool create-snapshot fails to create an incremental snapshot
#### Problem
During the devnet restart, we were unable to create an incremental snapshot for the cluster restart snapshot:
```
thread 'main' (2845122) panicked at /home/sol/src/agave/ledger-tool/src/main.rs:2181:25:
assertion failed: bank.accounts().accounts_db.latest_full_snapshot_slot().is_some()
```
This was attempted with the latest v4.0 tag.

State was not saved, but it was very easy to reproduce this:
- Run `solana-test-validator` for long enough to create a full snapshot
- Note the latest full snapshot slot `F`
- Run `agave-ledger-tool create-snapshot S --incremental ...` where `S > F`

#### Proposed Solution
Debug + fix. As noted, the issue was encountered with `4.0.0-beta.7` so a v4.0 BP is seemingly in order since `ledger-tool create-snapshot` is critical for cluster restarts

### PR DESCRIPTION
**Pull request by roryharr**
#### Problem
https://github.com/anza-xyz/agave/issues/11935
When creating a snapshot from the ledger tool, the full snapshot slot is not set. 

#### Summary of Changes
- Set the full snapshot slot on first snapshot configuration
- Added a test to verify the fix
-**Note** that the full path cannot be done in a unit test as it requires running main from the ledger-tool. 

Tested independently by running the solana-test-validator for 120s and waiting for snapshots to be created.

Then:
```
agave-ledger-tool create-snapshot 339 --incremental --ledger test-ledger
```

Output without fix:
```
thread 'main' (869528) panicked at /private/tmp/agave-no-fix/ledger-tool/src/main.rs:2179:25:
assertion failed: bank.accounts().accounts_db.latest_full_snapshot_slot().is_some()
```

Output with fix:
```
datapoint: archive-snapshot-package slot=339i archive_format="TarZstd" duration_ms=1i incremental-snapshot-archive-size=42085i
Shred version: 1506
...
agave_ledger_tool ledger tool took 863ms
```

Fixes #
https://github.com/anza-xyz/agave/issues/11935

Bug is present on 4.0 and 3.1. Needs backporting.

### CODE REVIEW

File: ledger-tool/src/ledger_utils.rs [hunk 1]
```diff
@@ -174,12 +175,16 @@ pub fn load_and_process_ledger(
         }
         let usage = if arg_matches.is_present("no_snapshot") {
             SnapshotUsage::Disabled
+        } else if arg_matches.is_present("snapshot_slot") {
+            SnapshotUsage::LoadAndGenerate
```
Comment (brooksprumo) [inline ledger-tool/src/ledger_utils.rs:178]: Heh... what if someone is trying to generate a new snapshot from genesis. IOW, they do `ledger-tool create-snapshot --no-snapshot`. We'll have both "no_snapshot" and "snapshot_slot", and currently "no_snapshot" will win.

I think that's OK since I believe they'd need to create a full snapshot in this scenario (and couldn't create an incremental snapshot since they didn't load from a full) and setting the latest_full_snapshot_slot is technically optional.

And this should only matter on private and/or test clusters, since starting from genesis on any of the public clusters likely isn't a thing.

File: ledger-tool/src/ledger_utils.rs [hunk 2]
```diff
@@ -174,12 +175,16 @@ pub fn load_and_process_ledger(
...
         } else {
             SnapshotUsage::LoadOnly
         };
 
         SnapshotConfig {
             usage,
+            full_snapshot_archive_interval: SnapshotInterval::Disabled,
+            incremental_snapshot_archive_interval: SnapshotInterval::Disabled,
```
Comment (brooksprumo) [inline ledger-tool/src/ledger_utils.rs]: Optionally we could change `..SnapshotConfig::default()` to `..SnapshotConfig::new_load_only()` and then remove these new lines.

File: ledger-tool/src/ledger_utils.rs [hunk 3]
```diff
@@ -605,3 +610,99 @@ pub(crate) fn get_access_type(process_options: &ProcessOptions) -> AccessType {
...
+            .unwrap(),
+        );
+
+        // Setup the arguments such that a new snapshot will be generated from the loaded snapshot
+        let arg_matches = App::new("test")
+            .arg(
+                Arg::with_name("block_verification_method")
+                    .long("block-verification-method")
+                    .takes_value(true)
+                    .default_value("unified-scheduler"),
```
Comment (brooksprumo) [inline ledger-tool/src/ledger_utils.rs:661]: Why do we need a block verification method arg?

File: ledger-tool/src/ledger_utils.rs [hunk 4]
```diff
@@ -605,3 +610,99 @@ pub(crate) fn get_access_type(process_options: &ProcessOptions) -> AccessType {
...
+            )
+            .arg(
+                Arg::with_name("snapshot_slot")
+                    .long("snapshot-slot")
+                    .takes_value(true),
```
Comment (brooksprumo) [inline ledger-tool/src/ledger_utils.rs:666]: Optionally can also use `.index()` instead of `.long()`.

File: ledger-tool/src/ledger_utils.rs [hunk 5]
```diff
@@ -605,3 +610,99 @@ pub(crate) fn get_access_type(process_options: &ProcessOptions) -> AccessType {
...
+            )
+            .get_matches_from(vec!["test", "--snapshot-slot", "0"]);
+        let process_options = ProcessOptions {
+            halt_at_slot: Some(0),
```
Comment (brooksprumo) [inline ledger-tool/src/ledger_utils.rs]: Do we need to halt at a slot?

File: ledger-tool/src/ledger_utils.rs [hunk 6]
```diff
@@ -605,3 +610,99 @@ pub(crate) fn get_access_type(process_options: &ProcessOptions) -> AccessType {
...
+            archive_format,
+        )
+        .unwrap();
+
+        // Open the blockstore so load_and_process_ledger can pass it to process_blockstore.
+        let blockstore = Arc::new(
+            Blockstore::open_with_options(
+                ledger_path,
+                BlockstoreOptions {
+                    access_type: AccessType::PrimaryForMaintenance,
```
Comment (brooksprumo) [inline ledger-tool/src/ledger_utils.rs]: Why PrimaryForMaintenance here?

File: ledger-tool/src/ledger_utils.rs [hunk 7]
```diff
@@ -605,3 +610,99 @@ pub(crate) fn get_access_type(process_options: &ProcessOptions) -> AccessType {
...
+        let ledger_path = ledger_tmp.path();
+
+        let genesis_config = create_genesis_config(10_000).genesis_config;
+
+        // Create a bank from genesis and archive a full snapshot into the ledger directory.
+        let bank_snapshots_dir = ledger_path.join(BANK_SNAPSHOTS_DIR);
+        fs::create_dir_all(&bank_snapshots_dir).unwrap();
+        let bank = Bank::new_for_tests(&genesis_config);
+        bank.fill_bank_with_ticks_for_tests();
+        Bank::calculate_and_set_block_id_for_dcou(&bank);
```
Comment (brooksprumo) [inline ledger-tool/src/ledger_utils.rs:640]: This is fine, also can set the block_id to anything, since the specific value doesn't matter.

File: ledger-tool/src/ledger_utils.rs [hunk 8]
```diff
@@ -605,3 +610,99 @@ pub(crate) fn get_access_type(process_options: &ProcessOptions) -> AccessType {
...
+        let root_bank = bank_forks.read().unwrap().root_bank();
+
+        // Verify that latest_full_snapshot_slot is set, which matches the assert in main.rs
+        assert!(
+            root_bank
+                .accounts()
+                .accounts_db
+                .latest_full_snapshot_slot()
+                .is_some()
+        );
```
Comment (brooksprumo) [inline ledger-tool/src/ledger_utils.rs:688]: Yeah, this is what I was thinking we could reasonably test as well.

File: ledger-tool/src/ledger_utils.rs (hunk 6 above)
Comment (roryharr) [reply ledger-tool/src/ledger_utils.rs]: This matches what would be used when running in this configuration. get_access_type would return PrimaryForMaintenance when loading a snapshot given that use_snapshot_archives_at_startup is set to WhenNewest

Otherwise the default is Primary.

File: ledger-tool/src/ledger_utils.rs (hunk 3 above)
Comment (roryharr) [reply ledger-tool/src/ledger_utils.rs:661]: It's required in load_and_process_ledger:
```
    let block_verification_method = value_t_or_exit!(
        arg_matches,
        "block_verification_method",
        BlockVerificationMethod
    );
    ```

File: ledger-tool/src/ledger_utils.rs (hunk 2 above)
Comment (roryharr) [reply ledger-tool/src/ledger_utils.rs]: Yup, will do.

File: ledger-tool/src/ledger_utils.rs (hunk 1 above)
Comment (roryharr) [reply ledger-tool/src/ledger_utils.rs:178]: Is that intended to work? I can't get the command to run at all: 
```
mac:debug roryharris$ ./agave-ledger-tool --ledger ./new_ledger/ create-snapshot --no-snapshot
error: The argument '--no-snapshot' cannot be used with '--snapshot-archive-format <ARCHIVE_TYPE>'

```

It looks like snapshot-archive-format is always defined (pre-existing bug)

Comment (brooksprumo) [reply ledger-tool/src/ledger_utils.rs:178]: > Is that intended to work?

No idea! Looks like multiple args have "conflicts with" for no_snapshot, so seems like were safe.

---

As far as _why_ would anyone want to do this, the only contrived example I could think of is starting up a new cluster, letting it run for a bit, stopping it after it created snapshots on its own, and then using ledger-tool to create a snapshot for a slot *older* than any of the current snapshots. 

Doesn't seem like a big deal, as in that scenario the user could just move the existing snapshots out of the way to force starting up from genesis.

File: ledger-tool/src/ledger_utils.rs (hunk 3 above)
Comment (brooksprumo) [reply ledger-tool/src/ledger_utils.rs:661]: Hah, got it. Thanks!

File: ledger-tool/src/ledger_utils.rs (hunk 6 above)
Comment (brooksprumo) [reply ledger-tool/src/ledger_utils.rs]: Ok, that's fine. Mainly thinking along the lines of keeping unit tests simple and the minimal configuration necessary. If the default blockstore options worked here, then that'd also save a few lines.

**Comment by roryharr** [comment]
Had to rebase

**Review by brooksprumo — APPROVED** [review]
:shipit:

**Comment by roryharr** [comment]
> :shipit:

Should I wait on steve?

**Comment by brooksprumo** [comment]
> Should I wait on steve? 

@steviez would you like to review before merging?

File: ledger-tool/src/ledger_utils.rs (hunk 3 above)
Comment (steviez) [reply ledger-tool/src/ledger_utils.rs:661]: Had same question before seeing Brooks asked it ha - including it looks good for this PR but we can probably relax the exit-if-set behavior in a subsequent PR. I think blockstore-processor is fully deprecated now (maybe not fully ripped tho)

**Review by steviez — APPROVED** [review]
Thanks for the clear before+after & unit test; LGTM !

> would you like to review before merging?

You two locked in on the issue pretty quickly so I was pretty confident you two had it covered. Regardless, I appreciate you asking and gave this a read through so LGTM. Might as well look as I'll be reviewing the BP too 😆

**Comment by brooksprumo** [comment]
> Might as well look as I'll be reviewing the BP too

Yah, this was my thought too 🤘
