### PR TITLE
block-prioritization-fee metrics update

### LINKED ISSUE #6948: [metrics] block_prioritization_fee::total_prioritiziation_fee is incorrect
#### Problem
Sender sends this, setting `transaction_fee` to the cu_price.
```rust
                self.sender
                    .send(CacheServiceUpdate::TransactionUpdate {
                        slot: bank.slot(),
                        bank_id: bank.bank_id(),
                        transaction_fee: compute_budget_limits.compute_unit_price,
                        writable_accounts,
                    })
```

On receiving side, this is what gets accumulated into `total_prioritization_fee`.
This makes no sense to accumulate in this way, and the name is misleading for the value.

#### Proposed Solution
- Send over actual transaction fee

### PR DESCRIPTION
**Pull request by tao-stones**
#### Problem
`block-prioritization-fee` metrics reports data incorrectly:
- `min_prioritization_fee` is actually min of `compute_unit_price`, denominated in `micro-lamports`
- `max_prioritization_fee` is actually max of `compute_unit_price`, denominated in `micro-lamports`
- `total_prioritization_fee` is the sum of all non-vote transaction's `compute_unit_price`, which is misleading.

#### Summary of Changes
- Replace `[min|max]-prioritization-fee` with `[min|max]-compute-unit-price` to truly reflect the data points are raw cu price user set in `micro-lamports`;
- `total-prioritization-fee` is updated to report the sum of all landed transactions' prioritization fee (eg `compute_unit_price * compute_unit_limit`).
- Added an additional counter datapoint `block_prioritization_fee_counters.total_calculate_priotitization_fee_elapsed_us` to monitor time spent on calculate prioritization fees.

Fixes #6948

### CODE REVIEW

File: runtime/src/prioritization_fee_cache.rs [hunk 1]
```diff
@@ -233,11 +248,27 @@ impl PrioritizationFeeCache {
...
+                let (transaction_fee, calculate_transaction_fee_us) = measure_us!({
+                    solana_fee::calculate_fee(
+                        sanitized_transaction,
+                        bank.get_lamports_per_signature() == 0,
+                        bank.fee_structure().lamports_per_signature,
+                        solana_fee_structure::FeeBudgetLimits::from(compute_budget_limits)
+                            .prioritization_fee,
+                        solana_fee::FeeFeatures::from(bank.feature_set.as_ref()),
+                    )
+                });
```
Comment (tao-stones) [inline runtime/src/prioritization_fee_cache.rs:254]: Making additional fee calculation in hot path might be an issue, reporting its `us`, testing in testnet

File: runtime/src/prioritization_fee.rs [hunk 2]
```diff
@@ -23,22 +23,22 @@ struct PrioritizationFeeMetrics {
     // Count of attempted update on finalized PrioritizationFee
     attempted_update_on_finalized_fee_count: Saturating<u64>,
 
-    // Total prioritization fees included in this slot.
-    total_prioritization_fee: Saturating<u64>,
+    // Total transaction fees of non-vote transactions included in this slot.
+    total_non_vote_transaction_fee: Saturating<u64>,
```
Comment (tao-stones) [inline runtime/src/prioritization_fee.rs]: vote transactions are filtered out early, so only non-vote-transaction-fees are accumulated for confirmed blocks, which probably is the right thing to look at when analyzing prioritization fee behaviors

File: runtime/src/prioritization_fee.rs [hunk 3]
```diff
@@ -23,22 +23,22 @@ struct PrioritizationFeeMetrics {
...
 
-    // The minimum prioritization fee of prioritized transactions in this slot.
-    min_prioritization_fee: Option<u64>,
+    // The minimum compute unit price of prioritized transactions in this slot.
+    min_compute_unit_price: Option<u64>,
```
Comment (tao-stones) [inline runtime/src/prioritization_fee.rs:30]: the `min|max_compute_unit_price`s are reported as sanitized raw value, in `micro-lamports`; vs above `total_non_vote_transaction_fee` is reported in `lamports`

File: runtime/src/prioritization_fee_cache.rs (hunk 1 above)
Comment (tao-stones) [reply runtime/src/prioritization_fee_cache.rs:254]: metrics reported from devbox indicates near `0 us`

**Comment by tao-stones** [comment]
testnet reports on internal-metrics: 
image

**Comment by tao-stones** [comment]
note: `block_min_prioritization_fee` is obsoleted, removing it in separate pr #6973

File: runtime/src/prioritization_fee.rs (hunk 2 above)
Comment (apfitzge) [reply runtime/src/prioritization_fee.rs]: I'd actually be in favor of removing this field of the metric entirely.
We should not re-calculate the costs just to get a metric.

Each bank has the fee-details on it. We should report those **somewhere**, though it doesn't necessarily have to be in this datapoint.

File: runtime/src/prioritization_fee_cache.rs (hunk 1 above)
Comment (apfitzge) [reply runtime/src/prioritization_fee_cache.rs:254]: Yeah I don't like the additional work here.

It's also worth noting that I've had a WIP PR to make `PrioritizationFeeCache` rpc-only - we don't need to do any of this on a block-producing node; but then we'd lose the metrics.

See my other comment on reporting all fees.

File: runtime/src/prioritization_fee.rs (hunk 2 above)
Comment (apfitzge) [reply runtime/src/prioritization_fee.rs]: A good place might be in the same loop as cost-reporting. and we report with a tag is_leader in a similar way.

wdyt?

File: runtime/src/prioritization_fee_cache.rs (hunk 1 above)
Comment (tao-stones) [reply runtime/src/prioritization_fee_cache.rs:254]: I felt the same. Was focusing on Trent's particular use case, when one is curious about how cu-price is bidding up, it helps to put total fee collected as ref point. But yea, I don't love to have to calculate fee again here just for reporting. 

One benefit of reporting here vs from cost-tracking is, here only report when block is opportunistically confirmed. Wondering if adding fee to transaction meta is a good idea - I chatted about it before, don't remember why we didn't do it.

Comment (apfitzge) [reply runtime/src/prioritization_fee_cache.rs:254]: but we won't report this on building nodes if we make prio-fee-cache optional (we should).

Comment (t-nelson) [reply runtime/src/prioritization_fee_cache.rs:254]: > we don't need to do any of this on a block-producing node; but then we'd lose the metrics

i am once again asking for separate metrics infra for objective block statistics

bernie-i-am-once-again-asking

**Comment by t-nelson** [comment]
assuming 992b0f8 is purely cosmetic?

File: runtime/src/prioritization_fee_cache.rs (hunk 1 above)
Comment (t-nelson) [reply runtime/src/prioritization_fee_cache.rs:254]: on a more serious note... presumably we've already calculated the fees by now? can we not schlepp it along as metadata somewhere?

**Comment by tao-stones** [comment]
> assuming 992b0f8 is purely cosmetic?

Yes, only renaming "_prioritization_fee" to "_compute_unit_price"

File: runtime/src/prioritization_fee_cache.rs (hunk 1 above)
Comment (tao-stones) [reply runtime/src/prioritization_fee_cache.rs:254]: How about this: `block_prioritization_fee` to have `total_prioritization_fee` that sums all prioritization fees collected in a block (e.g., sum(cu_price * cu_limit), no need to recalculate transaction fee, but one additional `*` op). Alongside `[min|max]_compute_unit_price`, it gives a clearer picture about fee market. `total_transaction_fee` can be tracked separately if needed.

Comment (tao-stones) [reply runtime/src/prioritization_fee_cache.rs:254]: > on a more serious note... presumably we've already calculated the fees by now? can we not schlepp it along as metadata somewhere?

I suggested same early too. But Andrew has a good point: prio-fee-cache can be optional. I like  b7c6fa7fd1d6e720a5fa4bba66846bad45ae17e0 that prio-fee metrics only concern prio fee (not transaction fee, nor signature counts). It reports total priority fee collected in a block.

Comment (apfitzge) [reply runtime/src/prioritization_fee_cache.rs:254]: to be clear, it's not be optional right now, but i wanted to make it optional sometime recently because doing the hashmap stuff is pointless for a non-rpc, it's never accessible

Comment (apfitzge) [reply runtime/src/prioritization_fee_cache.rs:254]: it's not separate infra, but the cost tracking is currently where we report other objective block facts around the cost. I feel it makes sense to just lop it near there for now so we have semething without reinventing a metric system.

Comment (t-nelson) [reply runtime/src/prioritization_fee_cache.rs:254]: i mostly want the separate infra 'cause 5000 identical datapoints is kinda useless load on the metrics db

Comment (apfitzge) [reply runtime/src/prioritization_fee_cache.rs:254]: agreed, but i feel we should have this metric asap even if repeated. then can figure out how we want to report going forward separately, but don't lose data time

Comment (tao-stones) [reply runtime/src/prioritization_fee_cache.rs:254]: Agree. Do we have objection of reporting `total_priority_fee` at cost of one multiplying (eg `FeeBudgetLimits::from(compute_budget_limits)`)? 

Can add total transaction fee reporting at Cost Tracker separately.

Comment (apfitzge) [reply runtime/src/prioritization_fee_cache.rs:254]: that's fine

**Comment by tao-stones** [comment]
Here’s a snapshot of a few minutes of data from mainnet-beta:

- Orange line shows the total prioritization fees collected (in lamports).
- Blue line represents the max compute unit price (in micro-lamports).

Observed a spike in max-cu-price that did not have similar effect in total prioritization fees. This suggests the spike may have been driven by outlier transactions, rather than a broad fee market up-bidding.

image

**Review by apfitzge — APPROVED** [review]

**Review by t-nelson — APPROVED** [review]
