### PR TITLE
cli: Print error during `program close`

### LINKED ISSUE #10638: solana program close --buffers  ->  fails silently and shows no buffers to close
#### Problem

```bash
virla@NyanNyanKyun:~/repos/candy_forge$ solana balance
0.00089296 SOL

virla@NyanNyanKyun:~/repos/candy_forge$ solana program close --buffers

Buffer Address                               | Authority                                    | Balance

virla@NyanNyanKyun:~/repos/candy_forge$ solana balance
1.00089296 SOL

virla@NyanNyanKyun:~/repos/candy_forge$ solana program close --buffers

Buffer Address                               | Authority                                    | Balance
Gf8CoqggbCisM6dajhqV5oKz82pEsdru1cEfCc5J5TvX | oFbnfSYXYsH5C6Hv2VTGqYDo83xY3Gr1mmNFG2EdDiE  | 13.60889496 SOL
```

i had a unclosed buffer

tried to close it the first time

it failed silently. upon a manual simulation this is what the error looks like:

```bash
Failed to close buffer Gf8CoqggbCisM6dajhqV5oKz82pEsdru1cEfCc5J5TvX: Close failed: RPC response error -32002: Transaction simulation failed: Transaction results in an account (0) with insufficient funds for rent;
```

send myself 1 sol

2nd time it went through with the close

#### Proposed Solution

Print an error letting the user know there are unclosed buffers but the simulations to close them failed.

### PR DESCRIPTION
**Pull request by MrCatnip**
#### Problem

If user has no realistic (very small) sol balance and unclosed buffers

solana program close --buffers

will fail silently and just convey to the user that there's no buffers to close

#### Summary of Changes

Instead of printing nothing print the unclosed buffers with their corresponding error message.

Fixes [solana program close --buffers -> fails silently if there's no valid amount of solana in the wallet #10638](https://github.com/anza-xyz/agave/issues/10638)

### CODE REVIEW

File: cli/src/program.rs [hunk 1]
```diff
@@ -2430,9 +2430,18 @@ async fn process_close(
...
         .await?;
 
+        if buffers.buffers.is_empty() {
+            return Ok(config
+                .output_format
+                .formatted_string(&CliUpgradeableBuffers {
+                    buffers: vec![],
+                    use_lamports_unit,
+                }));
+        }
```
Comment (joncinque) [inline cli/src/program.rs]: Can you remove this? It isn't necessary

File: cli/src/program.rs [hunk 2]
```diff
@@ -2441,11 +2450,25 @@ async fn process_close(
...
         }
+
+        if closed.is_empty() && !buffers.buffers.is_empty() {
+            return Err(format!(
+                "Failed to close any buffers. Found {} buffer(s) to close, but all operations failed. \
+                 Check the error messages above for details.",
+                buffers.buffers.len()
+            )
+            .into());
+        }
```
Comment (joncinque) [inline cli/src/program.rs]: Can you remove this too? It's not providing much more info, the other print is the real useful one

**Review by joncinque — COMMENTED** [review]
Printing the error makes sense to me, thanks!

For your specific issue, I don't think a low SOL balance was the problem. A close transaction shouldn't cost more than 10k lamports, and your account had much more than that.

File: cli/src/program.rs (hunk 1 above)
Comment (MrCatnip) [reply cli/src/program.rs]: 👍

File: cli/src/program.rs (hunk 2 above)
Comment (MrCatnip) [reply cli/src/program.rs]: 👍

**Comment by MrCatnip** [comment]
Reproduced this error, same parameters, with logging now:

```bash
virla@NyanNyanKyun:~/repos/agave$ solana balance
0.00089296 SOL
virla@NyanNyanKyun:~/repos/agave$ cargo run --bin solana -- program close --buffers
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.35s
     Running `target/debug/solana program close --buffers`
Failed to close buffer yxUMxWVv88rzrkjCvumQNAzBhUrviqz54BwekErHRxt: Close failed: RPC response error -32002: Transaction simulation failed: Transaction results in an account (0) with insufficient funds for rent; 

Buffer Address                               | Authority                                    | Balance

virla@NyanNyanKyun:~/repos/agave$ solana balance
1.00089296 SOL
virla@NyanNyanKyun:~/repos/agave$ cargo run --bin solana -- program close --buffers
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.34s
     Running `target/debug/solana program close --buffers`

Buffer Address                               | Authority                                    | Balance
yxUMxWVv88rzrkjCvumQNAzBhUrviqz54BwekErHRxt  | oFbnfSYXYsH5C6Hv2VTGqYDo83xY3Gr1mmNFG2EdDiE  | 13.60889496 SOL
```

**Comment by MrCatnip** [comment]
Thanks for the input, ready for review.

**Comment by joncinque** [comment]
> Failed to close buffer yxUMxWVv88rzrkjCvumQNAzBhUrviqz54BwekErHRxt: Close failed: RPC response error -32002: Transaction simulation failed: Transaction results in an account (0) with insufficient funds for rent; 

Oh right of course, rent! Thanks for posting that :pray:

**Review by joncinque — APPROVED** [review]
Thanks for your contribution!
