### PR TITLE
Cli: withdraw available stake with keyword

### LINKED ISSUE #34738: Shortcut method to withdraw all MEV (any unstaked SOL) from stake accounts
#### Problem
MEV rewards from Jito are airdropped to stake accounts as excess, unstaked SOL.

Stake accounts receiving those airdrops will see something similar to this:
```
% solana stake-account 74JwpCE61kJMdxaf9j2X5EpnkS1CiCoqoEoJPx5MBdCe
Balance: 97.256865087 SOL
Rent Exempt Reserve: 0.00228288 SOL
Delegated Stake: 96.742412791 SOL
Active Stake: 96.742412791 SOL
```

Note the difference between the Balance of the stake account and Active Stake.

It looks like you could withdraw the excess SOL using existing functions, but this doesn't appear to work as the ALL keyword implies the full balance of the account:
```
% solana withdraw-stake --help
solana-withdraw-stake
Withdraw the unstaked SOL from the stake account
```
```
    <AMOUNT>                   The amount to withdraw from the stake account, in SOL; accepts keyword ALL
```
```
% solana withdraw-stake 74JwpCE61kJMdxaf9j2X5EpnkS1CiCoqoEoJPx5MBdCe HKCgzSzVT92ZUDLj6hTeJnRgY6objrPDAbVr3xyxR6kY ALL
Error: RPC response error -32002: Transaction simulation failed: Error processing Instruction 0: insufficient funds for instruction [2 log messages]
```
(The client keypair is funded and specifying the --fee-payer doesn't have any effect)
```
% solana balance HKCgzSzVT92ZUDLj6hTeJnRgY6objrPDAbVr3xyxR6kY.json
102.301790691 SOL

% solana withdraw-stake --fee-payer HKCgzSzVT92ZUDLj6hTeJnRgY6objrPDAbVr3xyxR6kY.json stake-account.json $(solana address) ALL
Error: RPC response error -32002: Transaction simulation failed: Error processing Instruction 0: insufficient funds for instruction [2 log messages]
```

#### Proposed Solution
Add a new keyword like AVAILABLE, EXCESS, or UNSTAKED to calculate the difference between a stake accounts Balance and Active Stake.

This makes it very easy to withdraw all unstaked SOL from stake accounts. Before Jito, this wouldn't be necessary - but with MEV being airdropped and excess SOL in stake accounts, this would be incredibly useful.

### PR DESCRIPTION
**Pull request by CriesofCarrots**
#### Problem
It is difficult for users to withdraw just the available lamports from an active stake account.
See https://github.com/solana-labs/solana/issues/34738

#### Summary of Changes
Picking up #441

Add `AVAILABLE` keyword for `solana withdraw-stake` and plumb into spend-utils
Add integration tests for both `ALL` and `AVAILABLE`; the vast majority of the line additions are tests or updates to tests.

I preserved najeal's commits for credit, but if you'd prefer I rework the commits to facilitate by-commit review, let me know.

Closes #441
Fixes https://github.com/solana-labs/solana/issues/34738

### CODE REVIEW

File: cli/src/spend_utils.rs [hunk 1]
```diff
@@ -102,15 +111,42 @@ where
...
-        let from_rent_exempt_minimum = if amount == SpendAmount::RentExempt {
-            let data = rpc_client.get_account_data(from_pubkey)?;
-            rpc_client.get_minimum_balance_for_rent_exemption(data.len())?
-        } else {
-            0
-        };
+        let account = rpc_client
+            .get_account_with_commitment(from_pubkey, commitment)?
+            .value
+            .unwrap_or_default();
```
Comment (CriesofCarrots) [inline cli/src/spend_utils.rs:120]: Please look at this change especially. (Last commit)
`unwrap_or_default()` on `get_account_with_commitment()` for accounts that do not exist should yield a balance of 0 lamports and empty data, matching what would have been returned by `get_balance_with_commitment()` and `get_account_data()`.

I think we could probably get away with removing the `with_commitment`, since the `RpcClient` should be constructed with the configured commitment, but I ultimately decided to retain the approach already in use here. We could fix in a follow-up.

**Comment by CriesofCarrots** [comment]
Sigh, failing test is due to the really dumb defaults for MockSender (edit) ✅ fixed

**Comment by CriesofCarrots** [comment]
@joncinque , should I bother rebasing this? Or not something you care to bother with?

**Comment by joncinque** [comment]
> @joncinque , should I bother rebasing this? Or not something you care to bother with?

That's some fun ESP, I was just starting to look at this. Please rebase -- GitHub isn't mentioning any conflicts, so I'll go forward with reviewing

File: cli/src/spend_utils.rs (hunk 1 above)
Comment (joncinque) [reply cli/src/spend_utils.rs:120]: This makes sense to me, and agreed on avoiding the commitment change in this PR

File: cli/src/spend_utils.rs [hunk 2]
```diff
@@ -102,15 +111,40 @@ where
...
+            let state = stake::get_account_stake_state(
+                rpc_client,
+                from_pubkey,
+                account,
+                true,
+                None,
+                false,
+                None,
+            )?;
+            let mut sub_rent_exempt = false;
```
Comment (joncinque) [inline cli/src/spend_utils.rs]: nit: I got so confused about this variable name, since I thought `sub` meant that the account was somehow below rent-exemption. `subtract_rent_exempt_minimum` maybe?

File: cli/src/spend_utils.rs [hunk 3]
```diff
@@ -181,12 +215,14 @@ where
...
-                    SpendAmount::All | SpendAmount::RentExempt => 0,
+                    SpendAmount::All | SpendAmount::Available | SpendAmount::RentExempt => 0,
                 }
             } else {
                 match amount {
                     SpendAmount::Some(lamports) => lamports,
-                    SpendAmount::AllForAccountCreation { .. } | SpendAmount::All => from_balance,
+                    SpendAmount::AllForAccountCreation { .. }
+                    | SpendAmount::All
+                    | SpendAmount::Available => from_balance,
```
Comment (joncinque) [inline cli/src/spend_utils.rs]: nit: It's slightly confusing that `from_balance` doesn't necessarily mean the balance in the `from` account.

We could maybe rename this to `from_balance_available` or `from_balance_transferable`, but I don't feel great about either option.

**Review by joncinque — COMMENTED** [review]
Looks great to me! Just a couple of nits on variable naming, then we can get this in.

Apologies for the big delay on reviewing

File: cli/src/spend_utils.rs (hunk 3 above)
Comment (CriesofCarrots) [reply cli/src/spend_utils.rs]: I went with `from_account_transferable_balance`... thoughts?

**Comment by CriesofCarrots** [comment]
Shouldn't I still have CI privileges, due to the [Contributor Access Policy](https://github.com/anza-xyz/contributor-access-policy/blob/main/access-control-list/agave-member-access.md)? cc @yihau

**Comment by yihau** [comment]
@CriesofCarrots just sent an invitation. you were removed from the org 🙈

**Review by joncinque — APPROVED** [review]
Looks great, thanks! And sorry again for the delay
