### PR TITLE
bugfix: verifies base3 cert without any primary votes

### LINKED ISSUE #11607: Verification of base3 certs where primary is empty fails
It seems like if we have a base3 cert where the primary votes are empty then verification fails.  This is still a valid cert and its verification should succeed.

### PR DESCRIPTION
**Pull request by akhi3030**
#### Problem

It is perfectly reasonable to get a base3 cert without any primary votes and just fallback votes.  Currently, `bls-cert-verify` fails to verify such certs.

#### Summary of Changes

Adds a test to valid that indeed this is currently failing and updates the code to verify such certs.

Fixes #11607

### CODE REVIEW

File: bls-cert-verify/src/cert_verify.rs [hunk 1]
```diff
@@ -344,4 +347,30 @@ mod test {
             Error::VerifySig(BlsError::PointConversion)
         );
     }
+
+    #[test]
+    fn base3_cert_with_no_primary_verifies() {
```
Comment (akhi3030) [inline bls-cert-verify/src/cert_verify.rs:352]: I asserted that this test fails if the above code has not been modified.

**Review by AshwinSekar — APPROVED** [review]
