### PR TITLE
AppendVec::new_from_storage() does sanitization if len and capacity do not match

### LINKED ISSUE #6797: minimized ledgers not working on v2.3.1
Not able to get minimized snapshots loaded with agave v2.3.1

### PR DESCRIPTION
**Pull request by brooksprumo**
#### Problem

Minimized snapshots created with older versions of ledger-tool can have storages with a capacity (file size) larger than their len (number of bytes) (see #6797 for an example). This is no longer an issue in master, as `shrink` (which is used to write the new, minimized storages) now sets the correct file size for new storages.

After merging #6552, it was no longer possible to open those snapshots with storages that have mismatched capacity and len.

#### Summary of Changes

At startup when rebuilding storages, if the capacity and len mismatch, fall back to the old/slow impl that does the full sanitization of the storage file.

Fixes #6797

Note, since #6552 was backported to v2.3, I think we should also backport this to v2.3.

### CODE REVIEW

File: accounts-db/src/append_vec.rs [hunk 1]
```diff
@@ -467,9 +464,26 @@ impl AppendVec {
         {
             Ok(new)
         } else {
-            Err(AccountsFileError::AppendVecError(
-                AppendVecError::SizeMismatch(new.path.clone(), current_len, new.file_size),
```
Comment (HaoranYi) [inline accounts-db/src/append_vec.rs:471]: nit: do we still need SizeMismatch error?

**Review by HaoranYi — APPROVED** [review]
nice debugging. 
lgtm.

File: accounts-db/src/append_vec.rs (hunk 1 above)
Comment (brooksprumo) [reply accounts-db/src/append_vec.rs:471]: Nope. This was the only usage, which is why I've removed the SizeMismatch error variant.

Comment (HaoranYi) [reply accounts-db/src/append_vec.rs:471]: ok coo.

**Comment by roryharr** [comment]
When was shrink fixed to store the correct size? 

And how long will backwards compatibility be required? Is it worth adding a test to ensure this path doesn't break again?

**Comment by brooksprumo** [comment]
> When was shrink fixed to store the correct size?

There's been multiple fixes over the years. I thought it had been fixed for a while. Firedancer reported the issue here https://github.com/anza-xyz/agave/issues/6797, so it depends on what version they used to create that minimized snapshot.

---

> And how long will backwards compatibility be required?

We only need to guarantee compatibility between adjacent versions. But, no need to break folks unnecessarily. Since the firedancer minimized snapshot worked in v2.2, we should let it continue to work at least for v2.3.


> Is it worth adding a test to ensure this path doesn't break again?

Maybe? We'd have to manually create invalid storage files to do that (invalid w.r.t. cap vs len). I'm currently adding a fix to the snapshot minimization that will include a new test that will actually create a minimized snapshot and then load it.

**Comment by brooksprumo** [comment]
@anza-xyz/backport-reviewers FYI, intending to backport this one. Tagging to get eyes on it before merging to master.

**Review by t-nelson — APPROVED** [review]

**Review by roryharr — APPROVED** [review]
