### PR TITLE
fix: use proper serialization for versioned messages in get_fee_for_m…

### LINKED ISSUE #7563: RPC: Invalid serialiation for versioned messages in `get_fee_for_message`
If I were to use `get_fee_for_message` for a versioned message with an Address Lookup Table

```rust
use solana_message::v0::Message;

    let base_64_message = "AQABArJF/NYhcsDakp7Mn/v3nY4n7fZrhDHwZO6htys5ifCUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbQk8iO8n0RxkPJnwMn+6P3Nke6Itp61AnVqOx+qtaowEBAgACDAIAAADoAwAAAAAAAAHmBvllqrvqRtv+7D3SKk8iHBHqERdPvZZQELSj3pCjhQEAAA==";
    let bytes = BASE64_STANDARD.decode(base_64_message).unwrap();
    let decoded_message: Message = bincode::deserialize(&bytes).unwrap();
    println!("{}", BASE64_STANDARD.encode(bincode::serialize(&decoded_message).unwrap()));
    println!("{}", BASE64_STANDARD.encode(decoded_message.serialize()));
    match rpc_client.get_fee_for_message(&decoded_message).await {
        Ok(fee) => println!("{:#?}", fee),
        Err(err) => println!("Err: {:?}", err),
    };
```

I get an error:
```
Err: Error { request: Some(GetFeeForMessage), kind: RpcError(RpcResponseError { code: -32602, message: "invalid transaction message: index out of bounds", data: Empty }) }
```

It seems like there is an issue with serializing versioned messages using bincode::serialize in the rpc_client https://github.com/anza-xyz/agave/blob/338f1d82445e929625ea5a318467c8d8c79564bc/rpc-client/src/nonblocking/rpc_client.rs#L4734 

It differs from how `Message` gets serialized when we call `.serialize()` method - as it also adds `MESSAGE_VERSION_PREFIX`

https://github.com/anza-xyz/solana-sdk/blob/9decd857f019cc4c8dd89f4b3811ea56b0ac5c8e/message/src/versions/v0/mod.rs#L302

And so it leads to us having 2 completely different base64 encoded messages:

- This one I got by using bincode::serialize, leads to `index out of bounds`;
```
AQABArJF/NYhcsDakp7Mn/v3nY4n7fZrhDHwZO6htys5ifCUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbQk8iO8n0RxkPJnwMn+6P3Nke6Itp61AnVqOx+qtaowEBAgACDAIAAADoAwAAAAAAAAHmBvllqrvqRtv+7D3SKk8iHBHqERdPvZZQELSj3pCjhQEAAA==
``` 

- This one I got by using `.serialize()` of the `Message` and we get a correct response from getFeeForMessage if we try to query it:
```
gAEAAQKyRfzWIXLA2pKezJ/7952OJ+32a4Qx8GTuobcrOYnwlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG0JPIjvJ9EcZDyZ8DJ/uj9zZHuiLaetQJ1ajsfqrWqMBAQIAAgwCAAAA6AMAAAAAAAAB5gb5Zaq76kbb/uw90ipPIhwR6hEXT72WUBC0o96Qo4UBAAA=
```

### PR DESCRIPTION
**Pull request by swarna1101**
# Fix versioned message serialization in `get_fee_for_message`

## Problem
`get_fee_for_message` was failing with "index out of bounds" errors when used with v0 messages containing Address Lookup Tables. The root cause was that `bincode::serialize()` doesn't include the `MESSAGE_VERSION_PREFIX` (0x80) required for v0 messages, causing the RPC endpoint to misinterpret the serialized message format.

## Solution
Added a `serialize_message()` method to the `SerializableMessage` trait that uses the proper native serialization for each message type. For v0 messages, this includes the required version prefix, while legacy messages remain unchanged. Updated `get_fee_for_message()` to use this new serialization method instead of `bincode::serialize()`.

The fix ensures that both legacy messages and v0 messages with Address Lookup Tables are properly serialized when calling `get_fee_for_message()`. Added comprehensive tests to verify the serialization behavior and ensure no regressions.

Closes #7563

Can you pls check this @KirillLykov @0xbrw

### CODE REVIEW

**Comment by 0xbrw** [comment]
@KirillLykov would you know the right person to review this?

**Comment by KirillLykov** [comment]
@steveluscher probably is the best one

**Comment by KirillLykov** [comment]
Also this PR seems to fix the problem, it introduces some additional code. I wonder if it is possible to reuse `serialize_and_encode`: it calls `let serialized = serialize(input)` and this input should implement `serde::Serialize`. It seems that both are implementing `serde::Serialize`, so it should call correctly method serialize of each. But maybe I don't get something

**Comment by swarna1101** [comment]
> Also this PR seems to fix the problem, it introduces some additional code. I wonder if it is possible to reuse `serialize_and_encode`: it calls `let serialized = serialize(input)` and this input should implement `serde::Serialize`. It seems that both are implementing `serde::Serialize`, so it should call correctly method serialize of each. But maybe I don't get something

Good point! The issue is that `serialize_and_encode` uses `bincode::serialize(input)` which calls the **serde serialization trait**, but for v0 messages we need the **native `serialize()` method** that includes the `MESSAGE_VERSION_PREFIX`.

The key difference:
- `bincode::serialize(&v0_message)` → No version prefix ❌ (causes "index out of bounds")  
- `v0_message.serialize()` → Includes `MESSAGE_VERSION_PREFIX` ✅ (works correctly)

We could modify `serialize_and_encode` to detect message types, but this would break its generic nature and risk affecting other use cases. This approach keeps the existing function unchanged while being explicit about using the proper serialization method for each message type.

**Comment by KirillLykov** [comment]
@swarna1101 Hm, I got you.
I wonder if there is a way to reuse here the code from https://github.com/anza-xyz/solana-sdk/blob/master/message/src/versions/mod.rs#L179 instead of introducing the new one?

PS CI fails with extra whitespaces: `git diff origin/master --check --oneline`

**Comment by swarna1101** [comment]
> Hm, I got you. I wonder if there is a way to reuse here the code from https://github.com/anza-xyz/solana-sdk/blob/master/message/src/versions/mod.rs#L179 instead of introducing the new one?
> 
> PS CI fails with extra whitespaces: `git diff origin/master --check --oneline`

I've refactored to use the existing `VersionedMessage` from `solana-sdk/message/src/versions/mod.rs#L179` instead of the custom trait. It uses proven serialization logic that handles `MESSAGE_VERSION_PREFIX`. Removed the unnecessary `SerializableMessage` trait entirely and updated `get_fee_for_message()` to work directly with `VersionedMessage`. Tests pass and whitespace issues fixed. 👍

File: rpc-client/src/nonblocking/rpc_client.rs [hunk 1]
```diff
@@ -4746,6 +4746,25 @@ where
     Ok(encoded)
 }
 
+fn serialize_and_encode_versioned_message(
```
Comment (KirillLykov) [inline rpc-client/src/nonblocking/rpc_client.rs]: Are you sure that we need a new `serialize_and_encode_versioned_message` function? It looks to me `serialize_and_encode` will work, won't it?

File: rpc-client/src/rpc_client.rs [hunk 2]
```diff
@@ -4254,4 +4258,145 @@ mod tests {
             assert_eq!(expected_result, result1);
         }
     }
+
+    #[test]
+    fn test_versioned_message_serialization_includes_prefix() {
+        use solana_message::{v0, Message as LegacyMessage, compiled_instruction::CompiledInstruction, v0::MessageAddressTableLookup, MessageHeader};
```
Comment (KirillLykov) [inline rpc-client/src/rpc_client.rs]: I think we typically avoid using function-level imports.

File: rpc-client/src/rpc_client.rs [hunk 3]
```diff
@@ -4254,4 +4258,145 @@ mod tests {
...
+
+        // Test that VersionedMessage serialization includes MESSAGE_VERSION_PREFIX
```
Comment (KirillLykov) [inline rpc-client/src/rpc_client.rs]: I would move this comment to be for the whole test, so above `#[test]`

File: rpc-client/src/nonblocking/rpc_client.rs [hunk 4]
```diff
@@ -4669,9 +4669,9 @@ impl RpcClient {
 
     pub async fn get_fee_for_message(
         &self,
-        message: &impl SerializableMessage,
+        message: &VersionedMessage,
     ) -> ClientResult<u64> {
-        let serialized_encoded = serialize_and_encode(message, UiTransactionEncoding::Base64)?;
+        let serialized_encoded = serialize_and_encode_versioned_message(message, UiTransactionEncoding::Base64)?;
```
Comment (KirillLykov) [inline rpc-client/src/nonblocking/rpc_client.rs]: Do you know if there are tests for this `get_fee_for_message` function? If they exist and easy to add a new one, I think it might be valuable to have tests for this function instead of serialization of `VersionedMessage` because the later lives in sdk.

File: rpc-client/src/rpc_client.rs (hunk 2 above)
Comment (swarna1101) [reply rpc-client/src/rpc_client.rs]: Removed all function-level use statements from the test functions since the required types are already imported in the test module's use block

File: rpc-client/src/rpc_client.rs (hunk 3 above)
Comment (swarna1101) [reply rpc-client/src/rpc_client.rs]: moved

File: rpc-client/src/nonblocking/rpc_client.rs (hunk 4 above)
Comment (swarna1101) [reply rpc-client/src/nonblocking/rpc_client.rs]: You're right that we should test the actual `get_fee_for_message` function rather than just serialization since `VersionedMessage` is already well-tested in the SDK.

Currently there aren't specific tests for `get_fee_for_message` - adding proper ones would need either integration tests with a real RPC server or mock-based tests.

Since this PR focuses on the serialization bug fix and our tests do validate the fix works (v0 messages get proper version prefix), I think they serve their purpose here. But I agree comprehensive function tests would be valuable as a follow-up.

Would you prefer adding mock tests in this PR or keeping this focused and doing function tests separately?

Comment (KirillLykov) [reply rpc-client/src/nonblocking/rpc_client.rs]: I would add a unit test with mock rpc as part of the bug fix (this one) but for backporting it to 2.3.x, it is might be better to make a follow up so this PR is without tests.

Comment (swarna1101) [reply rpc-client/src/nonblocking/rpc_client.rs]: got it, will be great if we can create an issue to track it, happy to do that

**Comment by steveluscher** [comment]
@jstarry, do you still have the versioned message stuff loaded into your head enough that this is a quick review for you?

**Review by steveluscher — DISMISSED** [review]
Your original approach of trying to teach `SerializableMessage` to do the right thing was less intrusive, and required fewer changes. I think the current version of this PR where you force folks to use `get_fee_for_message_with_legacy` sometimes and `get_fee_for_message` other times is worse.

With a few tweaks, wouldn't your original change work?

```diff
diff --git a/rpc-client/src/nonblocking/rpc_client.rs b/rpc-client/src/nonblocking/rpc_client.rs
index e4e1396abc..293228b07b 100644
--- a/rpc-client/src/nonblocking/rpc_client.rs
+++ b/rpc-client/src/nonblocking/rpc_client.rs
@@ -4671,7 +4671,8 @@ impl RpcClient {
         &self,
         message: &impl SerializableMessage,
     ) -> ClientResult<u64> {
-        let serialized_encoded = serialize_and_encode(message, UiTransactionEncoding::Base64)?;
+        let serialized = message.serialize();
+        let serialized_encoded = BASE64_STANDARD.encode(serialized);
         let result = self
             .send::<Response<Option<u64>>>(
                 RpcRequest::GetFeeForMessage,
diff --git a/rpc-client/src/rpc_client.rs b/rpc-client/src/rpc_client.rs
index bf42e2fb06..567fc44ba0 100644
--- a/rpc-client/src/rpc_client.rs
+++ b/rpc-client/src/rpc_client.rs
@@ -62,9 +62,19 @@ impl RpcClientConfig {
 
 /// Trait used to add support for versioned messages to RPC APIs while
 /// retaining backwards compatibility
-pub trait SerializableMessage: Serialize {}
-impl SerializableMessage for LegacyMessage {}
-impl SerializableMessage for v0::Message {}
+pub trait SerializableMessage {
+    fn serialize(&self) -> Vec<u8>;
+}
+impl SerializableMessage for LegacyMessage {
+    fn serialize(&self) -> Vec<u8> {
+        self.serialize()
+    }
+}
+impl SerializableMessage for v0::Message {
+    fn serialize(&self) -> Vec<u8> {
+        self.serialize()
+    }
+}
 
 /// Trait used to add support for versioned transactions to RPC APIs while
 /// retaining backwards compatibility
@@ -3803,6 +3813,7 @@ mod tests {
         serde_json::{json, Number},
         solana_account_decoder::encode_ui_account,
         solana_account_decoder_client_types::UiAccountEncoding,
+        solana_hash::Hash,
         solana_instruction::error::InstructionError,
         solana_keypair::Keypair,
         solana_rpc_client_api::client_error::ErrorKind,
```

**Comment by jstarry** [comment]
Ugh, looks like I introduced this bug in https://github.com/solana-labs/solana/pull/28217 because I didn't add proper tests, apologies!

I think that we should do a few things:
1. `impl SerializableMessage for VersionedMessage`
2. Add `fn version_prefix() -> Option<u8>` to `SerializableMessage` and impl it for `v0::Message`
3. Update `fn get_fee_for_message` to first serialize the version prefix if `is_some`

**Comment by jstarry** [comment]
@steveluscher I don't really understand how your suggestion would fix the issue. Where is the version prefix handled?

**Comment by steveluscher** [comment]
> @steveluscher I don't really understand how your suggestion would fix the issue. Where is the version prefix handled?

Here's a one-liner that applies the patch, after which you can hyperclick around the calls to `serialize()` in the `SerializableMessage` part. That'll lead you right to it.

```
cat << EOF | git apply
diff --git a/rpc-client/src/nonblocking/rpc_client.rs b/rpc-client/src/nonblocking/rpc_client.rs
index e4e1396abc..293228b07b 100644
--- a/rpc-client/src/nonblocking/rpc_client.rs
+++ b/rpc-client/src/nonblocking/rpc_client.rs
@@ -4671,7 +4671,8 @@ impl RpcClient {
         &self,
         message: &impl SerializableMessage,
     ) -> ClientResult<u64> {
-        let serialized_encoded = serialize_and_encode(message, UiTransactionEncoding::Base64)?;
+        let serialized = message.serialize();
+        let serialized_encoded = BASE64_STANDARD.encode(serialized);
         let result = self
             .send::<Response<Option<u64>>>(
                 RpcRequest::GetFeeForMessage,
diff --git a/rpc-client/src/rpc_client.rs b/rpc-client/src/rpc_client.rs
index bf42e2fb06..567fc44ba0 100644
--- a/rpc-client/src/rpc_client.rs
+++ b/rpc-client/src/rpc_client.rs
@@ -62,9 +62,19 @@ impl RpcClientConfig {
 
 /// Trait used to add support for versioned messages to RPC APIs while
 /// retaining backwards compatibility
-pub trait SerializableMessage: Serialize {}
-impl SerializableMessage for LegacyMessage {}
-impl SerializableMessage for v0::Message {}
+pub trait SerializableMessage {
+    fn serialize(&self) -> Vec<u8>;
+}
+impl SerializableMessage for LegacyMessage {
+    fn serialize(&self) -> Vec<u8> {
+        self.serialize()
+    }
+}
+impl SerializableMessage for v0::Message {
+    fn serialize(&self) -> Vec<u8> {
+        self.serialize()
+    }
+}
 
 /// Trait used to add support for versioned transactions to RPC APIs while
 /// retaining backwards compatibility
@@ -3803,6 +3813,7 @@ mod tests {
         serde_json::{json, Number},
         solana_account_decoder::encode_ui_account,
         solana_account_decoder_client_types::UiAccountEncoding,
+        solana_hash::Hash,
         solana_instruction::error::InstructionError,
         solana_keypair::Keypair,
         solana_rpc_client_api::client_error::ErrorKind,
EOF
```

**Comment by swarna1101** [comment]
Thanks a lot for all this discussions, I am checking them, let me get back

**Comment by jstarry** [comment]
> Here's a one-liner that applies the patch, after which you can hyperclick around the calls to serialize() in the SerializableMessage part. That'll lead you right to it.

Oh I see, using `v0::Message::serialize` instead of its `derive(Serialize)`

**Comment by steveluscher** [comment]
This PR has been rewritten, and a tight test case added to assert that what we're _sending_ to `getFeeForMessage` is the correct bytes. Ready for review.

**Review by KirillLykov — DISMISSED** [review]

**Comment by KirillLykov** [comment]
But it fails CI

File: rpc-client/src/rpc_client.rs [hunk 5]
```diff
@@ -4254,4 +4268,85 @@ mod tests {
...
+        let serialized_message_base64 = BASE64_STANDARD.encode(serialized_message);
+
+        let (sender, receiver) = unbounded();
+        thread::spawn(move || {
+            let rpc_addr = "0.0.0.0:0".parse().unwrap();
+            let mut io = IoHandler::default();
+            // Successful request
+            io.add_method("getFeeForMessage", move |params: Params| match params {
+                Params::Array(p) => {
+                    let first_element = p.get(0).unwrap();
```
Comment (KirillLykov) [inline rpc-client/src/rpc_client.rs]:
```suggestion
                    let first_element = p.first.unwrap();
```
To pacify clippy

File: rpc-client/src/rpc_client.rs [hunk 6]
```diff
@@ -4254,4 +4268,85 @@ mod tests {
...
+        let serialized_message_base64 = BASE64_STANDARD.encode(serialized_message);
+
+        let (sender, receiver) = unbounded();
+        thread::spawn(move || {
+            let rpc_addr = "0.0.0.0:0".parse().unwrap();
+            let mut io = IoHandler::default();
+            // Successful request
+            io.add_method("getFeeForMessage", move |params: Params| match params {
+                Params::Array(p) => {
+                    let first_element = p.first.unwrap();
```
Comment (steveluscher) [inline rpc-client/src/rpc_client.rs]:
```suggestion
                    let first_element = p.first().unwrap();
```

File: rpc-client/src/nonblocking/rpc_client.rs [hunk 7]
```diff
@@ -4671,7 +4671,8 @@ impl RpcClient {
         &self,
         message: &impl SerializableMessage,
     ) -> ClientResult<u64> {
-        let serialized_encoded = serialize_and_encode(message, UiTransactionEncoding::Base64)?;
```
Comment (KirillLykov) [inline rpc-client/src/nonblocking/rpc_client.rs:4674]: Isn't new code does the same as the function `serialize_and_encode` but just in place? I wonder if we even need this function if it is a 2 lines of code.

**Review by KirillLykov — APPROVED** [review]
the change itself looks good to me, left comment about the function `serialize_and_encode`.

File: rpc-client/src/nonblocking/rpc_client.rs (hunk 7 above)
Comment (steveluscher) [reply rpc-client/src/nonblocking/rpc_client.rs:4674]: Not exactly. `serialize_and_encode` does `bincode::serialize(thing)` whereas the change does `thing.serialize()`. I'm always happy inlining code, but that's a matter for a different PR.
