### PR TITLE
fix: `build-sbf` Home Directory Error on Windows

### LINKED ISSUE #35558: cargo build-sbf  Can't get home directory path: environment variable not found
image

### PR DESCRIPTION
**Pull request by KartikSoneji**
#### Problem
The `cargo-build-sbf` command is unable to find the home directory path of the user on Windows and throws an error.
Setting the `HOME` env variable with `set HOME=%USERPROFILE%` fixes the issue but has to be run on each terminal session.

```console
> cargo build-sbf
[2024-11-12T19:54:24.953753800Z ERROR cargo_build_sbf] Can't get home directory path: environment variable not found
```

#### Summary of Changes
Only on Windows, if the `HOME` env variable is not set, automatically fall back to the `USERPROFILE` variable, and if that is not set then throws an error.

- fixes solana-labs/solana#35558

### CODE REVIEW

File: sdk/cargo-build-sbf/src/main.rs [hunk 1]
```diff
@@ -135,11 +135,31 @@ pub fn is_version_string(arg: &str) -> Result<(), String> {
     Err("a version string may start with 'v' and contains major and minor version numbers separated by a dot, e.g. v1.32 or 1.32".to_string())
 }
 
+fn get_home_dir() -> PathBuf {
```
Comment (joncinque) [inline sdk/cargo-build-sbf/src/main.rs]: nit: `get_` is not idiomatically rust, and `home_dir()` is preferred

File: sdk/cargo-build-sbf/src/main.rs [hunk 2]
```diff
@@ -135,11 +135,31 @@ pub fn is_version_string(arg: &str) -> Result<(), String> {
...
+    PathBuf::from(
+        env::var("HOME")
+            .or_else(|err| {
+                #[cfg(windows)]
+                {
+                    debug!("Could not read env variable 'HOME': {}", err);
+                    debug!("Falling back to 'USERPROFILE'");
```
Comment (joncinque) [inline sdk/cargo-build-sbf/src/main.rs]: nit: can you combine these into one debug line?

File: sdk/cargo-build-sbf/src/main.rs [hunk 3]
```diff
@@ -135,11 +135,31 @@ pub fn is_version_string(arg: &str) -> Result<(), String> {
...
+                    env::var("USERPROFILE")
+                }
+
+                #[cfg(not(windows))]
+                {
+                    Err(e)
```
Comment (joncinque) [inline sdk/cargo-build-sbf/src/main.rs]: I don't think this will compile with non-windows, should be `Err(err)`

File: sdk/cargo-build-sbf/src/main.rs [hunk 4]
```diff
@@ -135,11 +135,31 @@ pub fn is_version_string(arg: &str) -> Result<(), String> {
     Err("a version string may start with 'v' and contains major and minor version numbers separated by a dot, e.g. v1.32 or 1.32".to_string())
 }
 
+fn get_home_dir() -> PathBuf {
+    PathBuf::from(
+        env::var("HOME")
```
Comment (joncinque) [inline sdk/cargo-build-sbf/src/main.rs]: It looks like the `home` crate uses `env::var_os`, which seems like a better option for Windows (and also works for non-Windows).  Can we use that here?

File: sdk/cargo-build-sbf/src/main.rs [hunk 5]
```diff
@@ -135,11 +135,31 @@ pub fn is_version_string(arg: &str) -> Result<(), String> {
...
+            .or_else(|err| {
+                #[cfg(windows)]
+                {
+                    debug!("Could not read env variable 'HOME': {}", err);
+                    debug!("Falling back to 'USERPROFILE'");
+                    env::var("USERPROFILE")
```
Comment (joncinque) [inline sdk/cargo-build-sbf/src/main.rs]: Same here, let's use `env::var_os` instead

**Review by joncinque — COMMENTED** [review]
Thanks for the contribution! I looked at how cargo / rustup do this, and they use a specialty crate just for giving the user's homedir in different OS's and environments: https://github.com/rust-lang/cargo/tree/master/crates/home

Since some people might have set a HOME env variable in Windows in the past to get things to work, we should avoid breaking them -- meaning, this looks like the best approach.

Just some nits to work out -- let me know if you have any questions!

File: sdk/cargo-build-sbf/src/main.rs (hunk 3 above)
Comment (KartikSoneji) [reply sdk/cargo-build-sbf/src/main.rs]: Oops, that's what I get for coding this at 2am.

File: sdk/cargo-build-sbf/src/main.rs (hunk 1 above)
Comment (KartikSoneji) [reply sdk/cargo-build-sbf/src/main.rs]: Oh didn't, know that I based it off `get_latest_platform_tools_version()` and `get_base_rust_version()`.
Pushed a fix.

File: sdk/cargo-build-sbf/src/main.rs (hunk 2 above)
Comment (KartikSoneji) [reply sdk/cargo-build-sbf/src/main.rs]: Done.

File: sdk/cargo-build-sbf/src/main.rs (hunk 4 above)
Comment (KartikSoneji) [reply sdk/cargo-build-sbf/src/main.rs]: Hmm that changes the return type from `Result<String, _>` to `Option<String>`.
So the error messages will change too, is that OK?

Comment (KartikSoneji) [reply sdk/cargo-build-sbf/src/main.rs]: Also from what I understand, the only difference between `var_os()` and `var()` is that the latter throws if the string is not valid unicode. Is that possible on Windows?

Comment (KartikSoneji) [reply sdk/cargo-build-sbf/src/main.rs]: Huh apparently it is https://github.com/rust-lang/rust/issues/12056

File: sdk/cargo-build-sbf/src/main.rs (hunk 1 above)
Comment (joncinque) [reply sdk/cargo-build-sbf/src/main.rs]: Convention isn't always followed unfortunately :sweat_smile:

**Review by joncinque — APPROVED** [review]
Thanks for your contribution!

**Comment by KartikSoneji** [comment]
Appreciate the quick response!
