### PR TITLE
Return signature verification errors through the RPC as `TransactionError` rather than JSON RPC API errors

### LINKED ISSUE #4122: simulateTransaction RPC incorrent response
#### Problem

According to [documentation](https://solana.com/docs/rpc/http/simulatetransaction#result) the errors of transaction simulation are supposed to be returned inside `err` field. If signature verification fails it should probably be returned as [SignatureFailure](https://github.com/solana-labs/solana/blob/c0c60386544ec9a9ec7119229f37386d9f070523/sdk/src/transaction/error.rs#L70). But it is returned as an rpc error:
```
curl https://api.devnet.solana.com -s -X POST -H "Content-Type: application/json" -d '
  {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "simulateTransaction",
    "params": [
      "AfdiIh1VJVFHoZirs4OV3QgbI9V09KI/Iqotz+kuuWIjg4uwOvZWpb5Ko2FpFbi+QjmRBxkNV4lUmfgYkaGp614BAAEDtXNbCOnvYthBmiJo0S/5JMGj2g1Z6lcS7aM8k9n4Ik7Ee6OvBADQGFw/1hMiY7ym3f4iop/7XcsALwYRoNt9LAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAgIAAQwCAAAAQEIPAAAAAAA=",
      {
        "encoding":"base64",
        "sigVerify":true
      }
    ]
  }
'

{"jsonrpc":"2.0","error":{"code":-32003,"message":"Transaction signature verification failure"},"id":1}

```

#### Proposed Solution

Either the response or the documentation should be fixed.

### PR DESCRIPTION
**Pull request by steveluscher**
#### Problem

There exists `TransactionError::SignatureFailure`. Until [5 years ago](https://github.com/solana-labs/solana/pull/13080/files) this would be returned as `err` in the simulation result when calling `send_transaction()` or `simulate_transaction()`. After that point, the whole request would fail with a JSON RPC API error.

#### Summary of Changes

This PR puts it back the way it was. Now:

* a signature verification failure in `simulate_transaction()` with `sigVerify` set to `true` will return a `RpcSimulateTransactionResult` with `err` set to `TransactionError::SignatureFailure`
* a signature verification failure in `send_transaction()` with `skipPreflight` set to `false` will return a `RpcSimulateTransactionResult` with `err` set to `TransactionError::SignatureFailure` as the `data` of the JSON RPC API error representing the preflight error.

If none of that made any sense, just look at the tests.

Fixes #4122.

### CODE REVIEW

File: rpc/src/rpc.rs [hunk 1]
```diff
@@ -6099,12 +6131,27 @@ pub mod tests {
...
+            "jsonrpc": "2.0",
+            "result": {
+                "context": { "slot": 0, "apiVersion": RpcApiVersion::default() },
+                "value": {
+                    "accounts": null,
+                    "err": "SignatureFailure",
+                    "innerInstructions": null,
+                    "loadedAccountsDataSize": 0,
+                    "fee": null,
+                    "loadedAddresses": { "readonly": [], "writable": [] },
```
Comment (steveluscher) [inline rpc/src/rpc.rs:6127]: Note, for posterity: It's pretty annoying that in `simulate_transaction()` this gets set to `{ "readonly": [], "writable": [] }` upon a signature failure, but in `send_transaction()` it gets set to `null`.

**Comment by steveluscher** [comment]
Talking out loud.

This change, while material, is probably better for everyone.

Presently, if an application wants to catch a signature verification error, they will have to do it at the request callsite.

```ts
try {
    const result = await rpc.simulateTransaction(...).send();
    // ...
} catch(e) {
    if (isSolanaError(e, SOLANA_ERROR__JSON_RPC__SERVER_ERROR_TRANSACTION_SIGNATURE_VERIFICATION_FAILURE)) {
        // ...
    }
}
```

It is _much_ less likely that an application has applied try/catch in that way than it is that they have handling for simulation failures a priori.

```ts
const { value: simulationResult } = await rpc.simulateTransaction(...).send();
if (simulationResult.err) {
    // ...
}
```

After this PR is landed, the handling of signature verification failures will move from the first case to the more common second case, and applications should get more reliable as a result, not less.

**Comment by t-nelson** [comment]
what evidence do you have of the above claim?

**Comment by steveluscher** [comment]
The point of calling `simulateTransaction()` is to obtain a result, so it follows that the majority of people who call this method will have result-handling code. That is to say they will:

1. check for `err`, otherwise
2. inspect the simulation result

Ergo, people using `simulateTransaction()` according to its purpose and ergonomics will already have `err` handling code. Moving sigverify failures into `err` will result in their normal error handling code catching it.

**Comment by alannza** [comment]
I think this change makes sense. It should only fix people who aren't doing exception handling, and it can only break people who aren't doing error result checking, and the latter would already be so nonsensical I don't know what it would mean to break it.

@t-nelson, if you want want more than just reasoning and you want examples:

1. the [first github search result i pulled up](https://github.com/gillsdk/gill/blob/1baab4451c02cfc5c36d3af50a407bc6eeb219ab/docs/content/docs/react/hooks/transactions.mdx#usesimulatetransaction) is a helper library that only checks for errors and not exceptions (although you could imagine this code being wrapped in a React error boundary and handling the API errors at some higher level, but that isn't demonstrated in the docs, ONLY error checking is)
2. This came from [a community reported issue](https://github.com/anza-xyz/agave/issues/4122) so the inconsistency actually tripped a real person up. Presumably _many_ people, since we got a report.

**Review by alannza — DISMISSED** [review]
Makes sense to me!

**Comment by t-nelson** [comment]
did you ask jito how they interpret these results? they probably do more simulations than any other party by two orders of magnitude

**Comment by steveluscher** [comment]
Good idea! Who do I tag, @t-nelson?

**Comment by steveluscher** [comment]
Asked Jito whether it would be helpful for this error to move from the JSON RPC API boundary to the `err` property of the simulation result as a `TransactionError::SignatureFailure`:

> `TransactionError::SignatureFailure` would be great - parsing the responses where its a JSON-RPC error instead of a transaction error can be cumbersome

File: rpc/src/rpc.rs [hunk 2]
```diff
@@ -3884,6 +3875,25 @@ pub mod rpc_full {
                     }
                 }
 
+                let simulation_result = if let Some(err) = verification_error {
+                    TransactionSimulationResult {
```
Comment (t-nelson) [inline rpc/src/rpc.rs]: a helper probably makes this less painful. something like...
```rust
impl TransactionSimulationResult {
    pub fn new_error(err: TransactionError) -> Self {
        Self {
            fee: None,
            inner_instructions: None,
            loaded_accounts_data_size: 0,
            logs: vec![],
            post_balances: None,
            post_simulation_accounts: vec![],
            post_token_balances: None,
            pre_balances: None,
            pre_token_balances: None,
            result: Err(err),
            return_data: None,
            units_consumed: 0,
        }
    }
}
```

**Comment by t-nelson** [comment]
> Asked Jito whether it would be helpful for this error to move from the JSON RPC API boundary to the `err` property of the simulation result as a `TransactionError::SignatureFailure`:
> 
> > `TransactionError::SignatureFailure` would be great - parsing the responses where its a JSON-RPC error instead of a transaction error can be cumbersome

nice. thanks!

**Review by t-nelson — APPROVED** [review]
