### PR TITLE
Do not clean past enqueued snapshot request in AccountsBackgroundService

### LINKED ISSUE #6295: AccountsBackgroundService assert fails for `last_cleaned_block_height <= snapshot_block_height`
#### Problem

Occasionally this assert in AccountsBackgroundService fails:
https://github.com/anza-xyz/agave/blob/640a749ea599a05a1e2e553ed70f835752cb68e8/runtime/src/accounts_background_service.rs#L602

Under normal operation, this case should always be true. For it to be false, `last_cleaned_block_height` must be greater than the slot of the snapshot request just handled. We can see that `last_cleaned_block_height` is updated only when ABS did *not* handle a snapshot request. The invariant is that the root bank here in ABS is in the past compared to any snapshot requests we get in the future. However, we *can* have snapshot requests in the channel but *not* handle them! This would allow the following situation:

* snapshot request channel has a request for slot 10 (needs to be an EAH, since normal snapshots are not sent by `set_root()` until after startup verification is complete)
* the snapshot request is not handled *because startup verification is ongoing*
* thus we drop down into the `else if`, which will flush/clean/shrink on the current root bank
* since startup verification takes some time, the step above could get a root bank at slot 20
* once startup verification completes, we handle the snapshot request. This request is for slot 10.
* after handling the request returns, ABS checks the assert and sees it has failed. Sadness ensues.

Note if the snapshot request channel only contains incremental snapshots—which is quite common—then we'll always be replacing older snapshot requests with newer ones. So once snapshot verification completes, and assuming the default 100 slot incremental snapshot interval, we're pretty much guaranteed to always handle a snapshot request greater than the `last_cleaned_block_height`.

A partial diagnosis and fix was first proposed here: https://discord.com/channels/428295358100013066/1187805174803210341/1374820534671376485, which prompted me to understand and root-cause the problem.

#### Proposed Solution

If startup verification has not completed, we probably need to look at the snapshot request channel and see what the next request would be, and only allow cleaning up to that point.

Another option would be to skip the `else if` block entirely if startup verification is not complete. This will drop down to the `else`, and we'll do only `flush`, which is safe.

### PR DESCRIPTION
**Pull request by brooksprumo**
#### Problem

Please see #6295.

#### Summary of Changes

Do not clean past enqueued snapshot request.

Fixes #6295

Note, needs to be backported to v2.3.

### CODE REVIEW

**Review by roryharr — APPROVED** [review]

File: runtime/src/accounts_background_service.rs [hunk 1]
```diff
@@ -646,7 +674,12 @@ impl AccountsBackgroundService {
                                 .flush_accounts_cache(force_flush, Some(max_clean_slot_inclusive));
 
                             if should_clean {
-                                bank.clean_accounts();
+                                bank.rc.accounts.accounts_db.clean_accounts(
```
Comment (HaoranYi) [inline runtime/src/accounts_background_service.rs:677]: To be safe, maybe we can assert max_clean_slot_inclusive is less or eqal to bank.slot()?

File: runtime/src/accounts_background_service.rs [hunk 2]
```diff
@@ -418,6 +418,24 @@ impl SnapshotRequestHandler {
         );
         Ok(snapshot_root_bank.slot())
     }
+
+    /// Returns the slot of the next snapshot request to be handled
+    fn peek_next_snapshot_request_slot(&self) -> Option<Slot> {
+        // We reuse `get_next_snapshot_request()` here, since it already implements all the logic
+        // for getting the highest priority request, *AND* we leverage its test coverage.
+        // Additionally, since `get_next_snapshot_request()` drops old requests, we might get to
+        // proactively clean up old banks earlier as well!
```
Comment (HaoranYi) [inline runtime/src/accounts_background_service.rs:427]: 👍

**Review by HaoranYi — APPROVED** [review]
lgtm.

**Review by jeffwashington — APPROVED** [review]
lgtm
