### PR TITLE
fix(poh): don't process service messages if we have a record

### LINKED ISSUE #9002: ftv68 paniced with PohRecorder::record failed: MaxHeightReached
`ftv68` was running `v3.1.0-beta.0` and panicked with:

```
[2025-11-10T03:59:01.006465281Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="solPohTickProd" one=1i message="panicked at poh/src/poh_service.rs:416:29:
    PohRecorder::record failed: MaxHeightReached" location="poh/src/poh_service.rs:416:29" version="3.1.0 (src:bd8c57e7; feat:3652419286, client:Agave)"
```

### PR DESCRIPTION
**Pull request by OliverNChalk**
#### Problem

- #9002 : v3.1 nodes are panicking in rare circumstances where they are the leader but decide to abandon their slot and reset to the another leader's bank.
- This was triggered by a logic error where we would process service messages depsite having just cached a record message:

Store the message for later:
```rust
                    // check to see if a record request has been sent
                    if let Ok(record) = record_receiver.try_recv() {
                        // remember the record we just received as the next record to occur
                        *next_record = Some(record);
                        break;
                    }
```
Check service messages because channel is empty (ignoring the stored message):
```rust
                if Self::can_process_service_message(&service_message, &record_receiver)
                {
                    break;
                }
```

The fix is to ensure we don't have a stored message:
```rust
                if next_record.is_none()
                    && Self::can_process_service_message(&service_message, &record_receiver)
                {
                    break;
                }
```

#### Summary of Changes

- Add an `is_none` check to prevent processing service messages when the channel is empty.

Fixes #9002

### CODE REVIEW

File: poh/src/record_channels.rs [hunk 1]
```diff
@@ -58,6 +58,7 @@ pub fn record_channels(track_transaction_indexes: bool) -> (RecordSender, Record
     )
 }
 
+#[derive(Debug)]
```
Comment (tao-stones) [inline poh/src/record_channels.rs:61]: super nit: this probably doesn't need to be committed?

Comment (OliverNChalk) [reply poh/src/record_channels.rs:61]: Test uses `.unwrap()` on channel `try_send`. Can rewrite the test to use `assert!(is_ok)` - that said, is there any reason to not derive Debug here?

Comment (tao-stones) [reply poh/src/record_channels.rs:61]: ah, didn't notice the `unwrap()` part, thought it's leftover from debugging. Thanks for pointing it out. Perfectly fine with it.

File: poh/src/poh_service.rs [hunk 2]
```diff
@@ -543,7 +543,9 @@ impl PohService {
                 }
 
                 // Check if we can break the inner loop to handle a service message.
-                if Self::can_process_service_message(&service_message, &record_receiver) {
+                if next_record.is_none()
```
Comment (tao-stones) [inline poh/src/poh_service.rs:546]: nit: wdyt to include `next_record` in `can_process_service_message()` so the logic of "can break inner loop" is documented in one place?

Comment (OliverNChalk) [reply poh/src/poh_service.rs:546]: Other users of `can_process_service_message` don't have `next_record` unfortunately. I think the whole flow is a bit hard to follow but I think the goal here is to just fix it and not refactor due to Alpenglow making most of this redundant.

**Review by bw-solana — DISMISSED** [review]

**Review by tao-stones — DISMISSED** [review]
:shipit:

File: poh/src/poh_service.rs [hunk 3]
```diff
@@ -845,4 +848,79 @@ mod tests {
...
+            exit.clone(),
+            DEFAULT_TICKS_PER_SLOT,
+            DEFAULT_PINNED_CPU_CORE,
+            DEFAULT_HASHES_PER_BATCH,
+            record_receiver,
+            poh_service_message_receiver,
+        );
+
+        // Let poh service process the messages.
+        std::thread::sleep(Duration::from_millis(50));
```
Comment (steviez) [inline poh/src/poh_service.rs]: We've had some flaky test failures that came down to timing / sleeps; running a bunch of tests in parallel can cause some whacky stuff with timing.

I haven't looked at PoH in a while, but briefly scanning, I think the following could make it more robust:
- Add a (test only) method to `RecordSender` that calls `is_empty()` on the crossbeam channel
- Do `while !record_sender.is_empty() { sleep(1ms) }` to spin until channel empty
    - This way we know the message will have been received
    - In the happy path, we potentially finish much sooner than 50ms (ie 1ms or 2ms)
- Maybe add a timeout to the while loop to bail after 1s of checking or something and assert that we don't hit the timeout
    - Timeout prevents the test from hanging, and asserting that we didn't timeout gives us a more more direct failure should this thing fail to complete in time

**Review by steviez — COMMENTED** [review]
I'm deferring correctness of the actual change to others, so just the comment on the test.

I also confirmed that the unit test fails without the addition to `PohService::tick_producer()`

File: poh/src/poh_service.rs (hunk 3 above)
Comment (OliverNChalk) [reply poh/src/poh_service.rs]: dc92c0982347ff60480bbb2f825c298c8e0ecb54

**Review by tao-stones — APPROVED** [review]

**Review by steviez — APPROVED** [review]
