### PR TITLE
blockstore: Use rocksdb ReadOnly mode over Secondary

### LINKED ISSUE #7216: Long Blockstore::open() times for secondary process
#### Problem
We got a report about `Blockstore::open()` taking a long time when called from a secondary process while `agave-validator` is running. I was able to reproduce this issue as well:
```
// Run 1: agave-ledger-tool bounds 
[... INFO  solana_ledger::blockstore] Opening blockstore done; blockstore open took 6121.5s
// Run 2: agave-ledger-tool bounds 
[... INFO  solana_ledger::blockstore] Opening blockstore done; blockstore open took 9779.3s
```

For both the initial report and my reproduction, the node was running with config typical of RPC nodes. Namely, these two flags:
```
--enable-rpc-transaction-history
--limit-ledger-size 400000000
```

#### Steps to reproduce
1. Start a node with the flags mentioned above; I'm running 09fe49b95cdd440af471702387b17605f07c3196 (master)
2. Let it run for a day or two to fill up rocksdb
3. Run any `agave-ledger-tool blockstore` subcommand such as `bounds`

#### Additional Context
We had investigated some a slowdown like this before (relevant issues below). The issues seemed to be related to a rocksdb version upgrade, and the original reporter mentioned downgrading rocksdb mitigated the issue for them:
- https://github.com/anza-xyz/agave/issues/5798
- https://github.com/anza-xyz/agave/pull/5823

### PR DESCRIPTION
**Pull request by kskalski**
#### Problem
Blockstore supports two types of access that do not modify the data
(https://github.com/facebook/rocksdb/wiki/Read-only-and-Secondary-instances),
among which Secondary offers extra capabilities that are not used by the ledger tool.
Since there were also cases where secondary access had degraded performance, the best is to use ReadOnly when writing is not needed.

#### Summary of Changes
* introduce `AccessType::ReadOnly` for opening blockstore
* switch ledger-tool to use it

Fixes #7216

### CODE REVIEW

**Review by brooksprumo — COMMENTED** [review]
Looks good to me.

r+ SME approval.

**Review by steviez — COMMENTED** [review]
I think I'm onboard with the change. However, given that we know that `Secondary` has an issue (at least in the way we use it), I think I'd be more inclined to just replace `Secondary` with `ReadOnly`. If we ever decide we want the functionality that `Secondary` provides, we can reintroduce it then

**Comment by kskalski** [comment]
Sure, if we don't foresee any usefulness of secondary access - I guess this could be useful if there was a side-car server that accesses data for serving RPCs, but even if there is ever a need like this it won't use the same code paths, which are only used by ledger tool and our internal tests.

**Review by brooksprumo — COMMENTED** [review]
:shipit: 

r+ SME approval

File: ledger-tool/src/blockstore.rs [hunk 1]
```diff
@@ -39,6 +39,14 @@ use {
     },
 };
 
+/// Blockstore supports two types of access that do not modify the data
+/// (https://github.com/facebook/rocksdb/wiki/Read-only-and-Secondary-instances),
+/// among which Secondary offers extra capabilities that are not used by the ledger tool.
+/// Since there were also cases where secondary access had degraded performance
+/// (https://github.com/anza-xyz/agave/issues/7216), the best is to use ReadOnly when writing
+/// is not needed.
+pub(super) const NON_WRITABLE_BLOCKSTORE_ACCESS: AccessType = AccessType::ReadOnly;
```
Comment (steviez) [inline ledger-tool/src/blockstore.rs]: nit:
- Since we're ripping `Secondary` out, I don't think we need to explicitly mention it. That is, there is no reason to mention `Secondary` for `ledger-tool` if the enum doesn't have a `Secondary` case IMO
- The link to the rocksdb docs is good, but I kind of think it should live with the `AccessType` enum
- `NON WRITABLE` sounds a little awkward to me. Also, since we're ripping out `Secondary` (with no plans to re-add) it, I'm not sure we need this constant at all

File: ledger-tool/src/ledger_utils.rs [hunk 2]
```diff
@@ -80,7 +80,7 @@ pub(crate) enum LoadAndProcessLedgerError {
     #[error("failed to create all run and snapshot directories: {0}")]
     CreateAllAccountsRunAndSnapshotDirectories(#[source] std::io::Error),
 
-    #[error("custom accounts path is not supported with secondary blockstore access")]
+    #[error("custom accounts path is not supported with non-writable blockstore access")]
```
Comment (steviez) [inline ledger-tool/src/ledger_utils.rs]: nit: I'd probably prefer `read-only` over `non-writable` as I think that is more standard nomenclature; `non-writable` might have been more fitting with `Secondary` still as an option

File: ledger-tool/src/ledger_utils.rs [hunk 3]
```diff
@@ -238,7 +238,7 @@ pub fn load_and_process_ledger(
             .join(LEDGER_TOOL_DIRECTORY)
             .join("accounts");
         info!(
-            "Default accounts path is switched aligning with Blockstore's secondary access: \
+            "Default accounts path is switched aligning with Blockstore's non-writable access: \
```
Comment (steviez) [inline ledger-tool/src/ledger_utils.rs]: nit: Same here, `read-only`

File: ledger/src/blockstore_processor.rs [hunk 4]
```diff
@@ -2399,12 +2399,12 @@ pub mod tests {
...
     };
 
-    // Convenience wrapper to optionally process blockstore with Secondary access.
+    // Convenience wrapper to optionally process blockstore with ReadOnly access.
     //
     // Setting up the ledger for a test requires Primary access as items will need to be inserted.
-    // However, once a Secondary access has been opened, it won't automatically see updates made by
-    // the Primary access. So, open (and close) the Secondary access within this function to ensure
-    // that "stale" Secondary accesses don't propagate.
+    // However, once a ReaDOnly access has been opened, it won't automatically see updates made by
```
Comment (steviez) [inline ledger/src/blockstore_processor.rs]: nit: `ReaDOnly` ==> `ReadOnly`

File: ledger/src/blockstore_db.rs [hunk 5]
```diff
@@ -196,13 +194,10 @@ impl Rocks {
             new_cf_descriptor::<columns::MerkleRootMeta>(options, oldest_slot),
         ];
 
-        // If the access type is Secondary, we don't need to open all of the
+        // If the access type is read-only, we don't need to open all of the
```
Comment (steviez) [inline ledger/src/blockstore_db.rs]: nit: Not to punish a good deed but since we're cleaning up, this logic might be better off in `AccessType`. Ie, maybe a function like `AccessType::must_open_all_column_families() -> bool`

File: ledger/src/blockstore_db.rs [hunk 6]
```diff
@@ -1185,9 +1180,11 @@ fn get_db_options(blockstore_options: &BlockstoreOptions) -> Options {
...
 
     // Allow Rocks to open/keep open as many files as it needs for performance;
-    // however, this is also explicitly required for a secondary instance.
-    // See https://github.com/facebook/rocksdb/wiki/Secondary-instance
-    options.set_max_open_files(-1);
+    // It is not required for read-only access
+    // https://github.com/facebook/rocksdb/wiki/Read-only-and-Secondary-instances#feature-comparison
+    if !blockstore_options.access_type.is_non_writable() {
+        options.set_max_open_files(-1);
+    }
```
Comment (steviez) [inline ledger/src/blockstore_db.rs]: I know it is not required to set `-1` for read-only access, but are there any possible negative impacts from this ? Ie, we presumably use the default if we don't set it; is that default sufficient for all cases ?

I'm inclined to investigate + add this change of behavior in a separate PR

File: ledger/src/blockstore_options.rs [hunk 7]
```diff
@@ -45,10 +45,15 @@ pub enum AccessType {
...
-    Secondary,
+    /// Read-only access. When the Read-only instance is created, it gets a static
+    /// read-only view of the Primary Instance’s database contents.
+    ReadOnly,
+}
+
+impl AccessType {
+    pub fn is_non_writable(&self) -> bool {
+        matches!(self, AccessType::ReadOnly)
+    }
```
Comment (steviez) [inline ledger/src/blockstore_options.rs]: nit: Same here, `non_writable` is kind of awkward wording. If we're concerned about `read-only` matching one of the variants (I'm not but could see it), we could use `is_read_write()` and add a negation

File: ledger-tool/src/main.rs [hunk 8]
```diff
@@ -2571,7 +2571,7 @@ fn main() {
                     };
                     process_options.halt_at_slot = Some(parent_slot);
 
-                    // PrimaryForMaintenance needed over Secondary to purge any
+                    // PrimaryForMaintenance needed over ReadOnly to purge any
```
Comment (steviez) [inline ledger-tool/src/main.rs]: nit: Thanks for updating, maybe we don't need to mention the other access type directly and can just say `PrimaryForMaintenance needed to purge(write) any existing ...` to be more general

File: ledger/src/blockstore_db.rs [hunk 9]
```diff
@@ -124,18 +124,16 @@ impl Rocks {
...
+                    "Opening Rocks with read only access. This additional access could \
+                     temporarily degrade other accesses, such as by agave-validator"
                 );
-                DB::open_cf_descriptors_as_secondary(
+                DB::open_cf_descriptors_read_only(
                     &db_options,
                     &path,
-                    &secondary_path,
                     cf_descriptors,
+                    false, /* do not error if log file exists */
```
Comment (steviez) [inline ledger/src/blockstore_db.rs]: nit: Thank you for adding this but slight nit to just use the variable name with the underscores. Also, I'm surprised the linter didn't care about `// comment` vs `/* comment */` but if it doesn't care then I don't care either

**Review by steviez — COMMENTED** [review]
Things look good, a couple nits and a couple requests for more cleanup since you seem willing and I think it all ties into this PR nicely 😄

File: ledger/src/blockstore_db.rs (hunk 5 above)
Comment (kskalski) [reply ledger/src/blockstore_db.rs]: Hm, I don't believe decision on whether to open all columns or which is a property of access type, but I added a `must_open_all_column_families` to blockstore_db nearby other like `should_enable_compression` - looks like this mod is a decision maker on how to treat which columns (including: required vs optional)

File: ledger-tool/src/blockstore.rs (hunk 1 above)
Comment (kskalski) [reply ledger-tool/src/blockstore.rs]: done

File: ledger-tool/src/ledger_utils.rs (hunk 2 above)
Comment (kskalski) [reply ledger-tool/src/ledger_utils.rs]: done

File: ledger-tool/src/ledger_utils.rs (hunk 3 above)
Comment (kskalski) [reply ledger-tool/src/ledger_utils.rs]: done

File: ledger/src/blockstore_processor.rs (hunk 4 above)
Comment (kskalski) [reply ledger/src/blockstore_processor.rs]: done

File: ledger/src/blockstore_db.rs (hunk 6 above)
Comment (kskalski) [reply ledger/src/blockstore_db.rs]: ok, I brought back setting -1 and just updated column that it may not be required

File: ledger/src/blockstore_options.rs (hunk 7 above)
Comment (kskalski) [reply ledger/src/blockstore_options.rs]: removed

File: ledger-tool/src/main.rs (hunk 8 above)
Comment (kskalski) [reply ledger-tool/src/main.rs]: done

File: ledger/src/blockstore_db.rs (hunk 9 above)
Comment (kskalski) [reply ledger/src/blockstore_db.rs]: I've seen this style of annotating params, so I don't believe this is lint denied, but local var looks good too -> changed

File: ledger-tool/src/main.rs [hunk 10]
```diff
@@ -2571,8 +2571,8 @@ fn main() {
                     };
                     process_options.halt_at_slot = Some(parent_slot);
 
-                    // PrimaryForMaintenance needed over Secondary to purge any
-                    // existing simulated shreds from previous runs
+                    // PrimaryForMaintenance needed to purge(write) any existing simulated shreds
```
Comment (steviez) [inline ledger-tool/src/main.rs]: Sorry, this was a typo in my comment 🤦 ; can you change `purge(write)` to `purge (write)`

File: ledger/src/blockstore_db.rs (hunk 9 above)
Comment (steviez) [reply ledger/src/blockstore_db.rs]: Ahh, sorry, I meant to do:
```rust
false, /* do_not_error_if_log_file_exists */
```
instead of
```rust
false, /* do not error if log file exists */
```
to make the comment match the parameter name exactly. Separate variable is good with me too tho so no further action needed

File: ledger/src/blockstore_options.rs [hunk 11]
```diff
@@ -45,10 +45,10 @@ pub enum AccessType {
     Primary,
     /// Primary (read/write) access with RocksDB automatic compaction disabled.
     PrimaryForMaintenance,
-    /// Secondary (read) access; multiple processes can have Secondary access.
-    /// Additionally, Secondary access can be obtained while another process
-    /// already has Primary access.
-    Secondary,
+    /// Read-only access. When the Read-only instance is created, it gets a static
+    /// read-only view of the Primary Instance’s database contents
+    /// (https://github.com/facebook/rocksdb/wiki/Read-only-and-Secondary-instances).
```
Comment (steviez) [inline ledger/src/blockstore_options.rs]: nit: Last one but I think the URL would be better served to go on the type (`AccessType`) instead of the variant (`ReadOnly`). The URL name says "read only and secondary", but the document is a pretty good explainer of all 3. So, I'm thinking for the whole thing:
```rust
/// The mode to open a Blockstore with. For more details, see:
/// https://github.com/facebook/rocksdb/wiki/Read-only-and-Secondary-instances
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum AccessType {
    ...
    /// Read only access; multiple processes can obtain ReadOnly access.
    /// ReadOnly instance gets a static view of the database at creation time.
    ReadOnly,
}
```

File: ledger/src/blockstore_db.rs (hunk 5 above)
Comment (steviez) [reply ledger/src/blockstore_db.rs]: Yeah fair enough, I like what you did so marking this one resolved

File: ledger-tool/src/main.rs (hunk 10 above)
Comment (kskalski) [reply ledger-tool/src/main.rs]: done

File: ledger/src/blockstore_options.rs (hunk 11 above)
Comment (kskalski) [reply ledger/src/blockstore_options.rs]: done

**Review by steviez — APPROVED** [review]
LGTM - Thank you for digging in and finding us a mitigation for https://github.com/anza-xyz/agave/issues/7216 !
