### PR TITLE
cli: fix flaky `test_cli_program_deploy_with_args`

### LINKED ISSUE #7911: cli: test_cli_program_deploy_with_args::with_compute_unit_price is flaky
#### Problem
```
failures:

---- test_cli_program_deploy_with_args::with_compute_unit_price stdout ----
Waiting for fees to stabilize 1...
Waiting for fees to stabilize 2...
Waiting for fees to stabilize 3...
Waiting for fees to stabilize 4...
Waiting for fees to stabilize 5...
Waiting for fees to stabilize 6...
Waiting for fees to stabilize 7...
Waiting for fees to stabilize 8...
Waiting for fees to stabilize 9...
Waiting for fees to stabilize 10...
Requesting airdrop of 0.000176664 SOL

Signature: 4SWEMzzJkFHsrKSDCxN3eXNTqZmU1EU3QrTw9HqMLdtAjWaeauSFo2ShMBnTzCoGZsFL49YLpQJ4HX87oKitQnHm


thread 'test_cli_program_deploy_with_args::with_compute_unit_price' panicked at cli/tests/program.rs:3074:9:
assertion failed: `Ok(SetComputeUnitLimit(2670))` does not match `Ok(ComputeBudgetInstruction::SetComputeUnitLimit(2970))`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    test_cli_program_deploy_with_args::with_compute_unit_price

test result: FAILED. 26 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 38.72s

error: test failed, to rerun pass `--test program`
```

#### Proposed Solution
Would be nice to know why its flaky.

### PR DESCRIPTION
**Pull request by Not-Sarthak**
## Summary

Fixes #7911

The test `test_cli_program_deploy_with_args` was flaky because it relied on `get_signatures_for_address` returning all transaction signatures immediately after deploy confirmation. Due to RPC indexing lag, the deploy transaction signature was sometimes missing from the results, causing `signatures.last()` to return a write transaction instead. This made the `with_compute_unit_price` case fail on `SetComputeUnitLimit(2970)` because it was checking a write tx (`SetComputeUnitLimit(2670)`) instead of the deploy tx.

Additionally, `get_transaction` could return null for recently confirmed transactions whose historical data hadn't been indexed yet.

### Fix

1. Extract the deploy signature directly from the `CliProgramId` JSON response (`signature` field) instead of relying on positional indexing from `get_signatures_for_address`.
2. Poll `get_signatures_for_address` until the deploy signature appears in the results before fetching any transaction data, ensuring the RPC index is fully caught up.

`fetch_and_decode_transaction` remains a straightforward fetch with no retry logic.

### Test plan

Tested locally by running `cargo test -p solana-cli test_cli_program_deploy_with_args` (all 3 test cases: `default`, `with_compute_unit_price`, `use_rpc`) 20 consecutive times (120 total test executions) with 0 failures.

Also verified the root cause by testing intermediate approaches:
- Original code (no fix): fails intermittently - `signatures.last()` returns a write tx when the deploy tx isn't indexed yet
- Deploy signature from JSON only (no polling): 59/60 passed - `get_transaction` can still return null for the not-yet-indexed deploy signature
- Deploy signature from JSON + polling (this PR): 120/120 passed

### CODE REVIEW

File: cli/tests/program.rs [hunk 1]
```diff
@@ -3089,39 +3091,24 @@ async fn test_cli_program_deploy_with_args(compute_unit_price: Option<u64>, use_
...
+    let json_obj = json.as_object().unwrap();
+    let program_pubkey_str = json_obj.get("programId").unwrap().as_str().unwrap();
     assert_eq!(
         program_keypair.pubkey(),
         Pubkey::from_str(program_pubkey_str).unwrap()
     );
+    let deploy_signature = json_obj
+        .get("signature")
+        .and_then(|s| s.as_str())
+        .map(|s| Signature::from_str(s).unwrap());
```
Comment (joncinque) [inline cli/tests/program.rs]: nit: since this variable isn't used otherwise, let's just unwrap right away and remove `deploy_sig`
```suggestion
    let deploy_signature = json_obj
        .get("signature")
        .and_then(|s| s.as_str())
        .map(|s| Signature::from_str(s).unwrap())
        .unwrap();
```

File: cli/tests/program.rs [hunk 2]
```diff
@@ -3146,10 +3133,32 @@ async fn test_cli_program_deploy_with_args(compute_unit_price: Option<u64>, use_
...
+            .get_signatures_for_address_with_config(
+                &keypair.pubkey(),
+                GetConfirmedSignaturesForAddress2Config {
+                    commitment: Some(CommitmentConfig::confirmed()),
+                    ..GetConfirmedSignaturesForAddress2Config::default()
+                },
+            )
+            .await
+            .unwrap();
+        let sigs: Vec<_> = statuses
```
Comment (joncinque) [inline cli/tests/program.rs]: nit: let's rename this to `signatures`

**Review by joncinque — COMMENTED** [review]
Thanks for your contribution! The changes make sense to me, just a couple of nits

File: cli/tests/program.rs (hunk 2 above)
Comment (Not-Sarthak) [reply cli/tests/program.rs]: fixed both the issues, thanks for flagging those out!

**Review by joncinque — APPROVED** [review]
Thanks!
